/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedUserResponseDto } from '../../models/paginated-user-response-dto';

export interface UsersControllerFindAll$Params {

/**
 * Filter by role
 */
  role?: 'admin' | 'tenant';

/**
 * Filter by owner ID
 */
  idOwner?: string;

/**
 * Filter by active status
 */
  isActive?: boolean;

/**
 * Search by name or email
 */
  search?: string;

/**
 * Page number
 */
  page?: number;

/**
 * Items per page
 */
  limit?: number;
}

export function usersControllerFindAll(http: HttpClient, rootUrl: string, params?: UsersControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedUserResponseDto>> {
  const rb = new RequestBuilder(rootUrl, usersControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('role', params.role, {});
    rb.query('idOwner', params.idOwner, {});
    rb.query('isActive', params.isActive, {});
    rb.query('search', params.search, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedUserResponseDto>;
    })
  );
}

usersControllerFindAll.PATH = '/api/users';
