/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NodeAssignmentResponseDto } from '../../models/node-assignment-response-dto';
import { UpdateNodeAssignmentDto } from '../../models/update-node-assignment-dto';

export interface NodeAssignmentsControllerUpdate$Params {
  id: string;
      body: UpdateNodeAssignmentDto
}

export function nodeAssignmentsControllerUpdate(http: HttpClient, rootUrl: string, params: NodeAssignmentsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeAssignmentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, nodeAssignmentsControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NodeAssignmentResponseDto>;
    })
  );
}

nodeAssignmentsControllerUpdate.PATH = '/api/node-assignments/{id}';
