/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NodeModelResponseDto } from '../../models/node-model-response-dto';

export interface NodeModelsControllerFindOne$Params {
  id: string;
}

export function nodeModelsControllerFindOne(http: HttpClient, rootUrl: string, params: NodeModelsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeModelResponseDto>> {
  const rb = new RequestBuilder(rootUrl, nodeModelsControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NodeModelResponseDto>;
    })
  );
}

nodeModelsControllerFindOne.PATH = '/api/node-models/{id}';
