/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface NodeModelsControllerFindAll$Params {
  page?: number;
  limit?: number;
  search?: string;
  vendor?: string;
  protocol?: string;
  hardwareClass?: string;
}

export function nodeModelsControllerFindAll(http: HttpClient, rootUrl: string, params?: NodeModelsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, nodeModelsControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('search', params.search, {});
    rb.query('vendor', params.vendor, {});
    rb.query('protocol', params.protocol, {});
    rb.query('hardwareClass', params.hardwareClass, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

nodeModelsControllerFindAll.PATH = '/api/node-models';
