/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UploadStatusResponseDto } from '../../models/upload-status-response-dto';

export interface UploadControllerUpload$Params {
      body: {

/**
 * Spatial file (GeoJSON, CSV, KML, Shapefile ZIP)
 */
'file': Blob;

/**
 * Optional project ID
 */
'projectId'?: string;
}
}

export function uploadControllerUpload(http: HttpClient, rootUrl: string, params: UploadControllerUpload$Params, context?: HttpContext): Observable<StrictHttpResponse<UploadStatusResponseDto>> {
  const rb = new RequestBuilder(rootUrl, uploadControllerUpload.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UploadStatusResponseDto>;
    })
  );
}

uploadControllerUpload.PATH = '/api/webgis/upload';
