/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SensorResponseDto } from '../../models/sensor-response-dto';
import { UpdateSensorDto } from '../../models/update-sensor-dto';

export interface SensorsControllerUpdate$Params {
  id: string;
      body: UpdateSensorDto
}

export function sensorsControllerUpdate(http: HttpClient, rootUrl: string, params: SensorsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<SensorResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sensorsControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SensorResponseDto>;
    })
  );
}

sensorsControllerUpdate.PATH = '/api/sensors/{id}';
