/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateSensorDto } from '../../models/create-sensor-dto';
import { SensorResponseDto } from '../../models/sensor-response-dto';

export interface SensorsControllerCreate$Params {
      body: CreateSensorDto
}

export function sensorsControllerCreate(http: HttpClient, rootUrl: string, params: SensorsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<SensorResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sensorsControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SensorResponseDto>;
    })
  );
}

sensorsControllerCreate.PATH = '/api/sensors';
