/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LayerResponseDto } from '../../models/layer-response-dto';

export interface LayersControllerSeedCore$Params {
  projectId: string;
}

export function layersControllerSeedCore(http: HttpClient, rootUrl: string, params: LayersControllerSeedCore$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LayerResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, layersControllerSeedCore.PATH, 'post');
  if (params) {
    rb.path('projectId', params.projectId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LayerResponseDto>>;
    })
  );
}

layersControllerSeedCore.PATH = '/api/webgis/layers/seed-core/{projectId}';
