/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LayerResponseDto } from '../../models/layer-response-dto';
import { UpdateStyleDto } from '../../models/update-style-dto';

export interface LayersControllerUpdateStyle$Params {
  id: string;
      body: UpdateStyleDto
}

export function layersControllerUpdateStyle(http: HttpClient, rootUrl: string, params: LayersControllerUpdateStyle$Params, context?: HttpContext): Observable<StrictHttpResponse<LayerResponseDto>> {
  const rb = new RequestBuilder(rootUrl, layersControllerUpdateStyle.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LayerResponseDto>;
    })
  );
}

layersControllerUpdateStyle.PATH = '/api/webgis/layers/{id}/style';
