/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FeatureResponseDto } from '../../models/feature-response-dto';

export interface FeaturesControllerFindOne$Params {
  id: string;
}

export function featuresControllerFindOne(http: HttpClient, rootUrl: string, params: FeaturesControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<FeatureResponseDto>> {
  const rb = new RequestBuilder(rootUrl, featuresControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FeatureResponseDto>;
    })
  );
}

featuresControllerFindOne.PATH = '/api/webgis/features/{id}';
