/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateFeatureDto } from '../../models/create-feature-dto';
import { FeatureResponseDto } from '../../models/feature-response-dto';

export interface FeaturesControllerCreate$Params {
  layerId: string;
      body: CreateFeatureDto
}

export function featuresControllerCreate(http: HttpClient, rootUrl: string, params: FeaturesControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<FeatureResponseDto>> {
  const rb = new RequestBuilder(rootUrl, featuresControllerCreate.PATH, 'post');
  if (params) {
    rb.path('layerId', params.layerId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FeatureResponseDto>;
    })
  );
}

featuresControllerCreate.PATH = '/api/webgis/features/{layerId}';
