/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SensorTypeResponseDto } from '../../models/sensor-type-response-dto';

export interface SensorTypesControllerFindAll$Params {
  page?: number;
  limit?: number;
  search?: string;
}

export function sensorTypesControllerFindAll(http: HttpClient, rootUrl: string, params?: SensorTypesControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SensorTypeResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, sensorTypesControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('search', params.search, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SensorTypeResponseDto>>;
    })
  );
}

sensorTypesControllerFindAll.PATH = '/api/sensor-types';
