/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SensorTypeResponseDto } from '../../models/sensor-type-response-dto';
import { UpdateSensorTypeDto } from '../../models/update-sensor-type-dto';

export interface SensorTypesControllerUpdate$Params {
  id: string;
      body: UpdateSensorTypeDto
}

export function sensorTypesControllerUpdate(http: HttpClient, rootUrl: string, params: SensorTypesControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<SensorTypeResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sensorTypesControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SensorTypeResponseDto>;
    })
  );
}

sensorTypesControllerUpdate.PATH = '/api/sensor-types/{id}';
