/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateSensorTypeDto } from '../../models/create-sensor-type-dto';
import { SensorTypeResponseDto } from '../../models/sensor-type-response-dto';

export interface SensorTypesControllerCreate$Params {
      body: CreateSensorTypeDto
}

export function sensorTypesControllerCreate(http: HttpClient, rootUrl: string, params: SensorTypesControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<SensorTypeResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sensorTypesControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SensorTypeResponseDto>;
    })
  );
}

sensorTypesControllerCreate.PATH = '/api/sensor-types';
