/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ScadaBindingOptionItemDto } from '../../models/scada-binding-option-item-dto';

export interface ScadaBindingOptionsControllerFindAll$Params {
  ownerId?: string;
  projectId?: string;
  sensorTypeId?: string;
  search?: string;
}

export function scadaBindingOptionsControllerFindAll(http: HttpClient, rootUrl: string, params?: ScadaBindingOptionsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ScadaBindingOptionItemDto>>> {
  const rb = new RequestBuilder(rootUrl, scadaBindingOptionsControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('ownerId', params.ownerId, {});
    rb.query('projectId', params.projectId, {});
    rb.query('sensorTypeId', params.sensorTypeId, {});
    rb.query('search', params.search, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ScadaBindingOptionItemDto>>;
    })
  );
}

scadaBindingOptionsControllerFindAll.PATH = '/api/scada/binding-options';
