/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActivityLogItem {

  /**
   * Badge label
   */
  badge: string;

  /**
   * Activity description
   */
  description?: string;

  /**
   * Highlight important events
   */
  highlight: boolean;

  /**
   * Activity ID
   */
  id: string;

  /**
   * Related entity details
   */
  relatedEntity?: {
};

  /**
   * Severity level
   */
  severity: 'info' | 'warning' | 'success' | 'error';

  /**
   * Time ago formatted
   */
  timeAgo: string;

  /**
   * Activity timestamp
   */
  timestamp: string;

  /**
   * Activity title
   */
  title: string;

  /**
   * Activity type
   */
  type: 'webhook' | 'alert' | 'sync' | 'node_status' | 'owner_update' | 'sensor_added';
}
