/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActivityLogItem } from '../models/activity-log-item';
export interface ActivityLogResponseDto {

  /**
   * Recent activity logs
   */
  activities: Array<ActivityLogItem>;
}
