/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AlertItem {

  /**
   * Channel name
   */
  channelName: string;

  /**
   * Alert UUID
   */
  idAlert: string;

  /**
   * Alert message
   */
  message: string;

  /**
   * Node code (computed)
   */
  nodeCode: string;

  /**
   * Node name (alias for HTML)
   */
  nodeName: string;

  /**
   * Owner name
   */
  ownerName: string;

  /**
   * Project name
   */
  projectName: string;

  /**
   * Rule name (computed)
   */
  ruleName: string;

  /**
   * Sensor code
   */
  sensorCode: string;

  /**
   * Alert severity
   */
  severity: 'critical' | 'warning' | 'info';

  /**
   * Alert status
   */
  status: 'active' | 'acknowledged' | 'resolved';

  /**
   * Threshold value
   */
  threshold: number;

  /**
   * Timestamp (alias for HTML)
   */
  timestamp: string;

  /**
   * Alert triggered timestamp
   */
  triggeredAt: string;

  /**
   * Triggered timestamp formatted
   */
  triggeredAtFormatted: string;

  /**
   * Unit of measurement
   */
  unit: string;

  /**
   * Current value
   */
  value: number;
}
