/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChartSeriesDto } from '../models/chart-series-dto';
export interface ChartDataDto {

  /**
   * X-axis categories (timestamps)
   */
  categories: Array<string>;

  /**
   * Chart series data
   */
  series: Array<ChartSeriesDto>;
}
