/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChartSeriesDto {

  /**
   * Data points
   */
  data: Array<string>;

  /**
   * Series name
   */
  name: string;
}
