/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClearAlertEventDto {

  /**
   * User ID who cleared
   */
  clearedBy: string;

  /**
   * Clear note
   */
  note?: string;
}
