/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ColorMappingDto } from '../models/color-mapping-dto';
export interface ColorByFieldDto {
  defaultColor: string;
  enabled: boolean;
  field: string;
  mappings: Array<ColorMappingDto>;
}
