/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateSensorTypeDto {

  /**
   * Sensor category (temperature, pressure, flow, etc)
   */
  category: string;

  /**
   * Conversion formula using JavaScript expression with "x" as raw value variable
   */
  conversionFormula?: string;

  /**
   * Default unit of measurement
   */
  defaultUnit?: string;

  /**
   * Default precision (decimal places)
   */
  precision?: number;
}
