/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateNodeModelCommandDto {

  /**
   * Communication channel
   */
  channel: 'sms' | 'mqtt' | 'http' | 'call' | 'telegram';

  /**
   * Command code (e.g., RELAY_ON, STATUS, RESET)
   */
  code: string;

  /**
   * Color theme (primary, success, danger, etc)
   */
  color?: string;

  /**
   * Channel-specific configuration (e.g., mqtt topic, http method)
   */
  config?: {
};

  /**
   * Icon class (Font Awesome)
   */
  icon?: string;

  /**
   * Node model ID this command belongs to
   */
  idNodeModel: string;

  /**
   * Whether command is active
   */
  isActive?: boolean;

  /**
   * Human-readable label (e.g., Turn Relay ON)
   */
  label: string;

  /**
   * Display order
   */
  sortOrder?: number;

  /**
   * Command template with placeholders (e.g., CMD {device_id} {cmd})
   */
  template: string;
}
