/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateNodeModelDto {

  /**
   * Build agent for CI/CD
   */
  buildAgent?: string;

  /**
   * Communication band (868MHz, 915MHz, etc)
   */
  communicationBand?: string;

  /**
   * Default firmware version
   */
  defaultFirmware?: string;

  /**
   * Firmware repository URL
   */
  firmwareRepo?: string;

  /**
   * Flash protocol (UART, SWD, OTA, etc)
   */
  flashProtocol?: string;

  /**
   * Hardware class
   */
  hardwareClass?: 'mcu' | 'gateway' | 'tracker' | 'custom';

  /**
   * Hardware revision
   */
  hardwareRevision?: string;

  /**
   * Model code for internal reference
   */
  modelCode?: string;

  /**
   * Model name
   */
  modelName: string;

  /**
   * Power type (battery, solar, AC, etc)
   */
  powerType?: string;

  /**
   * Communication protocol (LoRa, MQTT, HTTP, etc)
   */
  protocol: string;

  /**
   * Supports code generation
   */
  supportsCodegen?: boolean;

  /**
   * Toolchain (Arduino IDE, PlatformIO, etc)
   */
  toolchain?: string;

  /**
   * Vendor/manufacturer name
   */
  vendor: string;
}
