/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCategoryDto {

  /**
   * Allowed geometry types
   */
  allowedGeometryTypes?: Array<string>;

  /**
   * Category code (unique per owner)
   */
  categoryCode: string;

  /**
   * Category name
   */
  categoryName: string;

  /**
   * Default color (hex)
   */
  colorDefault?: string;

  /**
   * Default style configuration
   */
  defaultStyle?: {
};

  /**
   * Description
   */
  description?: string;

  /**
   * Display order
   */
  displayOrder?: number;

  /**
   * Default icon name
   */
  iconDefault?: string;

  /**
   * Owner ID (null for system categories)
   */
  idOwner?: string;

  /**
   * Industry code (water_utility, energy, manufacturing, etc.)
   */
  industryCode?: string;

  /**
   * Is this an operational layer category
   */
  isOperational?: boolean;

  /**
   * Parent category ID
   */
  parentCategoryId?: string;

  /**
   * Template fields for auto-mapping
   */
  templateFields?: Array<string>;
}
