/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCustomDashboardDto {

  /**
   * Dashboard description
   */
  description?: string;

  /**
   * Set as default dashboard
   */
  isDefault?: boolean;

  /**
   * Layout configuration JSON
   */
  layoutConfig?: {
};

  /**
   * Dashboard name
   */
  name: string;

  /**
   * Auto refresh interval in seconds
   */
  refreshInterval?: number;

  /**
   * Default time range
   */
  timeRange?: string;
}
