/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateLayerDto {

  /**
   * Category code
   */
  categoryCode?: string;

  /**
   * Layer configuration
   */
  configJson?: {
};

  /**
   * Display order
   */
  displayOrder?: number;

  /**
   * Geometry type (Point, LineString, Polygon, etc.)
   */
  geometryType?: string;

  /**
   * Owner ID
   */
  idOwner?: string;

  /**
   * Project ID
   */
  idProject?: string;

  /**
   * Visible by default
   */
  isVisibleDefault?: boolean;

  /**
   * Layer code (unique per project)
   */
  layerCode?: string;

  /**
   * Layer description
   */
  layerDescription?: string;

  /**
   * Layer name
   */
  layerName: string;

  /**
   * Layer type
   */
  layerType: 'core' | 'operational' | 'custom';

  /**
   * Source reference (URL, file path, etc.)
   */
  sourceRef?: string;

  /**
   * Source table name (for query-based layers)
   */
  sourceTable?: string;

  /**
   * Source type
   */
  sourceType: 'system' | 'geojson' | 'shp' | 'kml' | 'csv' | 'api';

  /**
   * SRID (default: 4326)
   */
  srid?: number;

  /**
   * Style configuration
   */
  styleJson?: {
};
}
