/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateNodeAssignmentDto {

  /**
   * User ID who assigned
   */
  assignedBy?: string;

  /**
   * Assignment end date
   */
  endAt?: string;

  /**
   * Node ID
   */
  idNode: string;

  /**
   * Node location ID
   */
  idNodeLocation?: string;

  /**
   * Owner ID
   */
  idOwner: string;

  /**
   * Project ID
   */
  idProject: string;

  /**
   * Reason for assignment
   */
  reason?: string;

  /**
   * Assignment start date
   */
  startAt: string;

  /**
   * Ticket reference
   */
  ticketRef?: string;
}
