/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateNotificationDto {

  /**
   * Notification channel ID
   */
  idChannel: string;

  /**
   * User ID to send notification to
   */
  idUser: string;

  /**
   * Notification message
   */
  message: string;

  /**
   * Additional metadata
   */
  metadata?: {
};

  /**
   * Notification title
   */
  title: string;

  /**
   * Notification type
   */
  type: 'info' | 'warning' | 'error' | 'success' | 'alert';
}
