/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateAlertEventDto {

  /**
   * Alert rule ID
   */
  idAlertRule: string;

  /**
   * Note
   */
  note?: string;

  /**
   * Status
   */
  status?: string;

  /**
   * Triggered timestamp
   */
  triggeredAt: string;

  /**
   * Sensor value that triggered the alert
   */
  value?: number;
}
