/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateSensorChannelDto {

  /**
   * Aggregation method (avg, sum, min, max)
   */
  aggregation?: string;

  /**
   * Alert suppression window in seconds
   */
  alertSuppressionWindow?: number;

  /**
   * Sensor ID
   */
  idSensor: string;

  /**
   * Sensor Type ID (category of measurement)
   */
  idSensorType: string;

  /**
   * Maximum threshold for alerts
   */
  maxThreshold?: number;

  /**
   * Metric code (temperature, pressure, flow, etc)
   */
  metricCode: string;

  /**
   * Minimum threshold for alerts
   */
  minThreshold?: number;

  /**
   * Multiplier for raw value conversion
   */
  multiplier?: number;

  /**
   * Value offset for raw value conversion (renamed from offset to avoid SQL keyword conflict)
   */
  offsetValue?: number;

  /**
   * Decimal precision
   */
  precision?: number;

  /**
   * Modbus/protocol register address
   */
  registerAddress?: number;

  /**
   * Unit of measurement
   */
  unit?: string;
}
