/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CustomWidgetResponseDto } from '../models/custom-widget-response-dto';
export interface CustomDashboardResponseDto {

  /**
   * Created date
   */
  createdAt: string;

  /**
   * Created by user ID
   */
  createdBy?: string;

  /**
   * Dashboard description
   */
  description?: string;

  /**
   * Dashboard ID
   */
  idDashboard: string;

  /**
   * Owner ID
   */
  idOwner: string;

  /**
   * Associated project ID
   */
  idProject?: string;

  /**
   * Active status
   */
  isActive: boolean;

  /**
   * Is default dashboard
   */
  isDefault: boolean;

  /**
   * Layout configuration
   */
  layoutConfig: {
};

  /**
   * Dashboard name
   */
  name: string;

  /**
   * Project name (when loaded)
   */
  projectName?: string;

  /**
   * Auto refresh interval in seconds
   */
  refreshInterval: number;

  /**
   * Default time range
   */
  timeRange: string;

  /**
   * Updated date
   */
  updatedAt: string;

  /**
   * Widgets in this dashboard
   */
  widgets?: Array<CustomWidgetResponseDto>;
}
