/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DashboardWidgetResponseDto {
  configJson?: {
};
  createdAt: string;
  dashboard?: {
};
  displayOrder?: number;
  idDashboard: string;
  idSensor?: string;
  idSensorChannel?: string;
  idWidgetInstance: string;
  positionX: number;
  positionY: number;
  refreshRate: number;
  sensor?: {
};
  sensorChannel?: {
};
  sizeHeight: number;
  sizeWidth: number;
  updatedAt: string;
  widgetType: string;
}
