/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DatabaseHealthItem {

  /**
   * Connection string (alias for HTML)
   */
  connectionString: string;

  /**
   * Database type
   */
  dbType: 'mysql' | 'postgresql';

  /**
   * Database enabled status
   */
  enabled: boolean;

  /**
   * Failed attempts
   */
  failedAttempts: number;

  /**
   * Database host
   */
  host: string;

  /**
   * Database UUID
   */
  idDatabase: string;

  /**
   * Database label
   */
  label: string;

  /**
   * Last success (alias for HTML)
   */
  lastSuccess: string;

  /**
   * Last sync timestamp
   */
  lastSync: string;

  /**
   * Last sync formatted
   */
  lastSyncFormatted: string;

  /**
   * Database name (alias for HTML)
   */
  name: string;

  /**
   * Owner name
   */
  ownerName: string;

  /**
   * Health status
   */
  status: 'healthy' | 'degraded' | 'failed';

  /**
   * Success rate percentage (last 24h)
   */
  successRate: number;

  /**
   * Successful attempts
   */
  successfulAttempts: number;

  /**
   * Total attempts
   */
  totalAttempts: number;
}
