/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExecuteQueryDto {

  /**
   * SQL SELECT query to execute
   */
  sql: string;

  /**
   * Time range for query
   */
  timeRange?: '15m' | '30m' | '1h' | '3h' | '6h' | '12h' | '24h' | '7d' | '30d';

  /**
   * Query variables
   */
  variables?: {
};
}
