/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeatureResponseDto {
  createdAt: string;
  externalId?: string;

  /**
   * GeoJSON geometry
   */
  geometry: {
};
  idFeature: string;
  idLayer: string;
  label?: string;

  /**
   * Feature properties
   */
  properties: {
};
  updatedAt: string;
}
