/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FieldMappingDto {

  /**
   * Source field name from uploaded file
   */
  sourceField: string;

  /**
   * Target field name
   */
  targetField: string;

  /**
   * Transform function (trim, uppercase, etc.)
   */
  transform?: string;
}
