/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ForecastPointDto } from '../models/forecast-point-dto';
export interface ForecastResponseDto {
  createdAt: string;
  forecastData: Array<ForecastPointDto>;
  forecastGeneratedAt: string;
  forecastHorizonHours: number;
  idForecastResult: string;
  idSensorChannel: string;
  modelVersion: string;
  node?: {
};
  sensor?: {
};
  sensorChannel?: {
};
  trainingDataFrom?: string;
  trainingDataPoints?: number;
  trainingDataTo?: string;
}
