/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ForwardingStats {

  /**
   * Database batch count
   */
  dbBatchCount: number;

  /**
   * Database success rate
   */
  dbSuccessRate: number;

  /**
   * Total forwarded count
   */
  totalForwarded: number;

  /**
   * Webhook forwarded count
   */
  webhookCount: number;

  /**
   * Webhook success rate
   */
  webhookSuccessRate: number;
}
