/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GenerateFromTemplateDto {

  /**
   * Custom end date (overrides template range)
   */
  customEndDate?: string;

  /**
   * Custom start date (overrides template range)
   */
  customStartDate?: string;
}
