/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GeoJsonResponseDto {

  /**
   * Array of GeoJSON features
   */
  features: Array<string>;

  /**
   * Metadata
   */
  metadata?: {
};
  type: string;
}
