/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GetSensorTypesDto {

  /**
   * Node IDs to get sensor types for
   */
  nodeIds: Array<string>;
}
