/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IotLogStatsDto {

  /**
   * Count of logs grouped by label/category
   */
  byLabel: {
};

  /**
   * Number of processed logs
   */
  processed: number;

  /**
   * Total number of IoT logs
   */
  total: number;

  /**
   * Number of unprocessed logs
   */
  unprocessed: number;
}
