/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NodeResponseDto {
  batteryType?: string;
  code: string;
  connectivityStatus: string;
  createdAt: string;

  /**
   * Current location details
   */
  currentLocation?: {
};
  devEui?: string;
  firmwareVersion?: string;
  idCurrentLocation?: string;
  idNode: string;
  idNodeModel: string;
  idProject: string;
  installDate?: string;
  ipAddress?: string;
  lastSeenAt?: string;

  /**
   * Node model details
   */
  nodeModel?: {
};

  /**
   * Project details
   */
  project?: {
};
  serialNumber?: string;
  telemetryIntervalSec: number;
  updatedAt: string;
}
