/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NodeDetailedResponseDto {
  batteryType?: string;
  code: string;
  connectivityStatus: string;
  createdAt: string;

  /**
   * Current location details
   */
  currentLocation?: {
};
  devEui?: string;
  firmwareVersion?: string;
  idCurrentLocation?: string;
  idNode: string;
  idNodeModel: string;

  /**
   * Node Profile ID for payload parsing
   */
  idNodeProfile?: string;
  idProject: string;
  installDate?: string;
  ipAddress?: string;
  lastSeenAt?: string;

  /**
   * Node model details
   */
  nodeModel?: {
};

  /**
   * Project details
   */
  project?: {
};

  /**
   * Sensors attached to this node
   */
  sensors?: Array<Array<any>>;
  serialNumber?: string;

  /**
   * Node statistics
   */
  stats?: {
};
  telemetryIntervalSec: number;
  updatedAt: string;
}
