/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NodeResponseDto {
  address?: string;
  batteryType?: string;
  city?: string;
  code: string;
  commissionedAt?: string;
  connectivityStatus: string;
  country?: string;
  createdAt: string;
  description?: string;
  devEui?: string;
  elevationM?: number;
  enclosureRating?: string;
  firmwareVersion?: string;
  idNode: string;
  idNodeModel: string;

  /**
   * Node Profile ID for payload parsing
   */
  idNodeProfile?: string;
  idProject: string;
  installDate?: string;
  installationType?: string;
  ipAddress?: string;
  lastMaintenanceAt?: string;
  lastSeenAt?: string;
  latitude?: number;
  longitude?: number;
  name?: string;
  nextMaintenanceAt?: string;

  /**
   * Node model details
   */
  nodeModel?: {
};
  notes?: string;
  picEmail?: string;
  picName?: string;
  picPhone?: string;
  postalCode?: string;
  powerSource?: string;

  /**
   * Project details
   */
  project?: {
};
  province?: string;
  serialNumber?: string;
  status?: string;
  tags?: Array<string>;
  telemetryIntervalSec: number;
  updatedAt: string;
}
