/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NodesOnlineMetric {

  /**
   * Current value
   */
  current: number;

  /**
   * Change from previous period
   */
  delta: string;

  /**
   * Healthy nodes percentage
   */
  healthyPercentage: number;

  /**
   * New deployments count
   */
  newDeployments: number;

  /**
   * Sparkline data points (last 12 intervals)
   */
  sparkline: Array<number>;

  /**
   * Trend direction
   */
  trend: 'up' | 'down' | 'flat';
}
