/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NodeModelResponseDto {
  buildAgent?: string;
  communicationBand?: string;
  createdAt: string;
  defaultFirmware?: string;
  firmwareRepo?: string;
  flashProtocol?: string;
  hardwareClass?: 'mcu' | 'gateway' | 'tracker' | 'custom';
  hardwareRevision?: string;
  idNodeModel: string;
  modelCode?: string;
  modelName: string;
  powerType?: string;
  protocol: string;
  supportsCodegen: boolean;
  toolchain?: string;
  updatedAt: string;
  vendor: string;
}
