/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NodeAssignmentSummaryDto {
  assignedAt: string;
  idNodeAssignment: string;
  nodeName: string;
  projectName: string;
}
