/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NodeModelDetailedResponseDto {
  buildAgent?: string;
  communicationBand?: string;
  createdAt: string;
  defaultFirmware?: string;
  firmwareRepo?: string;
  flashProtocol?: string;
  hardwareClass?: 'mcu' | 'gateway' | 'tracker' | 'custom';
  hardwareRevision?: string;
  idNodeModel: string;
  modelCode?: string;
  modelName: string;

  /**
   * Nodes using this model
   */
  nodes?: Array<Array<any>>;
  powerType?: string;
  protocol: string;

  /**
   * Usage statistics
   */
  stats?: {
};
  supportsCodegen: boolean;
  toolchain?: string;
  updatedAt: string;
  vendor: string;
}
