/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NodeModelCommandResponseDto {
  channel: 'sms' | 'mqtt' | 'http' | 'call' | 'telegram';
  code: string;
  color: string;
  config?: {
};
  createdAt: string;
  icon: string;
  idCommand: string;
  idNodeModel: string;
  isActive: boolean;
  label: string;
  sortOrder: number;
  template: string;
  updatedAt: string;
}
