/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TelemetryRateInfo } from '../models/telemetry-rate-info';
export interface OwnerLeaderboardItem {

  /**
   * Active sensors count
   */
  activeSensorCount: number;

  /**
   * Active alert count
   */
  alertCount: number;

  /**
   * Critical alerts count
   */
  criticalAlerts: number;

  /**
   * Owner health status
   */
  health: 'healthy' | 'attention' | 'risk';

  /**
   * Owner UUID
   */
  idOwner: string;

  /**
   * Owner name
   */
  name: string;

  /**
   * Total nodes count
   */
  nodeCount: number;

  /**
   * SLA level
   */
  slaLevel: 'Bronze' | 'Silver' | 'Gold' | 'Platinum';

  /**
   * Telemetry rate
   */
  telemetryRate: TelemetryRateInfo;
}
