/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OwnerStatisticsDto } from '../models/owner-statistics-dto';
import { ProjectSummaryDto } from '../models/project-summary-dto';
export interface OwnerDashboardResponseDto {

  /**
   * Owner basic info
   */
  owner: {
};

  /**
   * Performance metrics
   */
  performanceMetrics: {
};

  /**
   * Recent alerts
   */
  recentAlerts: Array<string>;

  /**
   * Recent projects
   */
  recentProjects: Array<ProjectSummaryDto>;

  /**
   * Summary statistics
   */
  summary: OwnerStatisticsDto;
}
