/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OwnerResponseDto {

  /**
   * Contact person
   */
  contactPerson?: string;

  /**
   * Created timestamp
   */
  createdAt: string;

  /**
   * Forwarding settings
   */
  forwardingSettings?: {
};

  /**
   * Owner unique identifier
   */
  idOwner: string;

  /**
   * Industry type
   */
  industry: string;

  /**
   * Owner name
   */
  name: string;

  /**
   * SLA level
   */
  slaLevel?: string;

  /**
   * Updated timestamp
   */
  updatedAt: string;
}
