/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginationMetaDto } from '../models/pagination-meta-dto';
export interface PaginatedResponseDto {

  /**
   * Array of items
   */
  data: Array<Array<any>>;

  /**
   * Pagination metadata
   */
  meta: PaginationMetaDto;
}
