/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectDetailedResponseDto {
  areaType?: 'plant' | 'pipeline' | 'farm' | 'industrial' | 'other';
  createdAt: string;
  geofence?: {
};
  idOwner: string;
  idProject: string;

  /**
   * Last time any node synced telemetry
   */
  lastSync?: {
};

  /**
   * List of locations in this project
   */
  locations?: Array<Array<any>>;

  /**
   * Aggregated metrics for dashboard cards
   */
  metrics?: {
};
  name: string;

  /**
   * List of nodes in this project
   */
  nodes?: Array<Array<any>>;

  /**
   * Owner details
   */
  owner?: {
};

  /**
   * Primary location label / address
   */
  primaryLocation?: string;

  /**
   * Project statistics
   */
  stats?: {
};
  status: string;
  updatedAt: string;
}
