/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReleaseInfo } from '../models/release-info';
export interface ReleaseScheduleResponseDto {

  /**
   * Next scheduled release
   */
  nextRelease: ReleaseInfo;

  /**
   * Upcoming releases (next 3)
   */
  upcomingReleases?: Array<ReleaseInfo>;
}
