/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChartDataDto } from '../models/chart-data-dto';
import { ReportColumnDto } from '../models/report-column-dto';
import { ReportMetadataDto } from '../models/report-metadata-dto';
import { ReportRowDto } from '../models/report-row-dto';
import { SensorSummaryDto } from '../models/sensor-summary-dto';
export interface ReportPreviewResponseDto {

  /**
   * Chart data for visualization
   */
  chartData: ChartDataDto;

  /**
   * Column definitions
   */
  columns: Array<ReportColumnDto>;

  /**
   * Report metadata
   */
  metadata: ReportMetadataDto;

  /**
   * Data rows (limited for preview)
   */
  rows: Array<ReportRowDto>;

  /**
   * Summary statistics per sensor
   */
  summary: Array<SensorSummaryDto>;
}
