/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReportRowDto {

  /**
   * Timestamp
   */
  timestamp: string;

  /**
   * Sensor values keyed by sensor channel ID
   */
  values: {
};
}
