/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReportColumnDto {

  /**
   * Column key
   */
  key: string;

  /**
   * Column label
   */
  label: string;

  /**
   * Unit of measurement
   */
  unit?: string;
}
