/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScadaDiagramMetaUpdateDto {
  canvasConfig?: {
};
  description?: {
};
  diagramCode?: {
};
  name: string;
  projectId?: {
};
  runtimeConfig?: {
};
  status?: string;
}
