/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScadaDiagramMetaDto {
  canvasConfig: {
};
  createdAt: string;
  description?: {
};
  diagramCode?: {
};
  id: string;
  name: string;
  ownerId: string;
  projectId?: {
};
  runtimeConfig: {
};
  status: string;
  updatedAt: string;
}
