/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScadaDiagramListItemResponseDto {
  description?: {
};
  edgeCount?: number;
  id: string;
  name: string;
  nodeCount?: number;
  ownerId: string;
  projectId?: {
};
  status: string;
  updatedAt: string;
}
