/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScadaRuntimeBindingResponseDto {
  bindingId: string;
  bindingKey: string;
  category?: {
};
  connectivityState: string;
  displayLabel?: {
};
  freshnessState: string;
  nodeId: string;
  precision?: {
};
  qualityFlag?: {
};
  rawValue?: {
};
  sensorChannelId: string;
  sensorTypeId?: {
};
  status: string;
  timestamp?: {
};
  unit?: {
};
  unitOverride?: {
};
  value?: {
};
}
