/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScadaRuntimeBindingResponseDto } from '../models/scada-runtime-binding-response-dto';
export interface ScadaRuntimeResponseDto {
  bindings: Array<ScadaRuntimeBindingResponseDto>;
  diagramId: string;
  polledAt: string;
  summary: {
'totalBindings'?: number;
'offlineBindings'?: number;
'staleBindings'?: number;
};
}
