/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScadaBindingPayloadDto {
  bindingKey: string;
  displayLabel?: {
};
  id?: string;
  isPrimary?: boolean;
  priorityOrder?: number;
  sensorChannelId: string;
  transform?: {
};
  unitOverride?: {
};
}
