/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SensorLogTelemetryTrendDto {

  /**
   * Telemetry data points
   */
  dataPoints: Array<{
}>;

  /**
   * Channel ID
   */
  idSensorChannel: string;

  /**
   * Latest timestamp
   */
  latestTimestamp: string;

  /**
   * Latest value
   */
  latestValue: number;

  /**
   * Metric code
   */
  metricCode: string;

  /**
   * Sensor type category
   */
  sensorTypeCategory: string;

  /**
   * Statistics for the time period
   */
  statistics: {
};

  /**
   * Unit of measurement
   */
  unit: string;
}
