/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SensorTypeResponseDto {
  category: string;

  /**
   * Conversion formula using "x" as variable
   */
  conversionFormula?: string;
  createdAt: string;
  defaultUnit?: string;
  idSensorType: string;
  precision?: number;
  updatedAt: string;
}
