/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SensorResponseDto {
  calibrationDueAt?: string;
  calibrationFactor?: number;
  createdAt: string;
  idNode: string;
  idSensor: string;
  idSensorCatalog?: string;
  installDate?: string;
  label: string;

  /**
   * Physical location description
   */
  location?: string;

  /**
   * Node details
   */
  node?: {
};
  protocolChannel?: string;
  samplingRate?: number;

  /**
   * Sensor catalog details
   */
  sensorCatalog?: {
};

  /**
   * Unique sensor code identifier
   */
  sensorCode?: string;

  /**
   * Sensor health status
   */
  status?: 'active' | 'maintenance' | 'inactive';
  updatedAt: string;
}
