/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SensorChannelDetailedResponseDto {
  aggregation?: string;
  alertSuppressionWindow?: number;
  createdAt: string;
  idSensor: string;
  idSensorChannel: string;
  idSensorType: string;

  /**
   * Latest value from sensor logs
   */
  latestValue?: {
};
  maxThreshold?: number;
  metricCode: string;
  minThreshold?: number;
  multiplier?: number;

  /**
   * Value offset for calibration (renamed from offset)
   */
  offsetValue?: number;
  precision?: number;
  registerAddress?: number;

  /**
   * Sensor details
   */
  sensor?: {
};

  /**
   * Sensor type details
   */
  sensorType?: {
};

  /**
   * Channel statistics
   */
  stats?: {
};
  unit?: string;
  updatedAt: string;
}
