/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SensorDetailedResponseDto {
  calibrationDueAt?: string;
  calibrationFactor?: number;

  /**
   * Calibration status
   */
  calibrationStatus?: {
};

  /**
   * Sensor channels with latest values from ClickHouse
   */
  channels?: Array<{
'idSensorChannel'?: string;
'metricCode'?: string;
'unit'?: string;
'lastValue'?: number;
'lastValueAt'?: string;
}>;
  createdAt: string;
  idNode: string;
  idSensor: string;
  idSensorCatalog?: string;
  installDate?: string;
  label: string;

  /**
   * Last sensor value (engineered) - summary from first channel
   */
  lastValue?: number;

  /**
   * Timestamp of last sensor value
   */
  lastValueAt?: string;

  /**
   * Physical location description
   */
  location?: string;

  /**
   * Node details
   */
  node?: {
};
  protocolChannel?: string;
  samplingRate?: number;

  /**
   * Sensor catalog details
   */
  sensorCatalog?: {
};

  /**
   * Sensor channels
   */
  sensorChannels?: Array<Array<any>>;

  /**
   * Unique sensor code identifier
   */
  sensorCode?: string;

  /**
   * Sensor health status
   */
  status?: 'active' | 'maintenance' | 'inactive';
  updatedAt: string;
}
