/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SensorCatalogResponseDto {
  calibrationIntervalDays?: number;
  createdAt: string;
  datasheetUrl?: string;
  defaultChannelsJson?: {
};
  defaultThresholdsJson?: {
};
  firmware?: string;
  iconAsset?: string;
  iconColor?: string;
  idSensorCatalog: string;
  modelName: string;
  updatedAt: string;
  vendor: string;
}
