/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SensorLogEnrichedResponseDto {

  /**
   * Channel label/metric code
   */
  channelLabel?: string;

  /**
   * Record creation timestamp
   */
  createdAt: string;

  /**
   * Node ID (denormalized)
   */
  idNode: string;

  /**
   * Owner ID (denormalized)
   */
  idOwner?: string;

  /**
   * Project ID (denormalized)
   */
  idProject: string;

  /**
   * Sensor ID (denormalized)
   */
  idSensor: string;

  /**
   * Sensor channel ID
   */
  idSensorChannel: string;

  /**
   * Sensor log unique ID
   */
  idSensorLog: string;

  /**
   * Ingestion latency in milliseconds
   */
  ingestionLatencyMs?: number;

  /**
   * Ingestion source (api, mqtt, modbus)
   */
  ingestionSource?: string;

  /**
   * Maximum threshold at time of reading
   */
  maxThreshold?: number;

  /**
   * Minimum threshold at time of reading
   */
  minThreshold?: number;

  /**
   * Node name/code
   */
  nodeName?: string;

  /**
   * Node serial number
   */
  nodeSerialNumber?: string;

  /**
   * Owner name
   */
  ownerName?: string;

  /**
   * Payload sequence number
   */
  payloadSeq?: number;

  /**
   * Project name
   */
  projectName?: string;

  /**
   * Quality flag (good, bad, uncertain)
   */
  qualityFlag?: string;

  /**
   * Sensor code
   */
  sensorCode?: string;

  /**
   * Sensor label/name
   */
  sensorLabel?: string;

  /**
   * Sensor type name
   */
  sensorType?: string;

  /**
   * HTTP status code or protocol response
   */
  statusCode?: number;

  /**
   * Timestamp of measurement
   */
  ts: string;

  /**
   * Unit of measurement
   */
  unit?: string;

  /**
   * Engineered/calibrated value
   */
  valueEngineered?: number;

  /**
   * Raw value from sensor
   */
  valueRaw?: number;
}
