/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SensorLogStatisticsDto {

  /**
   * Logs by quality flag
   */
  byQuality: Array<string>;

  /**
   * Logs by ingestion source
   */
  bySource: Array<string>;

  /**
   * Recent activity (last 24 hours)
   */
  recentActivity: {
};

  /**
   * Top active channels
   */
  topChannels: Array<string>;

  /**
   * Total logs in database
   */
  totalLogs: number;
}
