/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TelemetryChartSeries {

  /**
   * Data points per hour
   */
  data: Array<number>;

  /**
   * Series name
   */
  name: string;
}
