/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TelemetryChartSeries } from '../models/telemetry-chart-series';
export interface TelemetryChart {

  /**
   * Time labels (hourly)
   */
  labels: Array<string>;

  /**
   * Data series
   */
  series: Array<TelemetryChartSeries>;
}
