/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TelemetryChart } from '../models/telemetry-chart';
import { TelemetryStats } from '../models/telemetry-stats';
export interface TelemetryStreamsResponseDto {

  /**
   * Chart data with hourly series
   */
  chart: TelemetryChart;

  /**
   * Ingestion and forwarding statistics
   */
  stats: TelemetryStats;
}
