/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TemplateConfigDto {

  /**
   * Aggregation mode
   */
  aggregation: 'raw' | '1m' | '10m' | '1h' | '1d';

  /**
   * Fill gaps with empty rows
   */
  fillGaps?: boolean;

  /**
   * Metric codes to filter sensor channels
   */
  metricCodes?: Array<string>;

  /**
   * Node IDs
   */
  nodeIds?: Array<string>;

  /**
   * Project ID
   */
  projectId?: string;

  /**
   * Range type
   */
  rangeType: '1d' | '1w' | '1M' | 'custom';

  /**
   * Sensor Channel IDs (optional if metricCodes provided)
   */
  sensorChannelIds?: Array<string>;

  /**
   * Skip zero values in aggregation
   */
  skipZero?: boolean;

  /**
   * Use threshold filter to exclude outliers
   */
  useThresholdFilter?: boolean;
}
