/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TemplateConfigDto {

  /**
   * Aggregation mode
   */
  aggregation: 'raw' | '1m' | '10m' | '1h' | '1d';

  /**
   * Node IDs
   */
  nodeIds?: Array<string>;

  /**
   * Project ID
   */
  projectId?: string;

  /**
   * Range type
   */
  rangeType: '1d' | '1w' | '1M' | 'custom';

  /**
   * Sensor Channel IDs
   */
  sensorChannelIds: Array<string>;
}
