/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateFeatureDto {

  /**
   * External ID
   */
  externalId?: string;

  /**
   * GeoJSON geometry object
   */
  geometry?: {
};

  /**
   * Feature label
   */
  label?: string;

  /**
   * Feature properties
   */
  properties?: {
};
}
