/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateWebhookDto {

  /**
   * Is webhook enabled
   */
  enabled?: boolean;

  /**
   * Webhook endpoint URL
   */
  endpointUrl?: string;

  /**
   * Headers as JSON object
   */
  headersJson?: {
};

  /**
   * HTTP method
   */
  httpMethod?: 'POST' | 'PUT';

  /**
   * Webhook label
   */
  label?: string;

  /**
   * Max retry count
   */
  maxRetry?: number;

  /**
   * Payload template as JSON
   */
  payloadTemplate?: {
};

  /**
   * Retry backoff in milliseconds
   */
  retryBackoffMs?: number;

  /**
   * Secret token for authentication
   */
  secretToken?: string;
}
