/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProfileDto {

  /**
   * User email
   */
  email?: string;

  /**
   * User name
   */
  name?: string;
}
