/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUnpairedDeviceDto {

  /**
   * Node model ID
   */
  idNodeModel?: string;

  /**
   * Last received raw payload from device
   */
  lastPayload?: {
};

  /**
   * Last MQTT topic where data was received
   */
  lastTopic?: string;

  /**
   * Paired node ID (after pairing)
   */
  pairedNodeId?: string;

  /**
   * Device status
   */
  status?: 'pending' | 'paired' | 'ignored';

  /**
   * Suggested owner ID for pairing
   */
  suggestedOwner?: string;

  /**
   * Suggested project ID for pairing
   */
  suggestedProject?: string;
}
