/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateAlertRuleDto {

  /**
   * Whether rule is enabled
   */
  enabled?: boolean;

  /**
   * Sensor channel ID
   */
  idSensorChannel?: string;

  /**
   * Rule parameters as JSON
   */
  paramsJson?: {
};

  /**
   * Rule type
   */
  ruleType?: string;

  /**
   * Severity level
   */
  severity?: string;
}
