/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ColorByFieldDto } from '../models/color-by-field-dto';
import { StrokeWidthByFieldDto } from '../models/stroke-width-by-field-dto';
export interface UpdateStyleDto {
  colorByField?: ColorByFieldDto;
  fillColor?: string;
  fillOpacity?: number;
  labelColor?: string;
  labelFields?: Array<string>;

  /**
   * Minimum zoom level to show labels (0-20)
   */
  labelMinZoom?: number;
  labelSize?: number;

  /**
   * Maximum zoom level to show layer (0-20)
   */
  maxZoom?: number;

  /**
   * Minimum zoom level to show layer (0-20)
   */
  minZoom?: number;
  pointRadius?: number;
  pointShape?: string;
  strokeColor?: string;
  strokeOpacity?: number;
  strokeWidth?: number;
  strokeWidthByField?: StrokeWidthByFieldDto;
}
