/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserDto {

  /**
   * User avatar URL
   */
  avatarUrl?: string;

  /**
   * User email address
   */
  email?: string;

  /**
   * Owner ID
   */
  idOwner?: string;

  /**
   * User active status
   */
  isActive?: boolean;

  /**
   * User full name
   */
  name?: string;

  /**
   * User phone number
   */
  phone?: string;

  /**
   * User role
   */
  role?: 'admin' | 'tenant';
}
