/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateAlertEventDto {

  /**
   * Note
   */
  note?: string;

  /**
   * Status
   */
  status?: string;
}
