/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UploadStatusResponseDto {
  createdAt: string;
  errorMessage?: string;
  fieldMapping?: Array<string>;
  fileType: string;
  idLayer?: string;
  idUpload: string;
  originalFilename: string;
  parsedResult?: {
};
  processedAt?: string;
  status: string;
}
