/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDashboardResponseDto {
  createdAt: string;
  description?: string;
  gridCols: number;
  idDashboard: string;
  idProject?: string;
  idUser: string;
  isDefault: boolean;
  isPublic: boolean;
  layoutType: string;
  name: string;
  project?: {
};
  updatedAt: string;
}
