/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDashboardDetailedResponseDto {
  createdAt: string;
  description?: string;
  gridCols: number;
  idDashboard: string;
  idProject?: string;
  idUser: string;
  isDefault: boolean;
  isPublic: boolean;
  layoutType: string;
  name: string;
  project?: {
};

  /**
   * Statistics
   */
  stats: {
};
  updatedAt: string;

  /**
   * Dashboard widgets
   */
  widgets: Array<any>;
}
