/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ValidateQueryResponseDto {

  /**
   * Blocked keywords found
   */
  blockedKeywords?: Array<string>;

  /**
   * Error message if invalid
   */
  error?: string;

  /**
   * Whether the query is valid
   */
  isValid: boolean;
}
