/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WidgetPositionDto {

  /**
   * Grid columns (width)
   */
  cols?: number;

  /**
   * Widget ID
   */
  idWidget: string;

  /**
   * Grid position X
   */
  positionX: number;

  /**
   * Grid position Y
   */
  positionY: number;

  /**
   * Grid rows (height)
   */
  rows?: number;
}
