/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NodesWithoutCoordsDto } from '../../models/nodes-without-coords-dto';

export interface CoreGeoJsonControllerGetNodesWithoutCoordinates$Params {
  projectId: string;
}

export function coreGeoJsonControllerGetNodesWithoutCoordinates(http: HttpClient, rootUrl: string, params: CoreGeoJsonControllerGetNodesWithoutCoordinates$Params, context?: HttpContext): Observable<StrictHttpResponse<NodesWithoutCoordsDto>> {
  const rb = new RequestBuilder(rootUrl, coreGeoJsonControllerGetNodesWithoutCoordinates.PATH, 'get');
  if (params) {
    rb.path('projectId', params.projectId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NodesWithoutCoordsDto>;
    })
  );
}

coreGeoJsonControllerGetNodesWithoutCoordinates.PATH = '/api/webgis/core/{projectId}/nodes/missing-coordinates';
