/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CoreGeoJsonResponseDto } from '../../models/core-geo-json-response-dto';

export interface CoreGeoJsonControllerGetSensorChannelsGeoJson$Params {
  projectId: string;

/**
 * Filter by sensor type ID
 */
  sensorTypeId?: string;
}

export function coreGeoJsonControllerGetSensorChannelsGeoJson(http: HttpClient, rootUrl: string, params: CoreGeoJsonControllerGetSensorChannelsGeoJson$Params, context?: HttpContext): Observable<StrictHttpResponse<CoreGeoJsonResponseDto>> {
  const rb = new RequestBuilder(rootUrl, coreGeoJsonControllerGetSensorChannelsGeoJson.PATH, 'get');
  if (params) {
    rb.path('projectId', params.projectId, {});
    rb.query('sensorTypeId', params.sensorTypeId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CoreGeoJsonResponseDto>;
    })
  );
}

coreGeoJsonControllerGetSensorChannelsGeoJson.PATH = '/api/webgis/core/{projectId}/sensor-channels';
