/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface NodeProfilesControllerFindAll$Params {
  page?: number;
  limit?: number;
  idNodeModel?: string;
  idProject?: string;
  enabled?: boolean;
  search?: string;
}

export function nodeProfilesControllerFindAll(http: HttpClient, rootUrl: string, params?: NodeProfilesControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, nodeProfilesControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('idNodeModel', params.idNodeModel, {});
    rb.query('idProject', params.idProject, {});
    rb.query('enabled', params.enabled, {});
    rb.query('search', params.search, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

nodeProfilesControllerFindAll.PATH = '/api/node-profiles';
