/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NodeProfileResponseDto } from '../../models/node-profile-response-dto';
import { UpdateNodeProfileDto } from '../../models/update-node-profile-dto';

export interface NodeProfilesControllerUpdate$Params {
  id: string;
      body: UpdateNodeProfileDto
}

export function nodeProfilesControllerUpdate(http: HttpClient, rootUrl: string, params: NodeProfilesControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeProfileResponseDto>> {
  const rb = new RequestBuilder(rootUrl, nodeProfilesControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NodeProfileResponseDto>;
    })
  );
}

nodeProfilesControllerUpdate.PATH = '/api/node-profiles/{id}';
