/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Activity type
 */
export type ActivityLogItemType = typeof ActivityLogItemType[keyof typeof ActivityLogItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActivityLogItemType = {
  webhook: 'webhook',
  alert: 'alert',
  sync: 'sync',
  node_status: 'node_status',
  owner_update: 'owner_update',
  sensor_added: 'sensor_added',
} as const;
