/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { AlertEventResponseDtoAlertRule } from './alertEventResponseDtoAlertRule';

export interface AlertEventResponseDto {
  idAlertEvent: string;
  idAlertRule: string;
  triggeredAt: string;
  value?: number;
  status: string;
  acknowledgedBy?: string;
  acknowledgedAt?: string;
  clearedBy?: string;
  clearedAt?: string;
  note?: string;
  createdAt: string;
  updatedAt: string;
  alertRule?: AlertEventResponseDtoAlertRule;
}
