/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { AlertItemSeverity } from './alertItemSeverity';
import type { AlertItemStatus } from './alertItemStatus';

export interface AlertItem {
  /** Alert UUID */
  idAlert: string;
  /** Sensor code */
  sensorCode: string;
  /** Channel name */
  channelName: string;
  /** Node code (computed) */
  nodeCode: string;
  /** Node name (alias for HTML) */
  nodeName: string;
  /** Rule name (computed) */
  ruleName: string;
  /** Alert severity */
  severity: AlertItemSeverity;
  /** Alert message */
  message: string;
  /** Current value */
  value: number;
  /** Threshold value */
  threshold: number;
  /** Unit of measurement */
  unit: string;
  /** Alert triggered timestamp */
  triggeredAt: string;
  /** Timestamp (alias for HTML) */
  timestamp: string;
  /** Triggered timestamp formatted */
  triggeredAtFormatted: string;
  /** Alert status */
  status: AlertItemStatus;
  /** Project name */
  projectName: string;
  /** Owner name */
  ownerName: string;
}
