/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { CommandResponseDtoPayload } from './commandResponseDtoPayload';

export interface CommandResponseDto {
  /** Success status */
  success: boolean;
  /** Response message */
  message: string;
  /** MQTT topic used */
  topic: string;
  /** Command payload sent */
  payload: CommandResponseDtoPayload;
  /** Timestamp when command was sent */
  timestamp: string;
}
