/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSensorCatalogDtoDefaultChannelsJson } from './createSensorCatalogDtoDefaultChannelsJson';
import type { CreateSensorCatalogDtoDefaultThresholdsJson } from './createSensorCatalogDtoDefaultThresholdsJson';

export interface CreateSensorCatalogDto {
  /** Vendor/manufacturer name */
  vendor: string;
  /** Sensor model name */
  modelName: string;
  /** Icon asset path or URL */
  iconAsset?: string;
  /** Icon color hex code */
  iconColor?: string;
  /** Datasheet URL */
  datasheetUrl?: string;
  /** Firmware version or identifier */
  firmware?: string;
  /** Calibration interval in days */
  calibrationIntervalDays?: number;
  /** Default channels configuration (JSON) */
  defaultChannelsJson?: CreateSensorCatalogDtoDefaultChannelsJson;
  /** Default thresholds configuration (JSON) */
  defaultThresholdsJson?: CreateSensorCatalogDtoDefaultThresholdsJson;
}
