/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSensorLogDtoQualityFlag } from './createSensorLogDtoQualityFlag';
import type { CreateSensorLogDtoIngestionSource } from './createSensorLogDtoIngestionSource';

export interface CreateSensorLogDto {
  /** Sensor channel ID */
  idSensorChannel: string;
  /** Sensor ID */
  idSensor: string;
  /** Node ID */
  idNode: string;
  /** Project ID */
  idProject: string;
  /** Owner ID */
  idOwner?: string;
  /** Timestamp of measurement (ISO string) */
  ts?: string;
  /** Raw sensor value */
  valueRaw?: number;
  /** Engineered/calibrated value */
  valueEngineered?: number;
  /** Quality flag */
  qualityFlag?: CreateSensorLogDtoQualityFlag;
  /** Ingestion source */
  ingestionSource?: CreateSensorLogDtoIngestionSource;
  /** Status code */
  statusCode?: number;
  /** Ingestion latency in ms */
  ingestionLatencyMs?: number;
  /** Payload sequence number */
  payloadSeq?: number;
  /** Minimum threshold */
  minThreshold?: number;
  /** Maximum threshold */
  maxThreshold?: number;
}
