/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateNodeProfileDtoMappingJson } from './createNodeProfileDtoMappingJson';

export interface CreateNodeProfileDto {
  /** Node Model ID */
  idNodeModel: string;
  /** Project ID */
  idProject?: string;
  /** Profile code (unique identifier) */
  code: string;
  /** Profile name */
  name: string;
  /** Profile description */
  description?: string;
  /** Parser type (e.g., json, binary, custom) */
  parserType: string;
  /** Mapping configuration for payload parsing */
  mappingJson: CreateNodeProfileDtoMappingJson;
  /** Custom transform script (JavaScript) */
  transformScript?: string;
  /** Whether profile is enabled */
  enabled?: boolean;
}
