/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateNodeDto {
  /** Project ID */
  idProject: string;
  /** Node Model ID */
  idNodeModel: string;
  /** Node code/identifier (unique within project) */
  code: string;
  /** Friendly name for the node */
  name?: string;
  /** Description of the node */
  description?: string;
  /** Serial number */
  serialNumber?: string;
  /** Device EUI for LoRaWAN */
  devEui?: string;
  /** IP address */
  ipAddress?: string;
  /** Installation date (YYYY-MM-DD) */
  installDate?: string;
  /** Firmware version */
  firmwareVersion?: string;
  /** Battery type */
  batteryType?: string;
  /** Telemetry interval in seconds */
  telemetryIntervalSec?: number;
  /** Connectivity status */
  connectivityStatus?: string;
  /** Node Profile ID for payload parsing */
  idNodeProfile?: string;
  /** Full address */
  address?: string;
  /** City */
  city?: string;
  /** Province/State */
  province?: string;
  /** Postal code */
  postalCode?: string;
  /** Country */
  country?: string;
  /** GPS Latitude */
  latitude?: number;
  /** GPS Longitude */
  longitude?: number;
  /** Elevation in meters */
  elevationM?: number;
  /** Status: active, inactive, maintenance, decommissioned */
  status?: string;
  /** Commissioning date */
  commissionedAt?: string;
  /** Last maintenance date */
  lastMaintenanceAt?: string;
  /** Next scheduled maintenance date */
  nextMaintenanceAt?: string;
  /** Installation type: outdoor, indoor, underground, submerged */
  installationType?: string;
  /** Enclosure rating: IP65, IP67, IP68 */
  enclosureRating?: string;
  /** Power source: solar, grid, battery, hybrid */
  powerSource?: string;
  /** PIC name */
  picName?: string;
  /** PIC phone number */
  picPhone?: string;
  /** PIC email */
  picEmail?: string;
  /** Additional notes */
  notes?: string;
  /** Tags for categorization */
  tags?: string[];
  /** Icon URL for WebGIS map display (max 64x64px, 100KB) */
  iconUrl?: string;
}
