/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateWebhookDtoHttpMethod } from './createWebhookDtoHttpMethod';
import type { CreateWebhookDtoHeadersJson } from './createWebhookDtoHeadersJson';
import type { CreateWebhookDtoPayloadTemplate } from './createWebhookDtoPayloadTemplate';

export interface CreateWebhookDto {
  /** Webhook label */
  label: string;
  /** Webhook endpoint URL */
  endpointUrl: string;
  /** HTTP method */
  httpMethod: CreateWebhookDtoHttpMethod;
  /** Headers as JSON object */
  headersJson?: CreateWebhookDtoHeadersJson;
  /** Secret token for authentication */
  secretToken?: string;
  /** Payload template as JSON */
  payloadTemplate?: CreateWebhookDtoPayloadTemplate;
  /** Max retry count */
  maxRetry: number;
  /** Retry backoff in milliseconds */
  retryBackoffMs: number;
  /** Is webhook enabled */
  enabled: boolean;
}
