/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateNodeLocationDtoType } from './createNodeLocationDtoType';

export interface CreateNodeLocationDto {
  /** Project ID */
  idProject: string;
  /** Location type */
  type?: CreateNodeLocationDtoType;
  /** Latitude */
  latitude: number;
  /** Longitude */
  longitude: number;
  /** Elevation in meters */
  elevation?: number;
  /** Physical address */
  address?: string;
  /** Precision in meters */
  precisionM?: number;
  /** Data source (GPS device, manual entry, import file) */
  source?: string;
}
