/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateDatabaseDtoDbType } from './createDatabaseDtoDbType';
import type { CreateDatabaseDtoWriteMode } from './createDatabaseDtoWriteMode';

export interface CreateDatabaseDto {
  /** Database configuration label */
  label: string;
  /** Database type */
  dbType: CreateDatabaseDtoDbType;
  /** Database host */
  host: string;
  /** Database port */
  port: number;
  /** Database name */
  databaseName: string;
  /** Database username */
  username: string;
  /** Database password (will be encrypted) */
  passwordCipher: string;
  /** Target schema (for PostgreSQL) */
  targetSchema?: string;
  /** Target table name */
  targetTable: string;
  /** Write mode */
  writeMode: CreateDatabaseDtoWriteMode;
  /** Batch size for bulk inserts */
  batchSize: number;
  /** Is database forwarding enabled */
  enabled: boolean;
}
