/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateChannelDtoType } from './createChannelDtoType';
import type { CreateChannelDtoConfig } from './createChannelDtoConfig';

export interface CreateChannelDto {
  /** Channel name */
  name: string;
  /** Channel type */
  type: CreateChannelDtoType;
  /** Channel description */
  description?: string;
  /** Channel configuration (e.g., SMTP settings for email) */
  config?: CreateChannelDtoConfig;
  /** Is channel active */
  isActive?: boolean;
}
