/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateUserDtoRole } from './createUserDtoRole';

export interface CreateUserDto {
  /** User email address */
  email: string;
  /**
   * User password (min 8 characters)
   * @minLength 8
   */
  password: string;
  /** User full name */
  name: string;
  /** User role */
  role: CreateUserDtoRole;
  /** Owner ID (required for tenant users) */
  idOwner?: string;
  /** User phone number */
  phone?: string;
  /** User avatar URL */
  avatarUrl?: string;
}
