/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateScadaDiagramDtoProjectId } from './createScadaDiagramDtoProjectId';
import type { CreateScadaDiagramDtoDiagramCode } from './createScadaDiagramDtoDiagramCode';
import type { CreateScadaDiagramDtoCanvasConfig } from './createScadaDiagramDtoCanvasConfig';
import type { CreateScadaDiagramDtoRuntimeConfig } from './createScadaDiagramDtoRuntimeConfig';

export interface CreateScadaDiagramDto {
  name: string;
  description?: string;
  ownerId?: string;
  projectId?: CreateScadaDiagramDtoProjectId;
  diagramCode?: CreateScadaDiagramDtoDiagramCode;
  status?: string;
  canvasConfig?: CreateScadaDiagramDtoCanvasConfig;
  runtimeConfig?: CreateScadaDiagramDtoRuntimeConfig;
}
