/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateWidgetDtoWidgetType } from './createWidgetDtoWidgetType';
import type { CreateWidgetDtoDataSource } from './createWidgetDtoDataSource';
import type { CreateWidgetDtoConfig } from './createWidgetDtoConfig';

export interface CreateWidgetDto {
  /** Widget name */
  name: string;
  /** Widget type */
  widgetType: CreateWidgetDtoWidgetType;
  /** SQL SELECT query */
  sqlQuery: string;
  /** Data source for query execution */
  dataSource?: CreateWidgetDtoDataSource;
  /** Widget configuration JSON */
  config: CreateWidgetDtoConfig;
  /** Grid position X */
  positionX?: number;
  /** Grid position Y */
  positionY?: number;
  /** Grid columns (width) */
  cols?: number;
  /** Grid rows (height) */
  rows?: number;
}
