/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProjectDtoAreaType } from './createProjectDtoAreaType';
import type { CreateProjectDtoGeofence } from './createProjectDtoGeofence';

export interface CreateProjectDto {
  /** Owner ID (tenant) */
  idOwner: string;
  /** Project name */
  name: string;
  /** Area type */
  areaType?: CreateProjectDtoAreaType;
  /** GeoJSON polygon for geofencing */
  geofence?: CreateProjectDtoGeofence;
  /** Project status */
  status?: string;
}
