/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateUnpairedDeviceDtoLastPayload } from './createUnpairedDeviceDtoLastPayload';

export interface CreateUnpairedDeviceDto {
  /** Hardware identifier (IMEI, dev_eui, MAC address, serial number) */
  hardwareId: string;
  /** Node model ID (auto-detected or manually assigned) */
  idNodeModel?: string;
  /** Last received raw payload from device */
  lastPayload?: CreateUnpairedDeviceDtoLastPayload;
  /** Last MQTT topic where data was received */
  lastTopic?: string;
  /** Suggested project ID for pairing */
  suggestedProject?: string;
  /** Suggested owner ID for pairing */
  suggestedOwner?: string;
}
