/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { CustomDashboardResponseDtoLayoutConfig } from './customDashboardResponseDtoLayoutConfig';
import type { CustomWidgetResponseDto } from './customWidgetResponseDto';

export interface CustomDashboardResponseDto {
  /** Dashboard ID */
  idDashboard: string;
  /** Owner ID */
  idOwner: string;
  /** Associated project ID */
  idProject?: string;
  /** Project name (when loaded) */
  projectName?: string;
  /** Dashboard name */
  name: string;
  /** Dashboard description */
  description?: string;
  /** Layout configuration */
  layoutConfig: CustomDashboardResponseDtoLayoutConfig;
  /** Default time range */
  timeRange: string;
  /** Auto refresh interval in seconds */
  refreshInterval: number;
  /** Is default dashboard */
  isDefault: boolean;
  /** Active status */
  isActive: boolean;
  /** Created by user ID */
  createdBy?: string;
  /** Created date */
  createdAt: string;
  /** Updated date */
  updatedAt: string;
  /** Widgets in this dashboard */
  widgets?: CustomWidgetResponseDto[];
}
