/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { CustomWidgetResponseDtoWidgetType } from './customWidgetResponseDtoWidgetType';
import type { CustomWidgetResponseDtoConfig } from './customWidgetResponseDtoConfig';

export interface CustomWidgetResponseDto {
  /** Widget ID */
  idWidget: string;
  /** Dashboard ID */
  idDashboard: string;
  /** Widget name */
  name: string;
  /** Widget type */
  widgetType: CustomWidgetResponseDtoWidgetType;
  /** SQL query */
  sqlQuery: string;
  /** Widget configuration */
  config: CustomWidgetResponseDtoConfig;
  /** Grid position X */
  positionX: number;
  /** Grid position Y */
  positionY: number;
  /** Grid columns */
  cols: number;
  /** Grid rows */
  rows: number;
  /** Active status */
  isActive: boolean;
  /** Created date */
  createdAt: string;
  /** Updated date */
  updatedAt: string;
}
