/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { DatabaseHealthItemDbType } from './databaseHealthItemDbType';
import type { DatabaseHealthItemStatus } from './databaseHealthItemStatus';

export interface DatabaseHealthItem {
  /** Database UUID */
  idDatabase: string;
  /** Owner name */
  ownerName: string;
  /** Database label */
  label: string;
  /** Database name (alias for HTML) */
  name: string;
  /** Database type */
  dbType: DatabaseHealthItemDbType;
  /** Connection string (alias for HTML) */
  connectionString: string;
  /** Database host */
  host: string;
  /** Health status */
  status: DatabaseHealthItemStatus;
  /** Success rate percentage (last 24h) */
  successRate: number;
  /** Total attempts */
  totalAttempts: number;
  /** Successful attempts */
  successfulAttempts: number;
  /** Failed attempts */
  failedAttempts: number;
  /** Last sync timestamp */
  lastSync: string;
  /** Last success (alias for HTML) */
  lastSuccess: string;
  /** Last sync formatted */
  lastSyncFormatted: string;
  /** Database enabled status */
  enabled: boolean;
}
