/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { FeatureResponseDtoGeometry } from './featureResponseDtoGeometry';
import type { FeatureResponseDtoProperties } from './featureResponseDtoProperties';

export interface FeatureResponseDto {
  idFeature: string;
  idLayer: string;
  /** GeoJSON geometry */
  geometry: FeatureResponseDtoGeometry;
  /** Feature properties */
  properties: FeatureResponseDtoProperties;
  label?: string;
  externalId?: string;
  createdAt: string;
  updatedAt: string;
}
