/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */

export interface ForwardingDatabaseResponseDto {
  /** Database config unique identifier */
  idOwnerForwardingDb: string;
  /** Owner ID */
  idOwner: string;
  /** Database config label */
  label: string;
  /** Database type */
  dbType: string;
  /** Database host */
  host: string;
  /** Database port */
  port: number;
  /** Database name */
  databaseName: string;
  /** Database username */
  username: string;
  /** Password (masked) */
  passwordCipher: string;
  /** Target schema */
  targetSchema?: string;
  /** Target table name */
  targetTable: string;
  /** Write mode */
  writeMode: string;
  /** Batch size */
  batchSize: number;
  /** Is database config enabled */
  enabled: boolean;
  /** Last delivery status */
  lastStatus?: string;
  /** Last delivery timestamp */
  lastDeliveryAt?: string;
  /** Last error message */
  lastError?: string;
  /** Created timestamp */
  createdAt: string;
  /** Updated timestamp */
  updatedAt: string;
}
