/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { IotLogStatsDtoByLabel } from './iotLogStatsDtoByLabel';

export interface IotLogStatsDto {
  /** Total number of IoT logs */
  total: number;
  /** Number of processed logs */
  processed: number;
  /** Number of unprocessed logs */
  unprocessed: number;
  /** Count of logs grouped by label/category */
  byLabel: IotLogStatsDtoByLabel;
}
