/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { NodeHealthItemStatus } from './nodeHealthItemStatus';

export interface NodeHealthItem {
  /** Node UUID */
  idNode: string;
  /** Node code */
  code: string;
  /** Project name */
  projectName: string;
  /** Project UUID */
  projectId: string;
  /** Node status */
  status: NodeHealthItemStatus;
  /** Last seen timestamp */
  lastSeen: string;
  /** Last seen formatted */
  lastSeenFormatted: string;
  /** Battery percentage */
  battery: number;
  /** Signal strength (dBm) */
  signalStrength?: number;
  /** Active alert count */
  alertCount: number;
}
