/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { NodesOnlineMetricTrend } from './nodesOnlineMetricTrend';
import type { TimeSeriesDataPoint } from './timeSeriesDataPoint';

export interface NodesOnlineMetric {
  /** Current value */
  current: number;
  /** Change from previous period */
  delta: string;
  /** Trend direction */
  trend: NodesOnlineMetricTrend;
  /** Sparkline data points (last 12 intervals) */
  sparkline: number[];
  /** Healthy nodes percentage */
  healthyPercentage: number;
  /** New deployments count */
  newDeployments: number;
  /** Time series data for stacked area chart (last 24 data points) */
  timeSeries: TimeSeriesDataPoint[];
  /** Total nodes count */
  totalNodes: number;
  /** Degraded nodes count */
  degradedNodes: number;
  /** Offline nodes count */
  offlineNodes: number;
}
