/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { OwnerResponseDtoForwardingSettings } from './ownerResponseDtoForwardingSettings';

export interface OwnerResponseDto {
  /** Owner unique identifier */
  idOwner: string;
  /** Owner unique 5-digit code */
  ownerCode: string;
  /** Owner name */
  name: string;
  /** Industry type */
  industry: string;
  /** Contact person */
  contactPerson?: string;
  /** Email address */
  email?: string;
  /** Phone number */
  phone?: string;
  /** Physical address */
  address?: string;
  /** SLA level */
  slaLevel?: string;
  /** Forwarding settings */
  forwardingSettings?: OwnerResponseDtoForwardingSettings;
  /** Created timestamp */
  createdAt: string;
  /** Updated timestamp */
  updatedAt: string;
}
