/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { OwnerDetailResponseDtoForwardingSettings } from './ownerDetailResponseDtoForwardingSettings';
import type { ProjectSummaryDto } from './projectSummaryDto';
import type { NodeAssignmentSummaryDto } from './nodeAssignmentSummaryDto';
import type { OwnerStatisticsDto } from './ownerStatisticsDto';
import type { ForwardingWebhookResponseDto } from './forwardingWebhookResponseDto';
import type { ForwardingDatabaseResponseDto } from './forwardingDatabaseResponseDto';
import type { ForwardingLogResponseDto } from './forwardingLogResponseDto';

export interface OwnerDetailResponseDto {
  /** Owner unique identifier */
  idOwner: string;
  /** Owner name */
  name: string;
  /** Industry type */
  industry: string;
  /** Contact person */
  contactPerson?: string;
  /** SLA level */
  slaLevel?: string;
  /** Forwarding settings */
  forwardingSettings?: OwnerDetailResponseDtoForwardingSettings;
  /** List of projects */
  projects: ProjectSummaryDto[];
  /** Node assignments */
  nodeAssignments: NodeAssignmentSummaryDto[];
  /** Owner statistics */
  statistics: OwnerStatisticsDto;
  /** Webhook configurations */
  forwardingWebhooks: ForwardingWebhookResponseDto[];
  /** Database configurations */
  forwardingDatabases: ForwardingDatabaseResponseDto[];
  /** Recent forwarding logs */
  forwardingLogs: ForwardingLogResponseDto[];
  /** Created timestamp */
  createdAt: string;
  /** Updated timestamp */
  updatedAt: string;
}
