/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { IndustryStatDto } from './industryStatDto';
import type { SlaStatDto } from './slaStatDto';
import type { TopOwnerDto } from './topOwnerDto';
import type { RecentActivityDto } from './recentActivityDto';

export interface OwnerStatisticsResponseDto {
  /** Total number of owners */
  totalOwners: number;
  /** Owners grouped by industry */
  ownersByIndustry: IndustryStatDto[];
  /** Owners grouped by SLA level */
  ownersBySlaLevel: SlaStatDto[];
  /** Top owners by projects and nodes */
  topOwnersByProjects: TopOwnerDto[];
  /** Recent owner activities */
  recentActivity: RecentActivityDto[];
}
