/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { OwnerLeaderboardItemSlaLevel } from './ownerLeaderboardItemSlaLevel';
import type { TelemetryRateInfo } from './telemetryRateInfo';
import type { OwnerLeaderboardItemHealth } from './ownerLeaderboardItemHealth';

export interface OwnerLeaderboardItem {
  /** Owner UUID */
  idOwner: string;
  /** Owner name */
  name: string;
  /** SLA level */
  slaLevel: OwnerLeaderboardItemSlaLevel;
  /** Total nodes count */
  nodeCount: number;
  /** Active sensors count */
  activeSensorCount: number;
  /** Telemetry rate */
  telemetryRate: TelemetryRateInfo;
  /** Active alert count */
  alertCount: number;
  /** Critical alerts count */
  criticalAlerts: number;
  /** Owner health status */
  health: OwnerLeaderboardItemHealth;
}
