/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */

export interface ParsedResultResponseDto {
  idUpload: string;
  status: string;
  /** Geometry type detected */
  geometryType: string;
  /** Number of features */
  featureCount: number;
  /** Detected CRS */
  detectedCrs: string;
  /** Detected fields and types */
  fields: string[];
  /** Bounding box [minX, minY, maxX, maxY] */
  bbox: string[];
  /** Parsing warnings */
  warnings?: string[];
  /** Suggested field mappings based on category */
  suggestedMappings?: string[];
}
