/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectDetailedResponseDtoAreaType } from './projectDetailedResponseDtoAreaType';
import type { ProjectDetailedResponseDtoGeofence } from './projectDetailedResponseDtoGeofence';
import type { ProjectDetailedResponseDtoOwner } from './projectDetailedResponseDtoOwner';
import type { ProjectDetailedResponseDtoMetrics } from './projectDetailedResponseDtoMetrics';
import type { ProjectDetailedResponseDtoLastSync } from './projectDetailedResponseDtoLastSync';
import type { ProjectDetailedResponseDtoNodesItemItem } from './projectDetailedResponseDtoNodesItemItem';
import type { ProjectDetailedResponseDtoLocationsItemItem } from './projectDetailedResponseDtoLocationsItemItem';
import type { ProjectDetailedResponseDtoStats } from './projectDetailedResponseDtoStats';

export interface ProjectDetailedResponseDto {
  idProject: string;
  idOwner: string;
  name: string;
  areaType?: ProjectDetailedResponseDtoAreaType;
  geofence?: ProjectDetailedResponseDtoGeofence;
  status: string;
  createdAt: string;
  updatedAt: string;
  /** Owner details */
  owner?: ProjectDetailedResponseDtoOwner;
  /** Aggregated metrics for dashboard cards */
  metrics?: ProjectDetailedResponseDtoMetrics;
  /** Primary location label / address */
  primaryLocation?: string;
  /** Last time any node synced telemetry */
  lastSync?: ProjectDetailedResponseDtoLastSync;
  /** List of nodes in this project */
  nodes?: ProjectDetailedResponseDtoNodesItemItem[][];
  /** List of locations in this project */
  locations?: ProjectDetailedResponseDtoLocationsItemItem[][];
  /** Project statistics */
  stats?: ProjectDetailedResponseDtoStats;
}
