/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectResponseDtoAreaType } from './projectResponseDtoAreaType';
import type { ProjectResponseDtoGeofence } from './projectResponseDtoGeofence';
import type { ProjectResponseDtoOwner } from './projectResponseDtoOwner';
import type { ProjectResponseDtoMetrics } from './projectResponseDtoMetrics';
import type { ProjectResponseDtoLastSync } from './projectResponseDtoLastSync';

export interface ProjectResponseDto {
  idProject: string;
  idOwner: string;
  name: string;
  areaType?: ProjectResponseDtoAreaType;
  geofence?: ProjectResponseDtoGeofence;
  status: string;
  createdAt: string;
  updatedAt: string;
  /** Owner details */
  owner?: ProjectResponseDtoOwner;
  /** Aggregated metrics for dashboard cards */
  metrics?: ProjectResponseDtoMetrics;
  /** Primary location label / address */
  primaryLocation?: string;
  /** Last time any node synced telemetry */
  lastSync?: ProjectResponseDtoLastSync;
}
