/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { ReportMetadataDto } from './reportMetadataDto';
import type { ReportColumnDto } from './reportColumnDto';
import type { ReportRowDto } from './reportRowDto';
import type { ChartDataDto } from './chartDataDto';
import type { SensorSummaryDto } from './sensorSummaryDto';

export interface ReportPreviewResponseDto {
  /** Report metadata */
  metadata: ReportMetadataDto;
  /** Column definitions */
  columns: ReportColumnDto[];
  /** Data rows (limited for preview) */
  rows: ReportRowDto[];
  /** Chart data for visualization */
  chartData: ChartDataDto;
  /** Summary statistics per sensor */
  summary: SensorSummaryDto[];
}
