/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { ScadaDiagramMetaUpdateDtoDescription } from './scadaDiagramMetaUpdateDtoDescription';
import type { ScadaDiagramMetaUpdateDtoProjectId } from './scadaDiagramMetaUpdateDtoProjectId';
import type { ScadaDiagramMetaUpdateDtoDiagramCode } from './scadaDiagramMetaUpdateDtoDiagramCode';
import type { ScadaDiagramMetaUpdateDtoCanvasConfig } from './scadaDiagramMetaUpdateDtoCanvasConfig';
import type { ScadaDiagramMetaUpdateDtoRuntimeConfig } from './scadaDiagramMetaUpdateDtoRuntimeConfig';

export interface ScadaDiagramMetaUpdateDto {
  name: string;
  description?: ScadaDiagramMetaUpdateDtoDescription;
  projectId?: ScadaDiagramMetaUpdateDtoProjectId;
  diagramCode?: ScadaDiagramMetaUpdateDtoDiagramCode;
  status?: string;
  canvasConfig?: ScadaDiagramMetaUpdateDtoCanvasConfig;
  runtimeConfig?: ScadaDiagramMetaUpdateDtoRuntimeConfig;
}
