/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { ScadaDiagramMetaDtoProjectId } from './scadaDiagramMetaDtoProjectId';
import type { ScadaDiagramMetaDtoDescription } from './scadaDiagramMetaDtoDescription';
import type { ScadaDiagramMetaDtoDiagramCode } from './scadaDiagramMetaDtoDiagramCode';
import type { ScadaDiagramMetaDtoCanvasConfig } from './scadaDiagramMetaDtoCanvasConfig';
import type { ScadaDiagramMetaDtoRuntimeConfig } from './scadaDiagramMetaDtoRuntimeConfig';

export interface ScadaDiagramMetaDto {
  id: string;
  ownerId: string;
  projectId?: ScadaDiagramMetaDtoProjectId;
  name: string;
  description?: ScadaDiagramMetaDtoDescription;
  diagramCode?: ScadaDiagramMetaDtoDiagramCode;
  status: string;
  canvasConfig: ScadaDiagramMetaDtoCanvasConfig;
  runtimeConfig: ScadaDiagramMetaDtoRuntimeConfig;
  createdAt: string;
  updatedAt: string;
}
