/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { ScadaPositionDto } from './scadaPositionDto';
import type { ScadaSizeDto } from './scadaSizeDto';
import type { ScadaDiagramNodeDtoRotationDeg } from './scadaDiagramNodeDtoRotationDeg';
import type { ScadaDiagramNodeDtoRelatedNodeId } from './scadaDiagramNodeDtoRelatedNodeId';
import type { ScadaDiagramNodeDtoRelatedSensorId } from './scadaDiagramNodeDtoRelatedSensorId';
import type { ScadaDiagramNodeDtoStyle } from './scadaDiagramNodeDtoStyle';
import type { ScadaDiagramNodeDtoConfig } from './scadaDiagramNodeDtoConfig';
import type { ScadaBindingPayloadDto } from './scadaBindingPayloadDto';

export interface ScadaDiagramNodeDto {
  id?: string;
  type: string;
  label: string;
  position: ScadaPositionDto;
  size: ScadaSizeDto;
  rotationDeg?: ScadaDiagramNodeDtoRotationDeg;
  zIndex?: number;
  relatedNodeId?: ScadaDiagramNodeDtoRelatedNodeId;
  relatedSensorId?: ScadaDiagramNodeDtoRelatedSensorId;
  style?: ScadaDiagramNodeDtoStyle;
  config?: ScadaDiagramNodeDtoConfig;
  bindings?: ScadaBindingPayloadDto[];
}
