/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { ScadaDiagramMetaDto } from './scadaDiagramMetaDto';
import type { ScadaDiagramNodeDto } from './scadaDiagramNodeDto';
import type { ScadaDiagramEdgeDto } from './scadaDiagramEdgeDto';

export interface ScadaDiagramDetailResponseDto {
  diagram: ScadaDiagramMetaDto;
  nodes: ScadaDiagramNodeDto[];
  edges: ScadaDiagramEdgeDto[];
}
