/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */

export interface SensorLogResponseDto {
  /** Sensor log unique ID */
  idSensorLog: string;
  /** Sensor channel ID */
  idSensorChannel: string;
  /** Sensor ID (denormalized) */
  idSensor: string;
  /** Node ID (denormalized) */
  idNode: string;
  /** Project ID (denormalized) */
  idProject: string;
  /** Owner ID (denormalized) */
  idOwner?: string;
  /** Timestamp of measurement */
  ts: string;
  /** Raw value from sensor */
  valueRaw?: number;
  /** Engineered/calibrated value */
  valueEngineered?: number;
  /** Quality flag (good, bad, uncertain) */
  qualityFlag?: string;
  /** Ingestion source (api, mqtt, modbus) */
  ingestionSource?: string;
  /** HTTP status code or protocol response */
  statusCode?: number;
  /** Ingestion latency in milliseconds */
  ingestionLatencyMs?: number;
  /** Payload sequence number */
  payloadSeq?: number;
  /** Minimum threshold at time of reading */
  minThreshold?: number;
  /** Maximum threshold at time of reading */
  maxThreshold?: number;
  /** Record creation timestamp */
  createdAt: string;
}
