/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { SensorLogTelemetryTrendDto } from './sensorLogTelemetryTrendDto';

export interface SensorLogTelemetryTrendsResponseDto {
  /** Node ID */
  idNode: string;
  /** Time range in hours */
  hours: number;
  /** Total channels with data */
  channelCount: number;
  /** Total data points returned */
  totalDataPoints: number;
  /** Telemetry trends per channel */
  channels: SensorLogTelemetryTrendDto[];
  /** Query execution time in ms */
  queryTimeMs: number;
}
