/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { SensorLogEnrichedResponseDto } from './sensorLogEnrichedResponseDto';

export interface SensorLogListResponseDto {
  /** List of sensor logs with enriched data */
  data: SensorLogEnrichedResponseDto[];
  /** Total count of logs */
  total: number;
  /** Current page number */
  page: number;
  /** Logs per page */
  limit: number;
  /** Total pages */
  totalPages: number;
}
