/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { SensorLogTelemetryTrendDtoDataPointsItem } from './sensorLogTelemetryTrendDtoDataPointsItem';
import type { SensorLogTelemetryTrendDtoStatistics } from './sensorLogTelemetryTrendDtoStatistics';

export interface SensorLogTelemetryTrendDto {
  /** Channel ID */
  idSensorChannel: string;
  /** Metric code */
  metricCode: string;
  /** Sensor type category */
  sensorTypeCategory: string;
  /** Unit of measurement */
  unit: string;
  /** Latest value */
  latestValue: number;
  /** Latest timestamp */
  latestTimestamp: string;
  /** Telemetry data points */
  dataPoints: SensorLogTelemetryTrendDtoDataPointsItem[];
  /** Statistics for the time period */
  statistics: SensorLogTelemetryTrendDtoStatistics;
}
