/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { SensorDetailedResponseDtoStatus } from './sensorDetailedResponseDtoStatus';
import type { SensorDetailedResponseDtoNode } from './sensorDetailedResponseDtoNode';
import type { SensorDetailedResponseDtoSensorCatalog } from './sensorDetailedResponseDtoSensorCatalog';
import type { SensorDetailedResponseDtoSensorChannelsItemItem } from './sensorDetailedResponseDtoSensorChannelsItemItem';
import type { SensorDetailedResponseDtoCalibrationStatus } from './sensorDetailedResponseDtoCalibrationStatus';

export interface SensorDetailedResponseDto {
  idSensor: string;
  idNode: string;
  idSensorCatalog?: string;
  /** Unique sensor code identifier */
  sensorCode?: string;
  label: string;
  /** Physical location description */
  location?: string;
  /** Sensor health status */
  status?: SensorDetailedResponseDtoStatus;
  protocolChannel?: string;
  calibrationFactor?: number;
  samplingRate?: number;
  installDate?: string;
  calibrationDueAt?: string;
  createdAt: string;
  updatedAt: string;
  /** Node details */
  node?: SensorDetailedResponseDtoNode;
  /** Sensor catalog details */
  sensorCatalog?: SensorDetailedResponseDtoSensorCatalog;
  /** Sensor channels */
  sensorChannels?: SensorDetailedResponseDtoSensorChannelsItemItem[][];
  /** Calibration status */
  calibrationStatus?: SensorDetailedResponseDtoCalibrationStatus;
}
