/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { SensorChannelDetailedResponseDtoSensor } from './sensorChannelDetailedResponseDtoSensor';
import type { SensorChannelDetailedResponseDtoSensorType } from './sensorChannelDetailedResponseDtoSensorType';
import type { SensorChannelDetailedResponseDtoLatestValue } from './sensorChannelDetailedResponseDtoLatestValue';
import type { SensorChannelDetailedResponseDtoStats } from './sensorChannelDetailedResponseDtoStats';

export interface SensorChannelDetailedResponseDto {
  idSensorChannel: string;
  idSensor: string;
  idSensorType: string;
  metricCode: string;
  unit?: string;
  minThreshold?: number;
  maxThreshold?: number;
  multiplier?: number;
  /** Value offset for calibration (renamed from offset) */
  offsetValue?: number;
  registerAddress?: number;
  precision?: number;
  aggregation?: string;
  alertSuppressionWindow?: number;
  createdAt: string;
  updatedAt: string;
  /** Sensor details */
  sensor?: SensorChannelDetailedResponseDtoSensor;
  /** Sensor type details */
  sensorType?: SensorChannelDetailedResponseDtoSensorType;
  /** Latest value from sensor logs */
  latestValue?: SensorChannelDetailedResponseDtoLatestValue;
  /** Channel statistics */
  stats?: SensorChannelDetailedResponseDtoStats;
}
