/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { TelemetryRateMetricTrend } from './telemetryRateMetricTrend';

export interface TelemetryRateMetric {
  /** Current value */
  current: number;
  /** Change from previous period */
  delta: string;
  /** Trend direction */
  trend: TelemetryRateMetricTrend;
  /** Sparkline data points (last 12 intervals) */
  sparkline: number[];
  /** Active devices sending data */
  activeDevices: number;
  /** Total devices */
  totalDevices: number;
  /** Last message received (seconds ago) */
  lastMessageSecondsAgo: number;
  /** Pending queue size */
  queueSize: number;
}
