/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { IngestionStats } from './ingestionStats';
import type { ForwardingStats } from './forwardingStats';

export interface TelemetryStats {
  /** Ingestion statistics */
  ingestion: IngestionStats;
  /** Forwarding statistics */
  forwarding: ForwardingStats;
  /** Total ingested (convenience) */
  totalIngested: number;
  /** Total forwarded (convenience) */
  totalForwarded: number;
  /** Success rate (convenience) */
  successRate: number;
  /** Average messages per hour */
  avgPerHour: number;
  /** Peak hour message count */
  peakHour: number;
  /** Growth percentage vs previous period */
  growthPercent: number;
}
