/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { TelemetryChart } from './telemetryChart';
import type { TelemetryStats } from './telemetryStats';

export interface TelemetryStreamsResponseDto {
  /** Chart data with hourly series */
  chart: TelemetryChart;
  /** Ingestion and forwarding statistics */
  stats: TelemetryStats;
}
