/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAlertRuleDtoParamsJson } from './updateAlertRuleDtoParamsJson';

export interface UpdateAlertRuleDto {
  /** Sensor channel ID */
  idSensorChannel?: string;
  /** Rule type */
  ruleType?: string;
  /** Severity level */
  severity?: string;
  /** Rule parameters as JSON */
  paramsJson?: UpdateAlertRuleDtoParamsJson;
  /** Whether rule is enabled */
  enabled?: boolean;
}
