/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUnpairedDeviceDtoLastPayload } from './updateUnpairedDeviceDtoLastPayload';
import type { UpdateUnpairedDeviceDtoStatus } from './updateUnpairedDeviceDtoStatus';

export interface UpdateUnpairedDeviceDto {
  /** Node model ID */
  idNodeModel?: string;
  /** Last received raw payload from device */
  lastPayload?: UpdateUnpairedDeviceDtoLastPayload;
  /** Last MQTT topic where data was received */
  lastTopic?: string;
  /** Suggested project ID for pairing */
  suggestedProject?: string;
  /** Suggested owner ID for pairing */
  suggestedOwner?: string;
  /** Paired node ID (after pairing) */
  pairedNodeId?: string;
  /** Device status */
  status?: UpdateUnpairedDeviceDtoStatus;
}
