/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateNodeAssignmentDto {
  /** Node ID */
  idNode?: string;
  /** Project ID */
  idProject?: string;
  /** Owner ID */
  idOwner?: string;
  /** Node location ID */
  idNodeLocation?: string;
  /** Assignment start date */
  startAt?: string;
  /** Assignment end date */
  endAt?: string;
  /** Reason for assignment */
  reason?: string;
  /** User ID who assigned */
  assignedBy?: string;
  /** Ticket reference */
  ticketRef?: string;
}
