/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateLayerDtoLayerType } from './updateLayerDtoLayerType';
import type { UpdateLayerDtoSourceType } from './updateLayerDtoSourceType';
import type { UpdateLayerDtoStyleJson } from './updateLayerDtoStyleJson';
import type { UpdateLayerDtoConfigJson } from './updateLayerDtoConfigJson';

export interface UpdateLayerDto {
  /** Layer name */
  layerName?: string;
  /** Layer code (unique per project) */
  layerCode?: string;
  /** Layer description */
  layerDescription?: string;
  /** Layer type */
  layerType?: UpdateLayerDtoLayerType;
  /** Source type */
  sourceType?: UpdateLayerDtoSourceType;
  /** Category code */
  categoryCode?: string;
  /** Geometry type (Point, LineString, Polygon, etc.) */
  geometryType?: string;
  /** SRID (default: 4326) */
  srid?: number;
  /** Source table name (for query-based layers) */
  sourceTable?: string;
  /** Source reference (URL, file path, etc.) */
  sourceRef?: string;
  /** Style configuration */
  styleJson?: UpdateLayerDtoStyleJson;
  /** Layer configuration */
  configJson?: UpdateLayerDtoConfigJson;
  /** Visible by default */
  isVisibleDefault?: boolean;
  /** Display order */
  displayOrder?: number;
  /** Project ID */
  idProject?: string;
  /** Owner ID */
  idOwner?: string;
}
