/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Data source for query execution
 */
export type UpdateWidgetDtoDataSource = typeof UpdateWidgetDtoDataSource[keyof typeof UpdateWidgetDtoDataSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateWidgetDtoDataSource = {
  postgresql: 'postgresql',
  clickhouse: 'clickhouse',
} as const;
