/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProjectDtoAreaType } from './updateProjectDtoAreaType';
import type { UpdateProjectDtoGeofence } from './updateProjectDtoGeofence';

export interface UpdateProjectDto {
  /** Owner ID (tenant) */
  idOwner?: string;
  /** Project name */
  name?: string;
  /** Area type */
  areaType?: UpdateProjectDtoAreaType;
  /** GeoJSON polygon for geofencing */
  geofence?: UpdateProjectDtoGeofence;
  /** Project status */
  status?: string;
}
