/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCustomDashboardDtoIdProject } from './updateCustomDashboardDtoIdProject';
import type { UpdateCustomDashboardDtoLayoutConfig } from './updateCustomDashboardDtoLayoutConfig';

export interface UpdateCustomDashboardDto {
  /** Dashboard name */
  name?: string;
  /** Associated project ID (optional, null to unlink) */
  idProject?: UpdateCustomDashboardDtoIdProject;
  /** Dashboard description */
  description?: string;
  /** Layout configuration JSON */
  layoutConfig?: UpdateCustomDashboardDtoLayoutConfig;
  /** Default time range */
  timeRange?: string;
  /** Auto refresh interval in seconds */
  refreshInterval?: number;
  /** Set as default dashboard */
  isDefault?: boolean;
  /** Active status */
  isActive?: boolean;
}
