/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCategoryDtoDefaultStyle } from './updateCategoryDtoDefaultStyle';

export interface UpdateCategoryDto {
  /** Category name */
  categoryName?: string;
  /** Description */
  description?: string;
  /** Allowed geometry types */
  allowedGeometryTypes?: string[];
  /** Template fields */
  templateFields?: string[];
  /** Default style */
  defaultStyle?: UpdateCategoryDtoDefaultStyle;
  /** Default icon */
  iconDefault?: string;
  /** Default color */
  colorDefault?: string;
  /** Is active */
  isActive?: boolean;
  /** Display order */
  displayOrder?: number;
}
