/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOwnerDtoSlaLevel } from './updateOwnerDtoSlaLevel';
import type { UpdateOwnerDtoForwardingSettings } from './updateOwnerDtoForwardingSettings';

export interface UpdateOwnerDto {
  /** Owner name */
  name?: string;
  /** Industry type */
  industry?: string;
  /** Contact person name */
  contactPerson?: string;
  /** Email address */
  email?: string;
  /** Phone number */
  phone?: string;
  /** Physical address */
  address?: string;
  /** SLA level */
  slaLevel?: UpdateOwnerDtoSlaLevel;
  /** Forwarding settings (JSONB) */
  forwardingSettings?: UpdateOwnerDtoForwardingSettings;
}
