/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Database type
 */
export type UpdateDatabaseDtoDbType = typeof UpdateDatabaseDtoDbType[keyof typeof UpdateDatabaseDtoDbType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateDatabaseDtoDbType = {
  mysql: 'mysql',
  postgresql: 'postgresql',
} as const;
