/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type { WebhookHealthItemStatus } from './webhookHealthItemStatus';

export interface WebhookHealthItem {
  /** Webhook UUID */
  idWebhook: string;
  /** Owner name */
  ownerName: string;
  /** Webhook label */
  label: string;
  /** Webhook name (alias for HTML) */
  name: string;
  /** Target URL */
  url: string;
  /** Endpoint (alias for HTML) */
  endpoint: string;
  /** Health status */
  status: WebhookHealthItemStatus;
  /** Success rate percentage (last 24h) */
  successRate: number;
  /** Total attempts */
  totalAttempts: number;
  /** Successful attempts */
  successfulAttempts: number;
  /** Failed attempts */
  failedAttempts: number;
  /** Last sync timestamp */
  lastSync: string;
  /** Last success (alias for HTML) */
  lastSuccess: string;
  /** Last sync formatted */
  lastSyncFormatted: string;
  /** Webhook enabled status */
  enabled: boolean;
  /** Average response time (ms) */
  avgResponseTime: number;
}
