/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */

export interface WidgetPositionDto {
  /** Widget ID */
  idWidget: string;
  /** Grid position X */
  positionX: number;
  /** Grid position Y */
  positionY: number;
  /** Grid columns (width) */
  cols?: number;
  /** Grid rows (height) */
  rows?: number;
}
