/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Monitoring System API
 * Complete IoT monitoring system REST API with nested data queries, aggregations, and real-time telemetry. Supports CRUD operations for all entities, complex queries with relations, and custom reports for dashboards.
 * OpenAPI spec version: 1.0.0
 */
import type {
  ChangePasswordDto,
  CreateScadaDiagramDto,
  DuplicateScadaDiagramDto,
  ForgotPasswordDto,
  LoginDto,
  RegisterDto,
  ResetPasswordDto,
  ScadaBindingOptionItemDto,
  ScadaBindingOptionsControllerFindAllParams,
  ScadaDiagramDetailResponseDto,
  ScadaDiagramListItemResponseDto,
  ScadaDiagramsControllerArchive200,
  ScadaDiagramsControllerFindAllParams,
  ScadaRuntimeResponseDto,
  UpdateProfileDto,
  UpdateScadaDiagramDto
} from './models';

import { customFetch } from './client';
/**
 * @summary Register new user
 */
export type authControllerRegisterResponse201 = {
  data: void
  status: 201
}

export type authControllerRegisterResponse400 = {
  data: void
  status: 400
}
    
export type authControllerRegisterResponseSuccess = (authControllerRegisterResponse201) & {
  headers: Headers;
};
export type authControllerRegisterResponseError = (authControllerRegisterResponse400) & {
  headers: Headers;
};

export type authControllerRegisterResponse = (authControllerRegisterResponseSuccess | authControllerRegisterResponseError)

export const getAuthControllerRegisterUrl = () => {


  

  return `/api/auth/register`
}

export const authControllerRegister = async (registerDto: RegisterDto, options?: RequestInit): Promise<authControllerRegisterResponse> => {
  
  return customFetch<authControllerRegisterResponse>(getAuthControllerRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerDto,)
  }
);}



/**
 * @summary Login user
 */
export type authControllerLoginResponse200 = {
  data: void
  status: 200
}

export type authControllerLoginResponse401 = {
  data: void
  status: 401
}
    
export type authControllerLoginResponseSuccess = (authControllerLoginResponse200) & {
  headers: Headers;
};
export type authControllerLoginResponseError = (authControllerLoginResponse401) & {
  headers: Headers;
};

export type authControllerLoginResponse = (authControllerLoginResponseSuccess | authControllerLoginResponseError)

export const getAuthControllerLoginUrl = () => {


  

  return `/api/auth/login`
}

export const authControllerLogin = async (loginDto: LoginDto, options?: RequestInit): Promise<authControllerLoginResponse> => {
  
  return customFetch<authControllerLoginResponse>(getAuthControllerLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginDto,)
  }
);}



/**
 * @summary Get current user profile
 */
export type authControllerGetProfileResponse200 = {
  data: void
  status: 200
}

export type authControllerGetProfileResponse401 = {
  data: void
  status: 401
}
    
export type authControllerGetProfileResponseSuccess = (authControllerGetProfileResponse200) & {
  headers: Headers;
};
export type authControllerGetProfileResponseError = (authControllerGetProfileResponse401) & {
  headers: Headers;
};

export type authControllerGetProfileResponse = (authControllerGetProfileResponseSuccess | authControllerGetProfileResponseError)

export const getAuthControllerGetProfileUrl = () => {


  

  return `/api/auth/me`
}

export const authControllerGetProfile = async ( options?: RequestInit): Promise<authControllerGetProfileResponse> => {
  
  return customFetch<authControllerGetProfileResponse>(getAuthControllerGetProfileUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get current user profile (alias for /me)
 */
export type authControllerGetProfileAliasResponse200 = {
  data: void
  status: 200
}

export type authControllerGetProfileAliasResponse401 = {
  data: void
  status: 401
}
    
export type authControllerGetProfileAliasResponseSuccess = (authControllerGetProfileAliasResponse200) & {
  headers: Headers;
};
export type authControllerGetProfileAliasResponseError = (authControllerGetProfileAliasResponse401) & {
  headers: Headers;
};

export type authControllerGetProfileAliasResponse = (authControllerGetProfileAliasResponseSuccess | authControllerGetProfileAliasResponseError)

export const getAuthControllerGetProfileAliasUrl = () => {


  

  return `/api/auth/profile`
}

export const authControllerGetProfileAlias = async ( options?: RequestInit): Promise<authControllerGetProfileAliasResponse> => {
  
  return customFetch<authControllerGetProfileAliasResponse>(getAuthControllerGetProfileAliasUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update current user profile
 */
export type authControllerUpdateProfileResponse200 = {
  data: void
  status: 200
}

export type authControllerUpdateProfileResponse400 = {
  data: void
  status: 400
}

export type authControllerUpdateProfileResponse401 = {
  data: void
  status: 401
}
    
export type authControllerUpdateProfileResponseSuccess = (authControllerUpdateProfileResponse200) & {
  headers: Headers;
};
export type authControllerUpdateProfileResponseError = (authControllerUpdateProfileResponse400 | authControllerUpdateProfileResponse401) & {
  headers: Headers;
};

export type authControllerUpdateProfileResponse = (authControllerUpdateProfileResponseSuccess | authControllerUpdateProfileResponseError)

export const getAuthControllerUpdateProfileUrl = () => {


  

  return `/api/auth/profile`
}

export const authControllerUpdateProfile = async (updateProfileDto: UpdateProfileDto, options?: RequestInit): Promise<authControllerUpdateProfileResponse> => {
  
  return customFetch<authControllerUpdateProfileResponse>(getAuthControllerUpdateProfileUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProfileDto,)
  }
);}



/**
 * @summary Change current user password
 */
export type authControllerChangePasswordResponse200 = {
  data: void
  status: 200
}

export type authControllerChangePasswordResponse400 = {
  data: void
  status: 400
}

export type authControllerChangePasswordResponse401 = {
  data: void
  status: 401
}
    
export type authControllerChangePasswordResponseSuccess = (authControllerChangePasswordResponse200) & {
  headers: Headers;
};
export type authControllerChangePasswordResponseError = (authControllerChangePasswordResponse400 | authControllerChangePasswordResponse401) & {
  headers: Headers;
};

export type authControllerChangePasswordResponse = (authControllerChangePasswordResponseSuccess | authControllerChangePasswordResponseError)

export const getAuthControllerChangePasswordUrl = () => {


  

  return `/api/auth/change-password`
}

export const authControllerChangePassword = async (changePasswordDto: ChangePasswordDto, options?: RequestInit): Promise<authControllerChangePasswordResponse> => {
  
  return customFetch<authControllerChangePasswordResponse>(getAuthControllerChangePasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changePasswordDto,)
  }
);}



/**
 * @summary Request password reset
 */
export type authControllerForgotPasswordResponse200 = {
  data: void
  status: 200
}
    
export type authControllerForgotPasswordResponseSuccess = (authControllerForgotPasswordResponse200) & {
  headers: Headers;
};
;

export type authControllerForgotPasswordResponse = (authControllerForgotPasswordResponseSuccess)

export const getAuthControllerForgotPasswordUrl = () => {


  

  return `/api/auth/forgot-password`
}

export const authControllerForgotPassword = async (forgotPasswordDto: ForgotPasswordDto, options?: RequestInit): Promise<authControllerForgotPasswordResponse> => {
  
  return customFetch<authControllerForgotPasswordResponse>(getAuthControllerForgotPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      forgotPasswordDto,)
  }
);}



/**
 * @summary Reset password with token
 */
export type authControllerResetPasswordResponse200 = {
  data: void
  status: 200
}

export type authControllerResetPasswordResponse400 = {
  data: void
  status: 400
}
    
export type authControllerResetPasswordResponseSuccess = (authControllerResetPasswordResponse200) & {
  headers: Headers;
};
export type authControllerResetPasswordResponseError = (authControllerResetPasswordResponse400) & {
  headers: Headers;
};

export type authControllerResetPasswordResponse = (authControllerResetPasswordResponseSuccess | authControllerResetPasswordResponseError)

export const getAuthControllerResetPasswordUrl = () => {


  

  return `/api/auth/reset-password`
}

export const authControllerResetPassword = async (resetPasswordDto: ResetPasswordDto, options?: RequestInit): Promise<authControllerResetPasswordResponse> => {
  
  return customFetch<authControllerResetPasswordResponse>(getAuthControllerResetPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resetPasswordDto,)
  }
);}



/**
 * @summary Refresh access token
 */
export type authControllerRefreshResponse200 = {
  data: void
  status: 200
}

export type authControllerRefreshResponse401 = {
  data: void
  status: 401
}
    
export type authControllerRefreshResponseSuccess = (authControllerRefreshResponse200) & {
  headers: Headers;
};
export type authControllerRefreshResponseError = (authControllerRefreshResponse401) & {
  headers: Headers;
};

export type authControllerRefreshResponse = (authControllerRefreshResponseSuccess | authControllerRefreshResponseError)

export const getAuthControllerRefreshUrl = () => {


  

  return `/api/auth/refresh`
}

export const authControllerRefresh = async ( options?: RequestInit): Promise<authControllerRefreshResponse> => {
  
  return customFetch<authControllerRefreshResponse>(getAuthControllerRefreshUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Logout user
 */
export type authControllerLogoutResponse200 = {
  data: void
  status: 200
}
    
export type authControllerLogoutResponseSuccess = (authControllerLogoutResponse200) & {
  headers: Headers;
};
;

export type authControllerLogoutResponse = (authControllerLogoutResponseSuccess)

export const getAuthControllerLogoutUrl = () => {


  

  return `/api/auth/logout`
}

export const authControllerLogout = async ( options?: RequestInit): Promise<authControllerLogoutResponse> => {
  
  return customFetch<authControllerLogoutResponse>(getAuthControllerLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary List SCADA diagrams
 */
export type scadaDiagramsControllerFindAllResponse200 = {
  data: ScadaDiagramListItemResponseDto[]
  status: 200
}
    
export type scadaDiagramsControllerFindAllResponseSuccess = (scadaDiagramsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type scadaDiagramsControllerFindAllResponse = (scadaDiagramsControllerFindAllResponseSuccess)

export const getScadaDiagramsControllerFindAllUrl = (params?: ScadaDiagramsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/scada/diagrams?${stringifiedParams}` : `/api/scada/diagrams`
}

export const scadaDiagramsControllerFindAll = async (params?: ScadaDiagramsControllerFindAllParams, options?: RequestInit): Promise<scadaDiagramsControllerFindAllResponse> => {
  
  return customFetch<scadaDiagramsControllerFindAllResponse>(getScadaDiagramsControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create a SCADA diagram
 */
export type scadaDiagramsControllerCreateResponse201 = {
  data: ScadaDiagramDetailResponseDto
  status: 201
}
    
export type scadaDiagramsControllerCreateResponseSuccess = (scadaDiagramsControllerCreateResponse201) & {
  headers: Headers;
};
;

export type scadaDiagramsControllerCreateResponse = (scadaDiagramsControllerCreateResponseSuccess)

export const getScadaDiagramsControllerCreateUrl = () => {


  

  return `/api/scada/diagrams`
}

export const scadaDiagramsControllerCreate = async (createScadaDiagramDto: CreateScadaDiagramDto, options?: RequestInit): Promise<scadaDiagramsControllerCreateResponse> => {
  
  return customFetch<scadaDiagramsControllerCreateResponse>(getScadaDiagramsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createScadaDiagramDto,)
  }
);}



/**
 * @summary Get SCADA diagram detail
 */
export type scadaDiagramsControllerFindOneResponse200 = {
  data: ScadaDiagramDetailResponseDto
  status: 200
}
    
export type scadaDiagramsControllerFindOneResponseSuccess = (scadaDiagramsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type scadaDiagramsControllerFindOneResponse = (scadaDiagramsControllerFindOneResponseSuccess)

export const getScadaDiagramsControllerFindOneUrl = (diagramId: string,) => {


  

  return `/api/scada/diagrams/${diagramId}`
}

export const scadaDiagramsControllerFindOne = async (diagramId: string, options?: RequestInit): Promise<scadaDiagramsControllerFindOneResponse> => {
  
  return customFetch<scadaDiagramsControllerFindOneResponse>(getScadaDiagramsControllerFindOneUrl(diagramId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update SCADA diagram with full payload save
 */
export type scadaDiagramsControllerUpdateResponse200 = {
  data: ScadaDiagramDetailResponseDto
  status: 200
}
    
export type scadaDiagramsControllerUpdateResponseSuccess = (scadaDiagramsControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type scadaDiagramsControllerUpdateResponse = (scadaDiagramsControllerUpdateResponseSuccess)

export const getScadaDiagramsControllerUpdateUrl = (diagramId: string,) => {


  

  return `/api/scada/diagrams/${diagramId}`
}

export const scadaDiagramsControllerUpdate = async (diagramId: string,
    updateScadaDiagramDto: UpdateScadaDiagramDto, options?: RequestInit): Promise<scadaDiagramsControllerUpdateResponse> => {
  
  return customFetch<scadaDiagramsControllerUpdateResponse>(getScadaDiagramsControllerUpdateUrl(diagramId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateScadaDiagramDto,)
  }
);}



/**
 * @summary Archive a SCADA diagram
 */
export type scadaDiagramsControllerArchiveResponse200 = {
  data: ScadaDiagramsControllerArchive200
  status: 200
}
    
export type scadaDiagramsControllerArchiveResponseSuccess = (scadaDiagramsControllerArchiveResponse200) & {
  headers: Headers;
};
;

export type scadaDiagramsControllerArchiveResponse = (scadaDiagramsControllerArchiveResponseSuccess)

export const getScadaDiagramsControllerArchiveUrl = (diagramId: string,) => {


  

  return `/api/scada/diagrams/${diagramId}`
}

export const scadaDiagramsControllerArchive = async (diagramId: string, options?: RequestInit): Promise<scadaDiagramsControllerArchiveResponse> => {
  
  return customFetch<scadaDiagramsControllerArchiveResponse>(getScadaDiagramsControllerArchiveUrl(diagramId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary Duplicate a SCADA diagram
 */
export type scadaDiagramsControllerDuplicateResponse201 = {
  data: ScadaDiagramDetailResponseDto
  status: 201
}
    
export type scadaDiagramsControllerDuplicateResponseSuccess = (scadaDiagramsControllerDuplicateResponse201) & {
  headers: Headers;
};
;

export type scadaDiagramsControllerDuplicateResponse = (scadaDiagramsControllerDuplicateResponseSuccess)

export const getScadaDiagramsControllerDuplicateUrl = (diagramId: string,) => {


  

  return `/api/scada/diagrams/${diagramId}/duplicate`
}

export const scadaDiagramsControllerDuplicate = async (diagramId: string,
    duplicateScadaDiagramDto: DuplicateScadaDiagramDto, options?: RequestInit): Promise<scadaDiagramsControllerDuplicateResponse> => {
  
  return customFetch<scadaDiagramsControllerDuplicateResponse>(getScadaDiagramsControllerDuplicateUrl(diagramId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      duplicateScadaDiagramDto,)
  }
);}



/**
 * @summary Get SCADA runtime snapshot by diagram ID
 */
export type scadaRuntimeControllerGetRuntimeResponse200 = {
  data: ScadaRuntimeResponseDto
  status: 200
}
    
export type scadaRuntimeControllerGetRuntimeResponseSuccess = (scadaRuntimeControllerGetRuntimeResponse200) & {
  headers: Headers;
};
;

export type scadaRuntimeControllerGetRuntimeResponse = (scadaRuntimeControllerGetRuntimeResponseSuccess)

export const getScadaRuntimeControllerGetRuntimeUrl = (diagramId: string,) => {


  

  return `/api/scada/diagrams/${diagramId}/runtime`
}

export const scadaRuntimeControllerGetRuntime = async (diagramId: string, options?: RequestInit): Promise<scadaRuntimeControllerGetRuntimeResponse> => {
  
  return customFetch<scadaRuntimeControllerGetRuntimeResponse>(getScadaRuntimeControllerGetRuntimeUrl(diagramId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary List bindable sensor channels for SCADA editor
 */
export type scadaBindingOptionsControllerFindAllResponse200 = {
  data: ScadaBindingOptionItemDto[]
  status: 200
}
    
export type scadaBindingOptionsControllerFindAllResponseSuccess = (scadaBindingOptionsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type scadaBindingOptionsControllerFindAllResponse = (scadaBindingOptionsControllerFindAllResponseSuccess)

export const getScadaBindingOptionsControllerFindAllUrl = (params?: ScadaBindingOptionsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/scada/binding-options?${stringifiedParams}` : `/api/scada/binding-options`
}

export const scadaBindingOptionsControllerFindAll = async (params?: ScadaBindingOptionsControllerFindAllParams, options?: RequestInit): Promise<scadaBindingOptionsControllerFindAllResponse> => {
  
  return customFetch<scadaBindingOptionsControllerFindAllResponse>(getScadaBindingOptionsControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
