/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UnpairedDeviceStatsDto } from '../../models/unpaired-device-stats-dto';

export interface UnpairedDevicesControllerGetStats$Params {
}

export function unpairedDevicesControllerGetStats(http: HttpClient, rootUrl: string, params?: UnpairedDevicesControllerGetStats$Params, context?: HttpContext): Observable<StrictHttpResponse<UnpairedDeviceStatsDto>> {
  const rb = new RequestBuilder(rootUrl, unpairedDevicesControllerGetStats.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UnpairedDeviceStatsDto>;
    })
  );
}

unpairedDevicesControllerGetStats.PATH = '/api/unpaired-devices/stats';
