/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UnpairedDeviceResponseDto } from '../../models/unpaired-device-response-dto';

export interface UnpairedDevicesControllerFindAll$Params {
  status?: 'pending' | 'paired' | 'ignored';
  nodeModelId?: string;
  projectId?: string;
  ownerId?: string;

/**
 * ISO date string
 */
  seenAfter?: string;

/**
 * ISO date string
 */
  seenBefore?: string;
  limit?: number;
  offset?: number;
}

export function unpairedDevicesControllerFindAll(http: HttpClient, rootUrl: string, params?: UnpairedDevicesControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UnpairedDeviceResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, unpairedDevicesControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('nodeModelId', params.nodeModelId, {});
    rb.query('projectId', params.projectId, {});
    rb.query('ownerId', params.ownerId, {});
    rb.query('seenAfter', params.seenAfter, {});
    rb.query('seenBefore', params.seenBefore, {});
    rb.query('limit', params.limit, {});
    rb.query('offset', params.offset, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UnpairedDeviceResponseDto>>;
    })
  );
}

unpairedDevicesControllerFindAll.PATH = '/api/unpaired-devices';
