/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PairDeviceDto } from '../../models/pair-device-dto';
import { UnpairedDeviceResponseDto } from '../../models/unpaired-device-response-dto';

export interface UnpairedDevicesControllerPairDevice$Params {

/**
 * Unpaired device UUID
 */
  id: string;
      body: PairDeviceDto
}

export function unpairedDevicesControllerPairDevice(http: HttpClient, rootUrl: string, params: UnpairedDevicesControllerPairDevice$Params, context?: HttpContext): Observable<StrictHttpResponse<UnpairedDeviceResponseDto>> {
  const rb = new RequestBuilder(rootUrl, unpairedDevicesControllerPairDevice.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UnpairedDeviceResponseDto>;
    })
  );
}

unpairedDevicesControllerPairDevice.PATH = '/api/unpaired-devices/{id}/pair';
