/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentResponseDto } from '../../models/document-response-dto';

export interface DocumentsControllerUpload$Params {
      body: {

/**
 * File to upload
 */
'file': Blob;

/**
 * Module name (e.g., project, node, map_layer)
 */
'fromModule': string;

/**
 * Module entity ID
 */
'fromModuleId': string;

/**
 * Optional document type override
 */
'documentType'?: string;

/**
 * Optional JSON metadata
 */
'metadata'?: string;
}
}

export function documentsControllerUpload(http: HttpClient, rootUrl: string, params: DocumentsControllerUpload$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, documentsControllerUpload.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentResponseDto>;
    })
  );
}

documentsControllerUpload.PATH = '/api/documents/upload';
