/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentResponseDto } from '../../models/document-response-dto';

export interface DocumentsControllerFindById$Params {
  id: string;
}

export function documentsControllerFindById(http: HttpClient, rootUrl: string, params: DocumentsControllerFindById$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, documentsControllerFindById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentResponseDto>;
    })
  );
}

documentsControllerFindById.PATH = '/api/documents/id/{id}';
