/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentResponseDto } from '../../models/document-response-dto';

export interface DocumentsControllerFindByModule$Params {
  fromModule: string;
  fromModuleId: string;
}

export function documentsControllerFindByModule(http: HttpClient, rootUrl: string, params: DocumentsControllerFindByModule$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DocumentResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, documentsControllerFindByModule.PATH, 'get');
  if (params) {
    rb.path('fromModule', params.fromModule, {});
    rb.path('fromModuleId', params.fromModuleId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DocumentResponseDto>>;
    })
  );
}

documentsControllerFindByModule.PATH = '/api/documents/{fromModule}/{fromModuleId}';
