/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ActivityLogResponseDto } from '../models/activity-log-response-dto';
import { AlertStreamResponseDto } from '../models/alert-stream-response-dto';
import { dashboardControllerGetActivityLog } from '../fn/dashboard/dashboard-controller-get-activity-log';
import { DashboardControllerGetActivityLog$Params } from '../fn/dashboard/dashboard-controller-get-activity-log';
import { dashboardControllerGetAlertStream } from '../fn/dashboard/dashboard-controller-get-alert-stream';
import { DashboardControllerGetAlertStream$Params } from '../fn/dashboard/dashboard-controller-get-alert-stream';
import { dashboardControllerGetDeliveryHealth } from '../fn/dashboard/dashboard-controller-get-delivery-health';
import { DashboardControllerGetDeliveryHealth$Params } from '../fn/dashboard/dashboard-controller-get-delivery-health';
import { dashboardControllerGetKpiStats } from '../fn/dashboard/dashboard-controller-get-kpi-stats';
import { DashboardControllerGetKpiStats$Params } from '../fn/dashboard/dashboard-controller-get-kpi-stats';
import { dashboardControllerGetNodeHealth } from '../fn/dashboard/dashboard-controller-get-node-health';
import { DashboardControllerGetNodeHealth$Params } from '../fn/dashboard/dashboard-controller-get-node-health';
import { dashboardControllerGetOwnerLeaderboard } from '../fn/dashboard/dashboard-controller-get-owner-leaderboard';
import { DashboardControllerGetOwnerLeaderboard$Params } from '../fn/dashboard/dashboard-controller-get-owner-leaderboard';
import { dashboardControllerGetPlatformStats } from '../fn/dashboard/dashboard-controller-get-platform-stats';
import { DashboardControllerGetPlatformStats$Params } from '../fn/dashboard/dashboard-controller-get-platform-stats';
import { dashboardControllerGetReleaseSchedule } from '../fn/dashboard/dashboard-controller-get-release-schedule';
import { DashboardControllerGetReleaseSchedule$Params } from '../fn/dashboard/dashboard-controller-get-release-schedule';
import { dashboardControllerGetTelemetryStreams } from '../fn/dashboard/dashboard-controller-get-telemetry-streams';
import { DashboardControllerGetTelemetryStreams$Params } from '../fn/dashboard/dashboard-controller-get-telemetry-streams';
import { DeliveryHealthResponseDto } from '../models/delivery-health-response-dto';
import { KpiStatsResponseDto } from '../models/kpi-stats-response-dto';
import { NodeHealthResponseDto } from '../models/node-health-response-dto';
import { OwnerLeaderboardResponseDto } from '../models/owner-leaderboard-response-dto';
import { ReleaseScheduleResponseDto } from '../models/release-schedule-response-dto';
import { TelemetryStreamsResponseDto } from '../models/telemetry-streams-response-dto';

@Injectable({ providedIn: 'root' })
export class DashboardService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `dashboardControllerGetPlatformStats()` */
  static readonly DashboardControllerGetPlatformStatsPath = '/api/dashboard/platform-stats';

  /**
   * Get platform statistics.
   *
   * Retrieve combined statistics for owners, projects, nodes, and sensors
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `dashboardControllerGetPlatformStats()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetPlatformStats$Response(params?: DashboardControllerGetPlatformStats$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return dashboardControllerGetPlatformStats(this.http, this.rootUrl, params, context);
  }

  /**
   * Get platform statistics.
   *
   * Retrieve combined statistics for owners, projects, nodes, and sensors
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `dashboardControllerGetPlatformStats$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetPlatformStats(params?: DashboardControllerGetPlatformStats$Params, context?: HttpContext): Observable<void> {
    return this.dashboardControllerGetPlatformStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `dashboardControllerGetKpiStats()` */
  static readonly DashboardControllerGetKpiStatsPath = '/api/dashboard/kpi-stats';

  /**
   * Get KPI statistics.
   *
   * Retrieve aggregated KPI metrics including nodes online, active alerts, telemetry rate, and forwarded payloads
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `dashboardControllerGetKpiStats()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetKpiStats$Response(params?: DashboardControllerGetKpiStats$Params, context?: HttpContext): Observable<StrictHttpResponse<KpiStatsResponseDto>> {
    return dashboardControllerGetKpiStats(this.http, this.rootUrl, params, context);
  }

  /**
   * Get KPI statistics.
   *
   * Retrieve aggregated KPI metrics including nodes online, active alerts, telemetry rate, and forwarded payloads
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `dashboardControllerGetKpiStats$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetKpiStats(params?: DashboardControllerGetKpiStats$Params, context?: HttpContext): Observable<KpiStatsResponseDto> {
    return this.dashboardControllerGetKpiStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<KpiStatsResponseDto>): KpiStatsResponseDto => r.body)
    );
  }

  /** Path part for operation `dashboardControllerGetNodeHealth()` */
  static readonly DashboardControllerGetNodeHealthPath = '/api/dashboard/node-health';

  /**
   * Get node health snapshot.
   *
   * Retrieve top impacted nodes with health status, battery level, and last seen information
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `dashboardControllerGetNodeHealth()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetNodeHealth$Response(params?: DashboardControllerGetNodeHealth$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeHealthResponseDto>> {
    return dashboardControllerGetNodeHealth(this.http, this.rootUrl, params, context);
  }

  /**
   * Get node health snapshot.
   *
   * Retrieve top impacted nodes with health status, battery level, and last seen information
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `dashboardControllerGetNodeHealth$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetNodeHealth(params?: DashboardControllerGetNodeHealth$Params, context?: HttpContext): Observable<NodeHealthResponseDto> {
    return this.dashboardControllerGetNodeHealth$Response(params, context).pipe(
      map((r: StrictHttpResponse<NodeHealthResponseDto>): NodeHealthResponseDto => r.body)
    );
  }

  /** Path part for operation `dashboardControllerGetOwnerLeaderboard()` */
  static readonly DashboardControllerGetOwnerLeaderboardPath = '/api/dashboard/owner-leaderboard';

  /**
   * Get owner leaderboard.
   *
   * Retrieve top owners ranked by telemetry throughput, with node counts and alert statistics
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `dashboardControllerGetOwnerLeaderboard()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetOwnerLeaderboard$Response(params?: DashboardControllerGetOwnerLeaderboard$Params, context?: HttpContext): Observable<StrictHttpResponse<OwnerLeaderboardResponseDto>> {
    return dashboardControllerGetOwnerLeaderboard(this.http, this.rootUrl, params, context);
  }

  /**
   * Get owner leaderboard.
   *
   * Retrieve top owners ranked by telemetry throughput, with node counts and alert statistics
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `dashboardControllerGetOwnerLeaderboard$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetOwnerLeaderboard(params?: DashboardControllerGetOwnerLeaderboard$Params, context?: HttpContext): Observable<OwnerLeaderboardResponseDto> {
    return this.dashboardControllerGetOwnerLeaderboard$Response(params, context).pipe(
      map((r: StrictHttpResponse<OwnerLeaderboardResponseDto>): OwnerLeaderboardResponseDto => r.body)
    );
  }

  /** Path part for operation `dashboardControllerGetActivityLog()` */
  static readonly DashboardControllerGetActivityLogPath = '/api/dashboard/activity-log';

  /**
   * Get activity log.
   *
   * Retrieve recent system activities including webhook executions, alert triggers, and node status changes
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `dashboardControllerGetActivityLog()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetActivityLog$Response(params?: DashboardControllerGetActivityLog$Params, context?: HttpContext): Observable<StrictHttpResponse<ActivityLogResponseDto>> {
    return dashboardControllerGetActivityLog(this.http, this.rootUrl, params, context);
  }

  /**
   * Get activity log.
   *
   * Retrieve recent system activities including webhook executions, alert triggers, and node status changes
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `dashboardControllerGetActivityLog$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetActivityLog(params?: DashboardControllerGetActivityLog$Params, context?: HttpContext): Observable<ActivityLogResponseDto> {
    return this.dashboardControllerGetActivityLog$Response(params, context).pipe(
      map((r: StrictHttpResponse<ActivityLogResponseDto>): ActivityLogResponseDto => r.body)
    );
  }

  /** Path part for operation `dashboardControllerGetTelemetryStreams()` */
  static readonly DashboardControllerGetTelemetryStreamsPath = '/api/dashboard/telemetry-streams';

  /**
   * Get telemetry streams.
   *
   * Retrieve hourly telemetry data for flow and pressure channels with ingestion and forwarding statistics
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `dashboardControllerGetTelemetryStreams()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetTelemetryStreams$Response(params?: DashboardControllerGetTelemetryStreams$Params, context?: HttpContext): Observable<StrictHttpResponse<TelemetryStreamsResponseDto>> {
    return dashboardControllerGetTelemetryStreams(this.http, this.rootUrl, params, context);
  }

  /**
   * Get telemetry streams.
   *
   * Retrieve hourly telemetry data for flow and pressure channels with ingestion and forwarding statistics
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `dashboardControllerGetTelemetryStreams$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetTelemetryStreams(params?: DashboardControllerGetTelemetryStreams$Params, context?: HttpContext): Observable<TelemetryStreamsResponseDto> {
    return this.dashboardControllerGetTelemetryStreams$Response(params, context).pipe(
      map((r: StrictHttpResponse<TelemetryStreamsResponseDto>): TelemetryStreamsResponseDto => r.body)
    );
  }

  /** Path part for operation `dashboardControllerGetDeliveryHealth()` */
  static readonly DashboardControllerGetDeliveryHealthPath = '/api/dashboard/delivery-health';

  /**
   * Get delivery health.
   *
   * Retrieve webhook and database forwarding health status with success rates and last sync times
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `dashboardControllerGetDeliveryHealth()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetDeliveryHealth$Response(params?: DashboardControllerGetDeliveryHealth$Params, context?: HttpContext): Observable<StrictHttpResponse<DeliveryHealthResponseDto>> {
    return dashboardControllerGetDeliveryHealth(this.http, this.rootUrl, params, context);
  }

  /**
   * Get delivery health.
   *
   * Retrieve webhook and database forwarding health status with success rates and last sync times
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `dashboardControllerGetDeliveryHealth$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetDeliveryHealth(params?: DashboardControllerGetDeliveryHealth$Params, context?: HttpContext): Observable<DeliveryHealthResponseDto> {
    return this.dashboardControllerGetDeliveryHealth$Response(params, context).pipe(
      map((r: StrictHttpResponse<DeliveryHealthResponseDto>): DeliveryHealthResponseDto => r.body)
    );
  }

  /** Path part for operation `dashboardControllerGetAlertStream()` */
  static readonly DashboardControllerGetAlertStreamPath = '/api/dashboard/alert-stream';

  /**
   * Get alert stream.
   *
   * Retrieve latest active alerts with severity levels and affected sensors
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `dashboardControllerGetAlertStream()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetAlertStream$Response(params?: DashboardControllerGetAlertStream$Params, context?: HttpContext): Observable<StrictHttpResponse<AlertStreamResponseDto>> {
    return dashboardControllerGetAlertStream(this.http, this.rootUrl, params, context);
  }

  /**
   * Get alert stream.
   *
   * Retrieve latest active alerts with severity levels and affected sensors
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `dashboardControllerGetAlertStream$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetAlertStream(params?: DashboardControllerGetAlertStream$Params, context?: HttpContext): Observable<AlertStreamResponseDto> {
    return this.dashboardControllerGetAlertStream$Response(params, context).pipe(
      map((r: StrictHttpResponse<AlertStreamResponseDto>): AlertStreamResponseDto => r.body)
    );
  }

  /** Path part for operation `dashboardControllerGetReleaseSchedule()` */
  static readonly DashboardControllerGetReleaseSchedulePath = '/api/dashboard/release-schedule';

  /**
   * Get release schedule.
   *
   * Retrieve next scheduled firmware/maintenance release window
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `dashboardControllerGetReleaseSchedule()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetReleaseSchedule$Response(params?: DashboardControllerGetReleaseSchedule$Params, context?: HttpContext): Observable<StrictHttpResponse<ReleaseScheduleResponseDto>> {
    return dashboardControllerGetReleaseSchedule(this.http, this.rootUrl, params, context);
  }

  /**
   * Get release schedule.
   *
   * Retrieve next scheduled firmware/maintenance release window
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `dashboardControllerGetReleaseSchedule$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  dashboardControllerGetReleaseSchedule(params?: DashboardControllerGetReleaseSchedule$Params, context?: HttpContext): Observable<ReleaseScheduleResponseDto> {
    return this.dashboardControllerGetReleaseSchedule$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReleaseScheduleResponseDto>): ReleaseScheduleResponseDto => r.body)
    );
  }

}
