/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { iotLogsControllerFindAll } from '../fn/io-t-logs/iot-logs-controller-find-all';
import { IotLogsControllerFindAll$Params } from '../fn/io-t-logs/iot-logs-controller-find-all';
import { iotLogsControllerGetStats } from '../fn/io-t-logs/iot-logs-controller-get-stats';
import { IotLogsControllerGetStats$Params } from '../fn/io-t-logs/iot-logs-controller-get-stats';
import { IotLogStatsDto } from '../models/iot-log-stats-dto';

@Injectable({ providedIn: 'root' })
export class IoTLogsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `iotLogsControllerGetStats()` */
  static readonly IotLogsControllerGetStatsPath = '/api/iot-logs/stats';

  /**
   * Get IoT logs statistics.
   *
   * Get aggregated statistics of IoT logs including total, processed, unprocessed counts and breakdown by label. Supports filtering by device, owner, project, label, and date range.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `iotLogsControllerGetStats()` instead.
   *
   * This method doesn't expect any request body.
   */
  iotLogsControllerGetStats$Response(params?: IotLogsControllerGetStats$Params, context?: HttpContext): Observable<StrictHttpResponse<IotLogStatsDto>> {
    return iotLogsControllerGetStats(this.http, this.rootUrl, params, context);
  }

  /**
   * Get IoT logs statistics.
   *
   * Get aggregated statistics of IoT logs including total, processed, unprocessed counts and breakdown by label. Supports filtering by device, owner, project, label, and date range.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `iotLogsControllerGetStats$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  iotLogsControllerGetStats(params?: IotLogsControllerGetStats$Params, context?: HttpContext): Observable<IotLogStatsDto> {
    return this.iotLogsControllerGetStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<IotLogStatsDto>): IotLogStatsDto => r.body)
    );
  }

  /** Path part for operation `iotLogsControllerFindAll()` */
  static readonly IotLogsControllerFindAllPath = '/api/iot-logs';

  /**
   * Get IoT logs list.
   *
   * Get paginated list of IoT logs with optional filters. Includes relations to node, project, and owner.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `iotLogsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  iotLogsControllerFindAll$Response(params?: IotLogsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return iotLogsControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get IoT logs list.
   *
   * Get paginated list of IoT logs with optional filters. Includes relations to node, project, and owner.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `iotLogsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  iotLogsControllerFindAll(params?: IotLogsControllerFindAll$Params, context?: HttpContext): Observable<void> {
    return this.iotLogsControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
