/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { anomaliesControllerAcknowledge } from '../fn/ml-anomalies/anomalies-controller-acknowledge';
import { AnomaliesControllerAcknowledge$Params } from '../fn/ml-anomalies/anomalies-controller-acknowledge';
import { anomaliesControllerFindAll } from '../fn/ml-anomalies/anomalies-controller-find-all';
import { AnomaliesControllerFindAll$Params } from '../fn/ml-anomalies/anomalies-controller-find-all';
import { anomaliesControllerFindBySensorChannel } from '../fn/ml-anomalies/anomalies-controller-find-by-sensor-channel';
import { AnomaliesControllerFindBySensorChannel$Params } from '../fn/ml-anomalies/anomalies-controller-find-by-sensor-channel';
import { anomaliesControllerFindOne } from '../fn/ml-anomalies/anomalies-controller-find-one';
import { AnomaliesControllerFindOne$Params } from '../fn/ml-anomalies/anomalies-controller-find-one';
import { anomaliesControllerGetSummary } from '../fn/ml-anomalies/anomalies-controller-get-summary';
import { AnomaliesControllerGetSummary$Params } from '../fn/ml-anomalies/anomalies-controller-get-summary';
import { AnomalyResponseDto } from '../models/anomaly-response-dto';
import { AnomalySummaryDto } from '../models/anomaly-summary-dto';

@Injectable({ providedIn: 'root' })
export class MlAnomaliesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `anomaliesControllerGetSummary()` */
  static readonly AnomaliesControllerGetSummaryPath = '/api/ml/anomalies/summary';

  /**
   * Get anomaly statistics summary.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `anomaliesControllerGetSummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  anomaliesControllerGetSummary$Response(params?: AnomaliesControllerGetSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<AnomalySummaryDto>> {
    return anomaliesControllerGetSummary(this.http, this.rootUrl, params, context);
  }

  /**
   * Get anomaly statistics summary.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `anomaliesControllerGetSummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  anomaliesControllerGetSummary(params?: AnomaliesControllerGetSummary$Params, context?: HttpContext): Observable<AnomalySummaryDto> {
    return this.anomaliesControllerGetSummary$Response(params, context).pipe(
      map((r: StrictHttpResponse<AnomalySummaryDto>): AnomalySummaryDto => r.body)
    );
  }

  /** Path part for operation `anomaliesControllerFindAll()` */
  static readonly AnomaliesControllerFindAllPath = '/api/ml/anomalies';

  /**
   * Get all anomalies with filters and pagination.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `anomaliesControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  anomaliesControllerFindAll$Response(params?: AnomaliesControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return anomaliesControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all anomalies with filters and pagination.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `anomaliesControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  anomaliesControllerFindAll(params?: AnomaliesControllerFindAll$Params, context?: HttpContext): Observable<void> {
    return this.anomaliesControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `anomaliesControllerFindBySensorChannel()` */
  static readonly AnomaliesControllerFindBySensorChannelPath = '/api/ml/anomalies/by-sensor/{idSensorChannel}';

  /**
   * Get anomalies for a specific sensor channel.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `anomaliesControllerFindBySensorChannel()` instead.
   *
   * This method doesn't expect any request body.
   */
  anomaliesControllerFindBySensorChannel$Response(params: AnomaliesControllerFindBySensorChannel$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AnomalyResponseDto>>> {
    return anomaliesControllerFindBySensorChannel(this.http, this.rootUrl, params, context);
  }

  /**
   * Get anomalies for a specific sensor channel.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `anomaliesControllerFindBySensorChannel$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  anomaliesControllerFindBySensorChannel(params: AnomaliesControllerFindBySensorChannel$Params, context?: HttpContext): Observable<Array<AnomalyResponseDto>> {
    return this.anomaliesControllerFindBySensorChannel$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<AnomalyResponseDto>>): Array<AnomalyResponseDto> => r.body)
    );
  }

  /** Path part for operation `anomaliesControllerFindOne()` */
  static readonly AnomaliesControllerFindOnePath = '/api/ml/anomalies/{id}';

  /**
   * Get anomaly by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `anomaliesControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  anomaliesControllerFindOne$Response(params: AnomaliesControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<AnomalyResponseDto>> {
    return anomaliesControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get anomaly by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `anomaliesControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  anomaliesControllerFindOne(params: AnomaliesControllerFindOne$Params, context?: HttpContext): Observable<AnomalyResponseDto> {
    return this.anomaliesControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<AnomalyResponseDto>): AnomalyResponseDto => r.body)
    );
  }

  /** Path part for operation `anomaliesControllerAcknowledge()` */
  static readonly AnomaliesControllerAcknowledgePath = '/api/ml/anomalies/{id}/acknowledge';

  /**
   * Acknowledge an anomaly.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `anomaliesControllerAcknowledge()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  anomaliesControllerAcknowledge$Response(params: AnomaliesControllerAcknowledge$Params, context?: HttpContext): Observable<StrictHttpResponse<AnomalyResponseDto>> {
    return anomaliesControllerAcknowledge(this.http, this.rootUrl, params, context);
  }

  /**
   * Acknowledge an anomaly.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `anomaliesControllerAcknowledge$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  anomaliesControllerAcknowledge(params: AnomaliesControllerAcknowledge$Params, context?: HttpContext): Observable<AnomalyResponseDto> {
    return this.anomaliesControllerAcknowledge$Response(params, context).pipe(
      map((r: StrictHttpResponse<AnomalyResponseDto>): AnomalyResponseDto => r.body)
    );
  }

}
