/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { mlNotificationControllerClearDedupCache } from '../fn/ml-notifications/ml-notification-controller-clear-dedup-cache';
import { MlNotificationControllerClearDedupCache$Params } from '../fn/ml-notifications/ml-notification-controller-clear-dedup-cache';
import { mlNotificationControllerGetDedupStats } from '../fn/ml-notifications/ml-notification-controller-get-dedup-stats';
import { MlNotificationControllerGetDedupStats$Params } from '../fn/ml-notifications/ml-notification-controller-get-dedup-stats';
import { mlNotificationControllerGetStats } from '../fn/ml-notifications/ml-notification-controller-get-stats';
import { MlNotificationControllerGetStats$Params } from '../fn/ml-notifications/ml-notification-controller-get-stats';
import { mlNotificationControllerPreviewAlert } from '../fn/ml-notifications/ml-notification-controller-preview-alert';
import { MlNotificationControllerPreviewAlert$Params } from '../fn/ml-notifications/ml-notification-controller-preview-alert';
import { mlNotificationControllerPreviewDailySummary } from '../fn/ml-notifications/ml-notification-controller-preview-daily-summary';
import { MlNotificationControllerPreviewDailySummary$Params } from '../fn/ml-notifications/ml-notification-controller-preview-daily-summary';
import { mlNotificationControllerResetSuppression } from '../fn/ml-notifications/ml-notification-controller-reset-suppression';
import { MlNotificationControllerResetSuppression$Params } from '../fn/ml-notifications/ml-notification-controller-reset-suppression';
import { mlNotificationControllerSendDailySummary } from '../fn/ml-notifications/ml-notification-controller-send-daily-summary';
import { MlNotificationControllerSendDailySummary$Params } from '../fn/ml-notifications/ml-notification-controller-send-daily-summary';
import { mlNotificationControllerTestAlert } from '../fn/ml-notifications/ml-notification-controller-test-alert';
import { MlNotificationControllerTestAlert$Params } from '../fn/ml-notifications/ml-notification-controller-test-alert';

@Injectable({ providedIn: 'root' })
export class MlNotificationsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `mlNotificationControllerTestAlert()` */
  static readonly MlNotificationControllerTestAlertPath = '/api/notifications/ml/test-alert';

  /**
   * Test anomaly alert email.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `mlNotificationControllerTestAlert()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  mlNotificationControllerTestAlert$Response(params: MlNotificationControllerTestAlert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return mlNotificationControllerTestAlert(this.http, this.rootUrl, params, context);
  }

  /**
   * Test anomaly alert email.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `mlNotificationControllerTestAlert$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  mlNotificationControllerTestAlert(params: MlNotificationControllerTestAlert$Params, context?: HttpContext): Observable<void> {
    return this.mlNotificationControllerTestAlert$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `mlNotificationControllerPreviewAlert()` */
  static readonly MlNotificationControllerPreviewAlertPath = '/api/notifications/ml/preview/alert';

  /**
   * Preview anomaly alert HTML.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `mlNotificationControllerPreviewAlert()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  mlNotificationControllerPreviewAlert$Response(params: MlNotificationControllerPreviewAlert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return mlNotificationControllerPreviewAlert(this.http, this.rootUrl, params, context);
  }

  /**
   * Preview anomaly alert HTML.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `mlNotificationControllerPreviewAlert$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  mlNotificationControllerPreviewAlert(params: MlNotificationControllerPreviewAlert$Params, context?: HttpContext): Observable<void> {
    return this.mlNotificationControllerPreviewAlert$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `mlNotificationControllerPreviewDailySummary()` */
  static readonly MlNotificationControllerPreviewDailySummaryPath = '/api/notifications/ml/preview/daily-summary';

  /**
   * Preview daily summary HTML.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `mlNotificationControllerPreviewDailySummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  mlNotificationControllerPreviewDailySummary$Response(params?: MlNotificationControllerPreviewDailySummary$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return mlNotificationControllerPreviewDailySummary(this.http, this.rootUrl, params, context);
  }

  /**
   * Preview daily summary HTML.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `mlNotificationControllerPreviewDailySummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  mlNotificationControllerPreviewDailySummary(params?: MlNotificationControllerPreviewDailySummary$Params, context?: HttpContext): Observable<void> {
    return this.mlNotificationControllerPreviewDailySummary$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `mlNotificationControllerGetDedupStats()` */
  static readonly MlNotificationControllerGetDedupStatsPath = '/api/notifications/ml/dedup-stats';

  /**
   * Get alert deduplication statistics.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `mlNotificationControllerGetDedupStats()` instead.
   *
   * This method doesn't expect any request body.
   */
  mlNotificationControllerGetDedupStats$Response(params?: MlNotificationControllerGetDedupStats$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return mlNotificationControllerGetDedupStats(this.http, this.rootUrl, params, context);
  }

  /**
   * Get alert deduplication statistics.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `mlNotificationControllerGetDedupStats$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  mlNotificationControllerGetDedupStats(params?: MlNotificationControllerGetDedupStats$Params, context?: HttpContext): Observable<void> {
    return this.mlNotificationControllerGetDedupStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `mlNotificationControllerClearDedupCache()` */
  static readonly MlNotificationControllerClearDedupCachePath = '/api/notifications/ml/dedup/clear';

  /**
   * Clear deduplication cache.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `mlNotificationControllerClearDedupCache()` instead.
   *
   * This method doesn't expect any request body.
   */
  mlNotificationControllerClearDedupCache$Response(params?: MlNotificationControllerClearDedupCache$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return mlNotificationControllerClearDedupCache(this.http, this.rootUrl, params, context);
  }

  /**
   * Clear deduplication cache.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `mlNotificationControllerClearDedupCache$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  mlNotificationControllerClearDedupCache(params?: MlNotificationControllerClearDedupCache$Params, context?: HttpContext): Observable<void> {
    return this.mlNotificationControllerClearDedupCache$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `mlNotificationControllerResetSuppression()` */
  static readonly MlNotificationControllerResetSuppressionPath = '/api/notifications/ml/dedup/reset/{deviceId}/{sensorKey}/{severity}';

  /**
   * Reset suppression for specific alert.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `mlNotificationControllerResetSuppression()` instead.
   *
   * This method doesn't expect any request body.
   */
  mlNotificationControllerResetSuppression$Response(params: MlNotificationControllerResetSuppression$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return mlNotificationControllerResetSuppression(this.http, this.rootUrl, params, context);
  }

  /**
   * Reset suppression for specific alert.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `mlNotificationControllerResetSuppression$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  mlNotificationControllerResetSuppression(params: MlNotificationControllerResetSuppression$Params, context?: HttpContext): Observable<void> {
    return this.mlNotificationControllerResetSuppression$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `mlNotificationControllerSendDailySummary()` */
  static readonly MlNotificationControllerSendDailySummaryPath = '/api/notifications/ml/send-daily-summary';

  /**
   * Manually trigger daily summary email.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `mlNotificationControllerSendDailySummary()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  mlNotificationControllerSendDailySummary$Response(params: MlNotificationControllerSendDailySummary$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return mlNotificationControllerSendDailySummary(this.http, this.rootUrl, params, context);
  }

  /**
   * Manually trigger daily summary email.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `mlNotificationControllerSendDailySummary$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  mlNotificationControllerSendDailySummary(params: MlNotificationControllerSendDailySummary$Params, context?: HttpContext): Observable<void> {
    return this.mlNotificationControllerSendDailySummary$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `mlNotificationControllerGetStats()` */
  static readonly MlNotificationControllerGetStatsPath = '/api/notifications/ml/stats';

  /**
   * Get ML notification service statistics.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `mlNotificationControllerGetStats()` instead.
   *
   * This method doesn't expect any request body.
   */
  mlNotificationControllerGetStats$Response(params?: MlNotificationControllerGetStats$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return mlNotificationControllerGetStats(this.http, this.rootUrl, params, context);
  }

  /**
   * Get ML notification service statistics.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `mlNotificationControllerGetStats$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  mlNotificationControllerGetStats(params?: MlNotificationControllerGetStats$Params, context?: HttpContext): Observable<void> {
    return this.mlNotificationControllerGetStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
