/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { NodeAssignmentResponseDto } from '../models/node-assignment-response-dto';
import { nodeAssignmentsControllerCreate } from '../fn/node-assignments/node-assignments-controller-create';
import { NodeAssignmentsControllerCreate$Params } from '../fn/node-assignments/node-assignments-controller-create';
import { nodeAssignmentsControllerFindAll } from '../fn/node-assignments/node-assignments-controller-find-all';
import { NodeAssignmentsControllerFindAll$Params } from '../fn/node-assignments/node-assignments-controller-find-all';
import { nodeAssignmentsControllerFindOne } from '../fn/node-assignments/node-assignments-controller-find-one';
import { NodeAssignmentsControllerFindOne$Params } from '../fn/node-assignments/node-assignments-controller-find-one';
import { nodeAssignmentsControllerRemove } from '../fn/node-assignments/node-assignments-controller-remove';
import { NodeAssignmentsControllerRemove$Params } from '../fn/node-assignments/node-assignments-controller-remove';
import { nodeAssignmentsControllerUpdate } from '../fn/node-assignments/node-assignments-controller-update';
import { NodeAssignmentsControllerUpdate$Params } from '../fn/node-assignments/node-assignments-controller-update';

@Injectable({ providedIn: 'root' })
export class NodeAssignmentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `nodeAssignmentsControllerFindAll()` */
  static readonly NodeAssignmentsControllerFindAllPath = '/api/node-assignments';

  /**
   * Get all node assignments.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeAssignmentsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeAssignmentsControllerFindAll$Response(params?: NodeAssignmentsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return nodeAssignmentsControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all node assignments.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeAssignmentsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeAssignmentsControllerFindAll(params?: NodeAssignmentsControllerFindAll$Params, context?: HttpContext): Observable<void> {
    return this.nodeAssignmentsControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `nodeAssignmentsControllerCreate()` */
  static readonly NodeAssignmentsControllerCreatePath = '/api/node-assignments';

  /**
   * Create a new node assignment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeAssignmentsControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  nodeAssignmentsControllerCreate$Response(params: NodeAssignmentsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeAssignmentResponseDto>> {
    return nodeAssignmentsControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new node assignment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeAssignmentsControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  nodeAssignmentsControllerCreate(params: NodeAssignmentsControllerCreate$Params, context?: HttpContext): Observable<NodeAssignmentResponseDto> {
    return this.nodeAssignmentsControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<NodeAssignmentResponseDto>): NodeAssignmentResponseDto => r.body)
    );
  }

  /** Path part for operation `nodeAssignmentsControllerFindOne()` */
  static readonly NodeAssignmentsControllerFindOnePath = '/api/node-assignments/{id}';

  /**
   * Get node assignment by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeAssignmentsControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeAssignmentsControllerFindOne$Response(params: NodeAssignmentsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeAssignmentResponseDto>> {
    return nodeAssignmentsControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get node assignment by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeAssignmentsControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeAssignmentsControllerFindOne(params: NodeAssignmentsControllerFindOne$Params, context?: HttpContext): Observable<NodeAssignmentResponseDto> {
    return this.nodeAssignmentsControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<NodeAssignmentResponseDto>): NodeAssignmentResponseDto => r.body)
    );
  }

  /** Path part for operation `nodeAssignmentsControllerRemove()` */
  static readonly NodeAssignmentsControllerRemovePath = '/api/node-assignments/{id}';

  /**
   * Delete node assignment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeAssignmentsControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeAssignmentsControllerRemove$Response(params: NodeAssignmentsControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return nodeAssignmentsControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete node assignment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeAssignmentsControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeAssignmentsControllerRemove(params: NodeAssignmentsControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.nodeAssignmentsControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `nodeAssignmentsControllerUpdate()` */
  static readonly NodeAssignmentsControllerUpdatePath = '/api/node-assignments/{id}';

  /**
   * Update node assignment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeAssignmentsControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  nodeAssignmentsControllerUpdate$Response(params: NodeAssignmentsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeAssignmentResponseDto>> {
    return nodeAssignmentsControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Update node assignment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeAssignmentsControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  nodeAssignmentsControllerUpdate(params: NodeAssignmentsControllerUpdate$Params, context?: HttpContext): Observable<NodeAssignmentResponseDto> {
    return this.nodeAssignmentsControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<NodeAssignmentResponseDto>): NodeAssignmentResponseDto => r.body)
    );
  }

}
