/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { NodeProfileResponseDto } from '../models/node-profile-response-dto';
import { nodeProfilesControllerCreate } from '../fn/node-profiles/node-profiles-controller-create';
import { NodeProfilesControllerCreate$Params } from '../fn/node-profiles/node-profiles-controller-create';
import { nodeProfilesControllerFindAll } from '../fn/node-profiles/node-profiles-controller-find-all';
import { NodeProfilesControllerFindAll$Params } from '../fn/node-profiles/node-profiles-controller-find-all';
import { nodeProfilesControllerFindByCode } from '../fn/node-profiles/node-profiles-controller-find-by-code';
import { NodeProfilesControllerFindByCode$Params } from '../fn/node-profiles/node-profiles-controller-find-by-code';
import { nodeProfilesControllerFindOne } from '../fn/node-profiles/node-profiles-controller-find-one';
import { NodeProfilesControllerFindOne$Params } from '../fn/node-profiles/node-profiles-controller-find-one';
import { nodeProfilesControllerRemove } from '../fn/node-profiles/node-profiles-controller-remove';
import { NodeProfilesControllerRemove$Params } from '../fn/node-profiles/node-profiles-controller-remove';
import { nodeProfilesControllerUpdate } from '../fn/node-profiles/node-profiles-controller-update';
import { NodeProfilesControllerUpdate$Params } from '../fn/node-profiles/node-profiles-controller-update';

@Injectable({ providedIn: 'root' })
export class NodeProfilesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `nodeProfilesControllerFindAll()` */
  static readonly NodeProfilesControllerFindAllPath = '/api/node-profiles';

  /**
   * Get all node profiles.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeProfilesControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeProfilesControllerFindAll$Response(params?: NodeProfilesControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return nodeProfilesControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all node profiles.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeProfilesControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeProfilesControllerFindAll(params?: NodeProfilesControllerFindAll$Params, context?: HttpContext): Observable<void> {
    return this.nodeProfilesControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `nodeProfilesControllerCreate()` */
  static readonly NodeProfilesControllerCreatePath = '/api/node-profiles';

  /**
   * Create a new node profile.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeProfilesControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  nodeProfilesControllerCreate$Response(params: NodeProfilesControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeProfileResponseDto>> {
    return nodeProfilesControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new node profile.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeProfilesControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  nodeProfilesControllerCreate(params: NodeProfilesControllerCreate$Params, context?: HttpContext): Observable<NodeProfileResponseDto> {
    return this.nodeProfilesControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<NodeProfileResponseDto>): NodeProfileResponseDto => r.body)
    );
  }

  /** Path part for operation `nodeProfilesControllerFindByCode()` */
  static readonly NodeProfilesControllerFindByCodePath = '/api/node-profiles/by-code/{code}';

  /**
   * Get node profile by code.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeProfilesControllerFindByCode()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeProfilesControllerFindByCode$Response(params: NodeProfilesControllerFindByCode$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeProfileResponseDto>> {
    return nodeProfilesControllerFindByCode(this.http, this.rootUrl, params, context);
  }

  /**
   * Get node profile by code.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeProfilesControllerFindByCode$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeProfilesControllerFindByCode(params: NodeProfilesControllerFindByCode$Params, context?: HttpContext): Observable<NodeProfileResponseDto> {
    return this.nodeProfilesControllerFindByCode$Response(params, context).pipe(
      map((r: StrictHttpResponse<NodeProfileResponseDto>): NodeProfileResponseDto => r.body)
    );
  }

  /** Path part for operation `nodeProfilesControllerFindOne()` */
  static readonly NodeProfilesControllerFindOnePath = '/api/node-profiles/{id}';

  /**
   * Get node profile by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeProfilesControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeProfilesControllerFindOne$Response(params: NodeProfilesControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeProfileResponseDto>> {
    return nodeProfilesControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get node profile by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeProfilesControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeProfilesControllerFindOne(params: NodeProfilesControllerFindOne$Params, context?: HttpContext): Observable<NodeProfileResponseDto> {
    return this.nodeProfilesControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<NodeProfileResponseDto>): NodeProfileResponseDto => r.body)
    );
  }

  /** Path part for operation `nodeProfilesControllerRemove()` */
  static readonly NodeProfilesControllerRemovePath = '/api/node-profiles/{id}';

  /**
   * Delete node profile.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeProfilesControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeProfilesControllerRemove$Response(params: NodeProfilesControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return nodeProfilesControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete node profile.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeProfilesControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeProfilesControllerRemove(params: NodeProfilesControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.nodeProfilesControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `nodeProfilesControllerUpdate()` */
  static readonly NodeProfilesControllerUpdatePath = '/api/node-profiles/{id}';

  /**
   * Update node profile.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeProfilesControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  nodeProfilesControllerUpdate$Response(params: NodeProfilesControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeProfileResponseDto>> {
    return nodeProfilesControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Update node profile.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeProfilesControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  nodeProfilesControllerUpdate(params: NodeProfilesControllerUpdate$Params, context?: HttpContext): Observable<NodeProfileResponseDto> {
    return this.nodeProfilesControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<NodeProfileResponseDto>): NodeProfileResponseDto => r.body)
    );
  }

}
