/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { NodeLocationResponseDto } from '../models/node-location-response-dto';
import { nodeLocationsControllerCreate } from '../fn/node-locations/node-locations-controller-create';
import { NodeLocationsControllerCreate$Params } from '../fn/node-locations/node-locations-controller-create';
import { nodeLocationsControllerFindAll } from '../fn/node-locations/node-locations-controller-find-all';
import { NodeLocationsControllerFindAll$Params } from '../fn/node-locations/node-locations-controller-find-all';
import { nodeLocationsControllerFindOne } from '../fn/node-locations/node-locations-controller-find-one';
import { NodeLocationsControllerFindOne$Params } from '../fn/node-locations/node-locations-controller-find-one';
import { nodeLocationsControllerRemove } from '../fn/node-locations/node-locations-controller-remove';
import { NodeLocationsControllerRemove$Params } from '../fn/node-locations/node-locations-controller-remove';
import { nodeLocationsControllerUpdate } from '../fn/node-locations/node-locations-controller-update';
import { NodeLocationsControllerUpdate$Params } from '../fn/node-locations/node-locations-controller-update';

@Injectable({ providedIn: 'root' })
export class NodeLocationsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `nodeLocationsControllerFindAll()` */
  static readonly NodeLocationsControllerFindAllPath = '/api/node-locations';

  /**
   * Get all node locations.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeLocationsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeLocationsControllerFindAll$Response(params?: NodeLocationsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return nodeLocationsControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all node locations.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeLocationsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeLocationsControllerFindAll(params?: NodeLocationsControllerFindAll$Params, context?: HttpContext): Observable<void> {
    return this.nodeLocationsControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `nodeLocationsControllerCreate()` */
  static readonly NodeLocationsControllerCreatePath = '/api/node-locations';

  /**
   * Create a new node location.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeLocationsControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  nodeLocationsControllerCreate$Response(params: NodeLocationsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeLocationResponseDto>> {
    return nodeLocationsControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new node location.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeLocationsControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  nodeLocationsControllerCreate(params: NodeLocationsControllerCreate$Params, context?: HttpContext): Observable<NodeLocationResponseDto> {
    return this.nodeLocationsControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<NodeLocationResponseDto>): NodeLocationResponseDto => r.body)
    );
  }

  /** Path part for operation `nodeLocationsControllerFindOne()` */
  static readonly NodeLocationsControllerFindOnePath = '/api/node-locations/{id}';

  /**
   * Get node location by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeLocationsControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeLocationsControllerFindOne$Response(params: NodeLocationsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeLocationResponseDto>> {
    return nodeLocationsControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get node location by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeLocationsControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeLocationsControllerFindOne(params: NodeLocationsControllerFindOne$Params, context?: HttpContext): Observable<NodeLocationResponseDto> {
    return this.nodeLocationsControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<NodeLocationResponseDto>): NodeLocationResponseDto => r.body)
    );
  }

  /** Path part for operation `nodeLocationsControllerRemove()` */
  static readonly NodeLocationsControllerRemovePath = '/api/node-locations/{id}';

  /**
   * Delete node location.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeLocationsControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeLocationsControllerRemove$Response(params: NodeLocationsControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return nodeLocationsControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete node location.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeLocationsControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  nodeLocationsControllerRemove(params: NodeLocationsControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.nodeLocationsControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `nodeLocationsControllerUpdate()` */
  static readonly NodeLocationsControllerUpdatePath = '/api/node-locations/{id}';

  /**
   * Update node location.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `nodeLocationsControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  nodeLocationsControllerUpdate$Response(params: NodeLocationsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeLocationResponseDto>> {
    return nodeLocationsControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Update node location.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `nodeLocationsControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  nodeLocationsControllerUpdate(params: NodeLocationsControllerUpdate$Params, context?: HttpContext): Observable<NodeLocationResponseDto> {
    return this.nodeLocationsControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<NodeLocationResponseDto>): NodeLocationResponseDto => r.body)
    );
  }

}
