/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { notificationsControllerCreate } from '../fn/notifications/notifications-controller-create';
import { NotificationsControllerCreate$Params } from '../fn/notifications/notifications-controller-create';
import { notificationsControllerCreateChannel } from '../fn/notifications/notifications-controller-create-channel';
import { NotificationsControllerCreateChannel$Params } from '../fn/notifications/notifications-controller-create-channel';
import { notificationsControllerFindAll } from '../fn/notifications/notifications-controller-find-all';
import { NotificationsControllerFindAll$Params } from '../fn/notifications/notifications-controller-find-all';
import { notificationsControllerFindAllChannels } from '../fn/notifications/notifications-controller-find-all-channels';
import { NotificationsControllerFindAllChannels$Params } from '../fn/notifications/notifications-controller-find-all-channels';
import { notificationsControllerFindOne } from '../fn/notifications/notifications-controller-find-one';
import { NotificationsControllerFindOne$Params } from '../fn/notifications/notifications-controller-find-one';
import { notificationsControllerFindOneChannel } from '../fn/notifications/notifications-controller-find-one-channel';
import { NotificationsControllerFindOneChannel$Params } from '../fn/notifications/notifications-controller-find-one-channel';
import { notificationsControllerGetUnreadCount } from '../fn/notifications/notifications-controller-get-unread-count';
import { NotificationsControllerGetUnreadCount$Params } from '../fn/notifications/notifications-controller-get-unread-count';
import { notificationsControllerMarkAllAsRead } from '../fn/notifications/notifications-controller-mark-all-as-read';
import { NotificationsControllerMarkAllAsRead$Params } from '../fn/notifications/notifications-controller-mark-all-as-read';
import { notificationsControllerMarkAsRead } from '../fn/notifications/notifications-controller-mark-as-read';
import { NotificationsControllerMarkAsRead$Params } from '../fn/notifications/notifications-controller-mark-as-read';
import { notificationsControllerRemove } from '../fn/notifications/notifications-controller-remove';
import { NotificationsControllerRemove$Params } from '../fn/notifications/notifications-controller-remove';
import { notificationsControllerRemoveChannel } from '../fn/notifications/notifications-controller-remove-channel';
import { NotificationsControllerRemoveChannel$Params } from '../fn/notifications/notifications-controller-remove-channel';
import { notificationsControllerUpdateChannel } from '../fn/notifications/notifications-controller-update-channel';
import { NotificationsControllerUpdateChannel$Params } from '../fn/notifications/notifications-controller-update-channel';

@Injectable({ providedIn: 'root' })
export class NotificationsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `notificationsControllerFindAll()` */
  static readonly NotificationsControllerFindAllPath = '/api/notifications';

  /**
   * Get all notifications (admin sees all, tenant sees own).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerFindAll$Response(params?: NotificationsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all notifications (admin sees all, tenant sees own).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerFindAll(params?: NotificationsControllerFindAll$Params, context?: HttpContext): Observable<void> {
    return this.notificationsControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsControllerCreate()` */
  static readonly NotificationsControllerCreatePath = '/api/notifications';

  /**
   * Create and send notification (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationsControllerCreate$Response(params: NotificationsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create and send notification (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationsControllerCreate(params: NotificationsControllerCreate$Params, context?: HttpContext): Observable<void> {
    return this.notificationsControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsControllerGetUnreadCount()` */
  static readonly NotificationsControllerGetUnreadCountPath = '/api/notifications/unread-count';

  /**
   * Get unread notification count.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerGetUnreadCount()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerGetUnreadCount$Response(params?: NotificationsControllerGetUnreadCount$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsControllerGetUnreadCount(this.http, this.rootUrl, params, context);
  }

  /**
   * Get unread notification count.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerGetUnreadCount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerGetUnreadCount(params?: NotificationsControllerGetUnreadCount$Params, context?: HttpContext): Observable<void> {
    return this.notificationsControllerGetUnreadCount$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsControllerMarkAllAsRead()` */
  static readonly NotificationsControllerMarkAllAsReadPath = '/api/notifications/mark-all-read';

  /**
   * Mark all notifications as read.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerMarkAllAsRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerMarkAllAsRead$Response(params?: NotificationsControllerMarkAllAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsControllerMarkAllAsRead(this.http, this.rootUrl, params, context);
  }

  /**
   * Mark all notifications as read.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerMarkAllAsRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerMarkAllAsRead(params?: NotificationsControllerMarkAllAsRead$Params, context?: HttpContext): Observable<void> {
    return this.notificationsControllerMarkAllAsRead$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsControllerFindOne()` */
  static readonly NotificationsControllerFindOnePath = '/api/notifications/{id}';

  /**
   * Get notification by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerFindOne$Response(params: NotificationsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get notification by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerFindOne(params: NotificationsControllerFindOne$Params, context?: HttpContext): Observable<void> {
    return this.notificationsControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsControllerRemove()` */
  static readonly NotificationsControllerRemovePath = '/api/notifications/{id}';

  /**
   * Delete notification.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerRemove$Response(params: NotificationsControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete notification.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerRemove(params: NotificationsControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.notificationsControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsControllerMarkAsRead()` */
  static readonly NotificationsControllerMarkAsReadPath = '/api/notifications/{id}/read';

  /**
   * Mark notification as read.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerMarkAsRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerMarkAsRead$Response(params: NotificationsControllerMarkAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsControllerMarkAsRead(this.http, this.rootUrl, params, context);
  }

  /**
   * Mark notification as read.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerMarkAsRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerMarkAsRead(params: NotificationsControllerMarkAsRead$Params, context?: HttpContext): Observable<void> {
    return this.notificationsControllerMarkAsRead$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsControllerCreateChannel()` */
  static readonly NotificationsControllerCreateChannelPath = '/api/notifications/channels';

  /**
   * Create notification channel (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerCreateChannel()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationsControllerCreateChannel$Response(params: NotificationsControllerCreateChannel$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsControllerCreateChannel(this.http, this.rootUrl, params, context);
  }

  /**
   * Create notification channel (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerCreateChannel$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationsControllerCreateChannel(params: NotificationsControllerCreateChannel$Params, context?: HttpContext): Observable<void> {
    return this.notificationsControllerCreateChannel$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsControllerFindAllChannels()` */
  static readonly NotificationsControllerFindAllChannelsPath = '/api/notifications/channels/all';

  /**
   * Get all notification channels (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerFindAllChannels()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerFindAllChannels$Response(params?: NotificationsControllerFindAllChannels$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsControllerFindAllChannels(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all notification channels (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerFindAllChannels$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerFindAllChannels(params?: NotificationsControllerFindAllChannels$Params, context?: HttpContext): Observable<void> {
    return this.notificationsControllerFindAllChannels$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsControllerFindOneChannel()` */
  static readonly NotificationsControllerFindOneChannelPath = '/api/notifications/channels/{id}';

  /**
   * Get notification channel by ID (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerFindOneChannel()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerFindOneChannel$Response(params: NotificationsControllerFindOneChannel$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsControllerFindOneChannel(this.http, this.rootUrl, params, context);
  }

  /**
   * Get notification channel by ID (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerFindOneChannel$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerFindOneChannel(params: NotificationsControllerFindOneChannel$Params, context?: HttpContext): Observable<void> {
    return this.notificationsControllerFindOneChannel$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsControllerRemoveChannel()` */
  static readonly NotificationsControllerRemoveChannelPath = '/api/notifications/channels/{id}';

  /**
   * Delete notification channel (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerRemoveChannel()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerRemoveChannel$Response(params: NotificationsControllerRemoveChannel$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsControllerRemoveChannel(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete notification channel (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerRemoveChannel$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerRemoveChannel(params: NotificationsControllerRemoveChannel$Params, context?: HttpContext): Observable<void> {
    return this.notificationsControllerRemoveChannel$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsControllerUpdateChannel()` */
  static readonly NotificationsControllerUpdateChannelPath = '/api/notifications/channels/{id}';

  /**
   * Update notification channel (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerUpdateChannel()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationsControllerUpdateChannel$Response(params: NotificationsControllerUpdateChannel$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsControllerUpdateChannel(this.http, this.rootUrl, params, context);
  }

  /**
   * Update notification channel (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerUpdateChannel$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationsControllerUpdateChannel(params: NotificationsControllerUpdateChannel$Params, context?: HttpContext): Observable<void> {
    return this.notificationsControllerUpdateChannel$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
