/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { OwnerDashboardResponseDto } from '../models/owner-dashboard-response-dto';
import { OwnerDetailResponseDto } from '../models/owner-detail-response-dto';
import { OwnerResponseDto } from '../models/owner-response-dto';
import { ownersControllerCreate } from '../fn/owners/owners-controller-create';
import { OwnersControllerCreate$Params } from '../fn/owners/owners-controller-create';
import { ownersControllerFindAll } from '../fn/owners/owners-controller-find-all';
import { OwnersControllerFindAll$Params } from '../fn/owners/owners-controller-find-all';
import { ownersControllerFindOne } from '../fn/owners/owners-controller-find-one';
import { OwnersControllerFindOne$Params } from '../fn/owners/owners-controller-find-one';
import { ownersControllerFindOneDetailed } from '../fn/owners/owners-controller-find-one-detailed';
import { OwnersControllerFindOneDetailed$Params } from '../fn/owners/owners-controller-find-one-detailed';
import { ownersControllerGetMonthlyReport } from '../fn/owners/owners-controller-get-monthly-report';
import { OwnersControllerGetMonthlyReport$Params } from '../fn/owners/owners-controller-get-monthly-report';
import { ownersControllerGetOwnerDashboard } from '../fn/owners/owners-controller-get-owner-dashboard';
import { OwnersControllerGetOwnerDashboard$Params } from '../fn/owners/owners-controller-get-owner-dashboard';
import { ownersControllerGetOwnerNodes } from '../fn/owners/owners-controller-get-owner-nodes';
import { OwnersControllerGetOwnerNodes$Params } from '../fn/owners/owners-controller-get-owner-nodes';
import { ownersControllerGetOwnerProjects } from '../fn/owners/owners-controller-get-owner-projects';
import { OwnersControllerGetOwnerProjects$Params } from '../fn/owners/owners-controller-get-owner-projects';
import { ownersControllerGetStatistics } from '../fn/owners/owners-controller-get-statistics';
import { OwnersControllerGetStatistics$Params } from '../fn/owners/owners-controller-get-statistics';
import { ownersControllerGetWidgetsData } from '../fn/owners/owners-controller-get-widgets-data';
import { OwnersControllerGetWidgetsData$Params } from '../fn/owners/owners-controller-get-widgets-data';
import { ownersControllerRemove } from '../fn/owners/owners-controller-remove';
import { OwnersControllerRemove$Params } from '../fn/owners/owners-controller-remove';
import { ownersControllerUpdate } from '../fn/owners/owners-controller-update';
import { OwnersControllerUpdate$Params } from '../fn/owners/owners-controller-update';
import { OwnerStatisticsResponseDto } from '../models/owner-statistics-response-dto';
import { OwnerWidgetsResponseDto } from '../models/owner-widgets-response-dto';
import { PaginatedResponseDto } from '../models/paginated-response-dto';


/**
 * Owner management and statistics
 */
@Injectable({ providedIn: 'root' })
export class OwnersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `ownersControllerFindAll()` */
  static readonly OwnersControllerFindAllPath = '/api/owners';

  /**
   * Get all owners with pagination.
   *
   * Retrieves a paginated list of owners with advanced filtering, searching and sorting
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ownersControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerFindAll$Response(params?: OwnersControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedResponseDto>> {
    return ownersControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all owners with pagination.
   *
   * Retrieves a paginated list of owners with advanced filtering, searching and sorting
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ownersControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerFindAll(params?: OwnersControllerFindAll$Params, context?: HttpContext): Observable<PaginatedResponseDto> {
    return this.ownersControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<PaginatedResponseDto>): PaginatedResponseDto => r.body)
    );
  }

  /** Path part for operation `ownersControllerCreate()` */
  static readonly OwnersControllerCreatePath = '/api/owners';

  /**
   * Create a new owner.
   *
   * Creates a new owner entity with the provided data
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ownersControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  ownersControllerCreate$Response(params: OwnersControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<OwnerResponseDto>> {
    return ownersControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new owner.
   *
   * Creates a new owner entity with the provided data
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ownersControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  ownersControllerCreate(params: OwnersControllerCreate$Params, context?: HttpContext): Observable<OwnerResponseDto> {
    return this.ownersControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<OwnerResponseDto>): OwnerResponseDto => r.body)
    );
  }

  /** Path part for operation `ownersControllerFindOne()` */
  static readonly OwnersControllerFindOnePath = '/api/owners/{id}';

  /**
   * Get owner by ID (basic info).
   *
   * Retrieves basic owner information without nested relations
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ownersControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerFindOne$Response(params: OwnersControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<OwnerResponseDto>> {
    return ownersControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get owner by ID (basic info).
   *
   * Retrieves basic owner information without nested relations
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ownersControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerFindOne(params: OwnersControllerFindOne$Params, context?: HttpContext): Observable<OwnerResponseDto> {
    return this.ownersControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<OwnerResponseDto>): OwnerResponseDto => r.body)
    );
  }

  /** Path part for operation `ownersControllerRemove()` */
  static readonly OwnersControllerRemovePath = '/api/owners/{id}';

  /**
   * Delete owner.
   *
   * Permanently deletes an owner and all related data (cascade)
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ownersControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerRemove$Response(params: OwnersControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return ownersControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete owner.
   *
   * Permanently deletes an owner and all related data (cascade)
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ownersControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerRemove(params: OwnersControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.ownersControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `ownersControllerUpdate()` */
  static readonly OwnersControllerUpdatePath = '/api/owners/{id}';

  /**
   * Update owner.
   *
   * Updates an existing owner with the provided data
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ownersControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  ownersControllerUpdate$Response(params: OwnersControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<OwnerResponseDto>> {
    return ownersControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Update owner.
   *
   * Updates an existing owner with the provided data
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ownersControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  ownersControllerUpdate(params: OwnersControllerUpdate$Params, context?: HttpContext): Observable<OwnerResponseDto> {
    return this.ownersControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<OwnerResponseDto>): OwnerResponseDto => r.body)
    );
  }

  /** Path part for operation `ownersControllerFindOneDetailed()` */
  static readonly OwnersControllerFindOneDetailedPath = '/api/owners/{id}/detail';

  /**
   * Get owner with full details.
   *
   * Retrieves owner with all nested relations (projects, node assignments, statistics)
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ownersControllerFindOneDetailed()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerFindOneDetailed$Response(params: OwnersControllerFindOneDetailed$Params, context?: HttpContext): Observable<StrictHttpResponse<OwnerDetailResponseDto>> {
    return ownersControllerFindOneDetailed(this.http, this.rootUrl, params, context);
  }

  /**
   * Get owner with full details.
   *
   * Retrieves owner with all nested relations (projects, node assignments, statistics)
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ownersControllerFindOneDetailed$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerFindOneDetailed(params: OwnersControllerFindOneDetailed$Params, context?: HttpContext): Observable<OwnerDetailResponseDto> {
    return this.ownersControllerFindOneDetailed$Response(params, context).pipe(
      map((r: StrictHttpResponse<OwnerDetailResponseDto>): OwnerDetailResponseDto => r.body)
    );
  }

  /** Path part for operation `ownersControllerGetOwnerProjects()` */
  static readonly OwnersControllerGetOwnerProjectsPath = '/api/owners/{id}/projects';

  /**
   * Get all projects for an owner.
   *
   * Retrieves all projects belonging to the specified owner with node counts
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ownersControllerGetOwnerProjects()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerGetOwnerProjects$Response(params: OwnersControllerGetOwnerProjects$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return ownersControllerGetOwnerProjects(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all projects for an owner.
   *
   * Retrieves all projects belonging to the specified owner with node counts
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ownersControllerGetOwnerProjects$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerGetOwnerProjects(params: OwnersControllerGetOwnerProjects$Params, context?: HttpContext): Observable<void> {
    return this.ownersControllerGetOwnerProjects$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `ownersControllerGetOwnerNodes()` */
  static readonly OwnersControllerGetOwnerNodesPath = '/api/owners/{id}/nodes';

  /**
   * Get all nodes for an owner.
   *
   * Retrieves all nodes from all projects belonging to the owner
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ownersControllerGetOwnerNodes()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerGetOwnerNodes$Response(params: OwnersControllerGetOwnerNodes$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return ownersControllerGetOwnerNodes(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all nodes for an owner.
   *
   * Retrieves all nodes from all projects belonging to the owner
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ownersControllerGetOwnerNodes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerGetOwnerNodes(params: OwnersControllerGetOwnerNodes$Params, context?: HttpContext): Observable<void> {
    return this.ownersControllerGetOwnerNodes$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `ownersControllerGetStatistics()` */
  static readonly OwnersControllerGetStatisticsPath = '/api/owners/statistics/overview';

  /**
   * Get aggregated statistics.
   *
   * Retrieves comprehensive statistics across all owners (industry distribution, SLA levels, top owners)
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ownersControllerGetStatistics()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerGetStatistics$Response(params?: OwnersControllerGetStatistics$Params, context?: HttpContext): Observable<StrictHttpResponse<OwnerStatisticsResponseDto>> {
    return ownersControllerGetStatistics(this.http, this.rootUrl, params, context);
  }

  /**
   * Get aggregated statistics.
   *
   * Retrieves comprehensive statistics across all owners (industry distribution, SLA levels, top owners)
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ownersControllerGetStatistics$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerGetStatistics(params?: OwnersControllerGetStatistics$Params, context?: HttpContext): Observable<OwnerStatisticsResponseDto> {
    return this.ownersControllerGetStatistics$Response(params, context).pipe(
      map((r: StrictHttpResponse<OwnerStatisticsResponseDto>): OwnerStatisticsResponseDto => r.body)
    );
  }

  /** Path part for operation `ownersControllerGetOwnerDashboard()` */
  static readonly OwnersControllerGetOwnerDashboardPath = '/api/owners/{id}/dashboard';

  /**
   * Get dashboard data for owner.
   *
   * Retrieves dashboard-ready data including summary, recent projects, alerts, and performance metrics
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ownersControllerGetOwnerDashboard()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerGetOwnerDashboard$Response(params: OwnersControllerGetOwnerDashboard$Params, context?: HttpContext): Observable<StrictHttpResponse<OwnerDashboardResponseDto>> {
    return ownersControllerGetOwnerDashboard(this.http, this.rootUrl, params, context);
  }

  /**
   * Get dashboard data for owner.
   *
   * Retrieves dashboard-ready data including summary, recent projects, alerts, and performance metrics
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ownersControllerGetOwnerDashboard$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerGetOwnerDashboard(params: OwnersControllerGetOwnerDashboard$Params, context?: HttpContext): Observable<OwnerDashboardResponseDto> {
    return this.ownersControllerGetOwnerDashboard$Response(params, context).pipe(
      map((r: StrictHttpResponse<OwnerDashboardResponseDto>): OwnerDashboardResponseDto => r.body)
    );
  }

  /** Path part for operation `ownersControllerGetMonthlyReport()` */
  static readonly OwnersControllerGetMonthlyReportPath = '/api/owners/{id}/reports/monthly';

  /**
   * Get monthly report for owner.
   *
   * Generates a detailed monthly report with metrics, alerts, and compliance data
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ownersControllerGetMonthlyReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerGetMonthlyReport$Response(params: OwnersControllerGetMonthlyReport$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return ownersControllerGetMonthlyReport(this.http, this.rootUrl, params, context);
  }

  /**
   * Get monthly report for owner.
   *
   * Generates a detailed monthly report with metrics, alerts, and compliance data
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ownersControllerGetMonthlyReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerGetMonthlyReport(params: OwnersControllerGetMonthlyReport$Params, context?: HttpContext): Observable<void> {
    return this.ownersControllerGetMonthlyReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `ownersControllerGetWidgetsData()` */
  static readonly OwnersControllerGetWidgetsDataPath = '/api/owners/reports/widgets';

  /**
   * Get data for dashboard widgets.
   *
   * Retrieves aggregated data optimized for dashboard widgets (charts, gauges, counters)
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ownersControllerGetWidgetsData()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerGetWidgetsData$Response(params?: OwnersControllerGetWidgetsData$Params, context?: HttpContext): Observable<StrictHttpResponse<OwnerWidgetsResponseDto>> {
    return ownersControllerGetWidgetsData(this.http, this.rootUrl, params, context);
  }

  /**
   * Get data for dashboard widgets.
   *
   * Retrieves aggregated data optimized for dashboard widgets (charts, gauges, counters)
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ownersControllerGetWidgetsData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ownersControllerGetWidgetsData(params?: OwnersControllerGetWidgetsData$Params, context?: HttpContext): Observable<OwnerWidgetsResponseDto> {
    return this.ownersControllerGetWidgetsData$Response(params, context).pipe(
      map((r: StrictHttpResponse<OwnerWidgetsResponseDto>): OwnerWidgetsResponseDto => r.body)
    );
  }

}
