/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ProjectDetailedResponseDto } from '../models/project-detailed-response-dto';
import { ProjectResponseDto } from '../models/project-response-dto';
import { projectsControllerCreate } from '../fn/projects/projects-controller-create';
import { ProjectsControllerCreate$Params } from '../fn/projects/projects-controller-create';
import { projectsControllerFindAll } from '../fn/projects/projects-controller-find-all';
import { ProjectsControllerFindAll$Params } from '../fn/projects/projects-controller-find-all';
import { projectsControllerFindOne } from '../fn/projects/projects-controller-find-one';
import { ProjectsControllerFindOne$Params } from '../fn/projects/projects-controller-find-one';
import { projectsControllerFindOneDetailed } from '../fn/projects/projects-controller-find-one-detailed';
import { ProjectsControllerFindOneDetailed$Params } from '../fn/projects/projects-controller-find-one-detailed';
import { projectsControllerRemove } from '../fn/projects/projects-controller-remove';
import { ProjectsControllerRemove$Params } from '../fn/projects/projects-controller-remove';
import { projectsControllerUpdate } from '../fn/projects/projects-controller-update';
import { ProjectsControllerUpdate$Params } from '../fn/projects/projects-controller-update';


/**
 * Project management endpoints
 */
@Injectable({ providedIn: 'root' })
export class ProjectsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `projectsControllerFindAll()` */
  static readonly ProjectsControllerFindAllPath = '/api/projects';

  /**
   * Get all projects with filters and pagination.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectsControllerFindAll$Response(params?: ProjectsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return projectsControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all projects with filters and pagination.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectsControllerFindAll(params?: ProjectsControllerFindAll$Params, context?: HttpContext): Observable<void> {
    return this.projectsControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `projectsControllerCreate()` */
  static readonly ProjectsControllerCreatePath = '/api/projects';

  /**
   * Create a new project.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectsControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  projectsControllerCreate$Response(params: ProjectsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectResponseDto>> {
    return projectsControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new project.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectsControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  projectsControllerCreate(params: ProjectsControllerCreate$Params, context?: HttpContext): Observable<ProjectResponseDto> {
    return this.projectsControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectResponseDto>): ProjectResponseDto => r.body)
    );
  }

  /** Path part for operation `projectsControllerFindOne()` */
  static readonly ProjectsControllerFindOnePath = '/api/projects/{id}';

  /**
   * Get project by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectsControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectsControllerFindOne$Response(params: ProjectsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectResponseDto>> {
    return projectsControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get project by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectsControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectsControllerFindOne(params: ProjectsControllerFindOne$Params, context?: HttpContext): Observable<ProjectResponseDto> {
    return this.projectsControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectResponseDto>): ProjectResponseDto => r.body)
    );
  }

  /** Path part for operation `projectsControllerRemove()` */
  static readonly ProjectsControllerRemovePath = '/api/projects/{id}';

  /**
   * Delete project.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectsControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectsControllerRemove$Response(params: ProjectsControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return projectsControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete project.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectsControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectsControllerRemove(params: ProjectsControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.projectsControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `projectsControllerUpdate()` */
  static readonly ProjectsControllerUpdatePath = '/api/projects/{id}';

  /**
   * Update project.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectsControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  projectsControllerUpdate$Response(params: ProjectsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectResponseDto>> {
    return projectsControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Update project.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectsControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  projectsControllerUpdate(params: ProjectsControllerUpdate$Params, context?: HttpContext): Observable<ProjectResponseDto> {
    return this.projectsControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectResponseDto>): ProjectResponseDto => r.body)
    );
  }

  /** Path part for operation `projectsControllerFindOneDetailed()` */
  static readonly ProjectsControllerFindOneDetailedPath = '/api/projects/{id}/detailed';

  /**
   * Get project with detailed information.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectsControllerFindOneDetailed()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectsControllerFindOneDetailed$Response(params: ProjectsControllerFindOneDetailed$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectDetailedResponseDto>> {
    return projectsControllerFindOneDetailed(this.http, this.rootUrl, params, context);
  }

  /**
   * Get project with detailed information.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectsControllerFindOneDetailed$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectsControllerFindOneDetailed(params: ProjectsControllerFindOneDetailed$Params, context?: HttpContext): Observable<ProjectDetailedResponseDto> {
    return this.projectsControllerFindOneDetailed$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectDetailedResponseDto>): ProjectDetailedResponseDto => r.body)
    );
  }

}
