/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { reportControllerCreateTemplate } from '../fn/reports/report-controller-create-template';
import { ReportControllerCreateTemplate$Params } from '../fn/reports/report-controller-create-template';
import { reportControllerDeleteTemplate } from '../fn/reports/report-controller-delete-template';
import { ReportControllerDeleteTemplate$Params } from '../fn/reports/report-controller-delete-template';
import { reportControllerExportFromTemplate } from '../fn/reports/report-controller-export-from-template';
import { ReportControllerExportFromTemplate$Params } from '../fn/reports/report-controller-export-from-template';
import { reportControllerExportXlsx } from '../fn/reports/report-controller-export-xlsx';
import { ReportControllerExportXlsx$Params } from '../fn/reports/report-controller-export-xlsx';
import { reportControllerGeneratePreview } from '../fn/reports/report-controller-generate-preview';
import { ReportControllerGeneratePreview$Params } from '../fn/reports/report-controller-generate-preview';
import { reportControllerGetTemplate } from '../fn/reports/report-controller-get-template';
import { ReportControllerGetTemplate$Params } from '../fn/reports/report-controller-get-template';
import { reportControllerGetTemplates } from '../fn/reports/report-controller-get-templates';
import { ReportControllerGetTemplates$Params } from '../fn/reports/report-controller-get-templates';
import { reportControllerPreviewFromTemplate } from '../fn/reports/report-controller-preview-from-template';
import { ReportControllerPreviewFromTemplate$Params } from '../fn/reports/report-controller-preview-from-template';
import { reportControllerUpdateTemplate } from '../fn/reports/report-controller-update-template';
import { ReportControllerUpdateTemplate$Params } from '../fn/reports/report-controller-update-template';
import { ReportPreviewResponseDto } from '../models/report-preview-response-dto';


/**
 * Custom reports and analytics
 */
@Injectable({ providedIn: 'root' })
export class ReportsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `reportControllerGeneratePreview()` */
  static readonly ReportControllerGeneratePreviewPath = '/api/reports/preview';

  /**
   * Generate report preview with chart data.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportControllerGeneratePreview()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportControllerGeneratePreview$Response(params: ReportControllerGeneratePreview$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportPreviewResponseDto>> {
    return reportControllerGeneratePreview(this.http, this.rootUrl, params, context);
  }

  /**
   * Generate report preview with chart data.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportControllerGeneratePreview$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportControllerGeneratePreview(params: ReportControllerGeneratePreview$Params, context?: HttpContext): Observable<ReportPreviewResponseDto> {
    return this.reportControllerGeneratePreview$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReportPreviewResponseDto>): ReportPreviewResponseDto => r.body)
    );
  }

  /** Path part for operation `reportControllerExportXlsx()` */
  static readonly ReportControllerExportXlsxPath = '/api/reports/export/xlsx';

  /**
   * Export report data to XLSX file.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportControllerExportXlsx()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportControllerExportXlsx$Response(params: ReportControllerExportXlsx$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return reportControllerExportXlsx(this.http, this.rootUrl, params, context);
  }

  /**
   * Export report data to XLSX file.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportControllerExportXlsx$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportControllerExportXlsx(params: ReportControllerExportXlsx$Params, context?: HttpContext): Observable<any> {
    return this.reportControllerExportXlsx$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }

  /** Path part for operation `reportControllerGetTemplates()` */
  static readonly ReportControllerGetTemplatesPath = '/api/reports/templates';

  /**
   * Get all report templates for current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportControllerGetTemplates()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportControllerGetTemplates$Response(params?: ReportControllerGetTemplates$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return reportControllerGetTemplates(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all report templates for current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportControllerGetTemplates$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportControllerGetTemplates(params?: ReportControllerGetTemplates$Params, context?: HttpContext): Observable<void> {
    return this.reportControllerGetTemplates$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `reportControllerCreateTemplate()` */
  static readonly ReportControllerCreateTemplatePath = '/api/reports/templates';

  /**
   * Create new report template.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportControllerCreateTemplate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportControllerCreateTemplate$Response(params: ReportControllerCreateTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return reportControllerCreateTemplate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create new report template.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportControllerCreateTemplate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportControllerCreateTemplate(params: ReportControllerCreateTemplate$Params, context?: HttpContext): Observable<void> {
    return this.reportControllerCreateTemplate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `reportControllerGetTemplate()` */
  static readonly ReportControllerGetTemplatePath = '/api/reports/templates/{id}';

  /**
   * Get report template by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportControllerGetTemplate()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportControllerGetTemplate$Response(params: ReportControllerGetTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return reportControllerGetTemplate(this.http, this.rootUrl, params, context);
  }

  /**
   * Get report template by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportControllerGetTemplate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportControllerGetTemplate(params: ReportControllerGetTemplate$Params, context?: HttpContext): Observable<void> {
    return this.reportControllerGetTemplate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `reportControllerUpdateTemplate()` */
  static readonly ReportControllerUpdateTemplatePath = '/api/reports/templates/{id}';

  /**
   * Update report template.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportControllerUpdateTemplate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportControllerUpdateTemplate$Response(params: ReportControllerUpdateTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return reportControllerUpdateTemplate(this.http, this.rootUrl, params, context);
  }

  /**
   * Update report template.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportControllerUpdateTemplate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportControllerUpdateTemplate(params: ReportControllerUpdateTemplate$Params, context?: HttpContext): Observable<void> {
    return this.reportControllerUpdateTemplate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `reportControllerDeleteTemplate()` */
  static readonly ReportControllerDeleteTemplatePath = '/api/reports/templates/{id}';

  /**
   * Delete report template.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportControllerDeleteTemplate()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportControllerDeleteTemplate$Response(params: ReportControllerDeleteTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return reportControllerDeleteTemplate(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete report template.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportControllerDeleteTemplate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportControllerDeleteTemplate(params: ReportControllerDeleteTemplate$Params, context?: HttpContext): Observable<void> {
    return this.reportControllerDeleteTemplate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `reportControllerPreviewFromTemplate()` */
  static readonly ReportControllerPreviewFromTemplatePath = '/api/reports/templates/{id}/preview';

  /**
   * Generate report preview from saved template.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportControllerPreviewFromTemplate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportControllerPreviewFromTemplate$Response(params: ReportControllerPreviewFromTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return reportControllerPreviewFromTemplate(this.http, this.rootUrl, params, context);
  }

  /**
   * Generate report preview from saved template.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportControllerPreviewFromTemplate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportControllerPreviewFromTemplate(params: ReportControllerPreviewFromTemplate$Params, context?: HttpContext): Observable<void> {
    return this.reportControllerPreviewFromTemplate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `reportControllerExportFromTemplate()` */
  static readonly ReportControllerExportFromTemplatePath = '/api/reports/templates/{id}/export/xlsx';

  /**
   * Export XLSX from saved template.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportControllerExportFromTemplate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportControllerExportFromTemplate$Response(params: ReportControllerExportFromTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return reportControllerExportFromTemplate(this.http, this.rootUrl, params, context);
  }

  /**
   * Export XLSX from saved template.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportControllerExportFromTemplate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportControllerExportFromTemplate(params: ReportControllerExportFromTemplate$Params, context?: HttpContext): Observable<void> {
    return this.reportControllerExportFromTemplate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
