/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { searchControllerSearch } from '../fn/search/search-controller-search';
import { SearchControllerSearch$Params } from '../fn/search/search-controller-search';
import { SearchResponseDto } from '../models/search-response-dto';

@Injectable({ providedIn: 'root' })
export class SearchService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `searchControllerSearch()` */
  static readonly SearchControllerSearchPath = '/api/search';

  /**
   * Global search across nodes, devices, alerts, projects, and owners.
   *
   * Searches across multiple entities with a single query. Results are filtered based on user permissions.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchControllerSearch()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerSearch$Response(params: SearchControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<SearchResponseDto>> {
    return searchControllerSearch(this.http, this.rootUrl, params, context);
  }

  /**
   * Global search across nodes, devices, alerts, projects, and owners.
   *
   * Searches across multiple entities with a single query. Results are filtered based on user permissions.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchControllerSearch$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerSearch(params: SearchControllerSearch$Params, context?: HttpContext): Observable<SearchResponseDto> {
    return this.searchControllerSearch$Response(params, context).pipe(
      map((r: StrictHttpResponse<SearchResponseDto>): SearchResponseDto => r.body)
    );
  }

}
