/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { SensorDetailedResponseDto } from '../models/sensor-detailed-response-dto';
import { SensorResponseDto } from '../models/sensor-response-dto';
import { sensorsControllerCreate } from '../fn/sensors/sensors-controller-create';
import { SensorsControllerCreate$Params } from '../fn/sensors/sensors-controller-create';
import { sensorsControllerFindAll } from '../fn/sensors/sensors-controller-find-all';
import { SensorsControllerFindAll$Params } from '../fn/sensors/sensors-controller-find-all';
import { sensorsControllerFindOne } from '../fn/sensors/sensors-controller-find-one';
import { SensorsControllerFindOne$Params } from '../fn/sensors/sensors-controller-find-one';
import { sensorsControllerFindOneDetailed } from '../fn/sensors/sensors-controller-find-one-detailed';
import { SensorsControllerFindOneDetailed$Params } from '../fn/sensors/sensors-controller-find-one-detailed';
import { sensorsControllerGetChannels } from '../fn/sensors/sensors-controller-get-channels';
import { SensorsControllerGetChannels$Params } from '../fn/sensors/sensors-controller-get-channels';
import { sensorsControllerGetDashboard } from '../fn/sensors/sensors-controller-get-dashboard';
import { SensorsControllerGetDashboard$Params } from '../fn/sensors/sensors-controller-get-dashboard';
import { sensorsControllerGetStatistics } from '../fn/sensors/sensors-controller-get-statistics';
import { SensorsControllerGetStatistics$Params } from '../fn/sensors/sensors-controller-get-statistics';
import { sensorsControllerRemove } from '../fn/sensors/sensors-controller-remove';
import { SensorsControllerRemove$Params } from '../fn/sensors/sensors-controller-remove';
import { sensorsControllerUpdate } from '../fn/sensors/sensors-controller-update';
import { SensorsControllerUpdate$Params } from '../fn/sensors/sensors-controller-update';


/**
 * Sensor configuration and data
 */
@Injectable({ providedIn: 'root' })
export class SensorsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `sensorsControllerFindAll()` */
  static readonly SensorsControllerFindAllPath = '/api/sensors';

  /**
   * Get all sensors.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sensorsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  sensorsControllerFindAll$Response(params?: SensorsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sensorsControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all sensors.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sensorsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sensorsControllerFindAll(params?: SensorsControllerFindAll$Params, context?: HttpContext): Observable<void> {
    return this.sensorsControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sensorsControllerCreate()` */
  static readonly SensorsControllerCreatePath = '/api/sensors';

  /**
   * Create a new sensor.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sensorsControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sensorsControllerCreate$Response(params: SensorsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<SensorResponseDto>> {
    return sensorsControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new sensor.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sensorsControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sensorsControllerCreate(params: SensorsControllerCreate$Params, context?: HttpContext): Observable<SensorResponseDto> {
    return this.sensorsControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<SensorResponseDto>): SensorResponseDto => r.body)
    );
  }

  /** Path part for operation `sensorsControllerGetStatistics()` */
  static readonly SensorsControllerGetStatisticsPath = '/api/sensors/statistics/overview';

  /**
   * Get aggregated sensor statistics.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sensorsControllerGetStatistics()` instead.
   *
   * This method doesn't expect any request body.
   */
  sensorsControllerGetStatistics$Response(params?: SensorsControllerGetStatistics$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sensorsControllerGetStatistics(this.http, this.rootUrl, params, context);
  }

  /**
   * Get aggregated sensor statistics.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sensorsControllerGetStatistics$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sensorsControllerGetStatistics(params?: SensorsControllerGetStatistics$Params, context?: HttpContext): Observable<void> {
    return this.sensorsControllerGetStatistics$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sensorsControllerFindOneDetailed()` */
  static readonly SensorsControllerFindOneDetailedPath = '/api/sensors/{id}/detailed';

  /**
   * Get sensor with channels and calibration status.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sensorsControllerFindOneDetailed()` instead.
   *
   * This method doesn't expect any request body.
   */
  sensorsControllerFindOneDetailed$Response(params: SensorsControllerFindOneDetailed$Params, context?: HttpContext): Observable<StrictHttpResponse<SensorDetailedResponseDto>> {
    return sensorsControllerFindOneDetailed(this.http, this.rootUrl, params, context);
  }

  /**
   * Get sensor with channels and calibration status.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sensorsControllerFindOneDetailed$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sensorsControllerFindOneDetailed(params: SensorsControllerFindOneDetailed$Params, context?: HttpContext): Observable<SensorDetailedResponseDto> {
    return this.sensorsControllerFindOneDetailed$Response(params, context).pipe(
      map((r: StrictHttpResponse<SensorDetailedResponseDto>): SensorDetailedResponseDto => r.body)
    );
  }

  /** Path part for operation `sensorsControllerGetDashboard()` */
  static readonly SensorsControllerGetDashboardPath = '/api/sensors/{id}/dashboard';

  /**
   * Get sensor dashboard data with health status.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sensorsControllerGetDashboard()` instead.
   *
   * This method doesn't expect any request body.
   */
  sensorsControllerGetDashboard$Response(params: SensorsControllerGetDashboard$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sensorsControllerGetDashboard(this.http, this.rootUrl, params, context);
  }

  /**
   * Get sensor dashboard data with health status.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sensorsControllerGetDashboard$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sensorsControllerGetDashboard(params: SensorsControllerGetDashboard$Params, context?: HttpContext): Observable<void> {
    return this.sensorsControllerGetDashboard$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sensorsControllerGetChannels()` */
  static readonly SensorsControllerGetChannelsPath = '/api/sensors/{id}/channels';

  /**
   * Get all channels for a sensor.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sensorsControllerGetChannels()` instead.
   *
   * This method doesn't expect any request body.
   */
  sensorsControllerGetChannels$Response(params: SensorsControllerGetChannels$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sensorsControllerGetChannels(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all channels for a sensor.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sensorsControllerGetChannels$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sensorsControllerGetChannels(params: SensorsControllerGetChannels$Params, context?: HttpContext): Observable<void> {
    return this.sensorsControllerGetChannels$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sensorsControllerFindOne()` */
  static readonly SensorsControllerFindOnePath = '/api/sensors/{id}';

  /**
   * Get sensor by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sensorsControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  sensorsControllerFindOne$Response(params: SensorsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<SensorResponseDto>> {
    return sensorsControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get sensor by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sensorsControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sensorsControllerFindOne(params: SensorsControllerFindOne$Params, context?: HttpContext): Observable<SensorResponseDto> {
    return this.sensorsControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<SensorResponseDto>): SensorResponseDto => r.body)
    );
  }

  /** Path part for operation `sensorsControllerRemove()` */
  static readonly SensorsControllerRemovePath = '/api/sensors/{id}';

  /**
   * Delete sensor.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sensorsControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  sensorsControllerRemove$Response(params: SensorsControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sensorsControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete sensor.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sensorsControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sensorsControllerRemove(params: SensorsControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.sensorsControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sensorsControllerUpdate()` */
  static readonly SensorsControllerUpdatePath = '/api/sensors/{id}';

  /**
   * Update sensor.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sensorsControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sensorsControllerUpdate$Response(params: SensorsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<SensorResponseDto>> {
    return sensorsControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Update sensor.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sensorsControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sensorsControllerUpdate(params: SensorsControllerUpdate$Params, context?: HttpContext): Observable<SensorResponseDto> {
    return this.sensorsControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<SensorResponseDto>): SensorResponseDto => r.body)
    );
  }

}
