/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { UserDashboardDetailedResponseDto } from '../models/user-dashboard-detailed-response-dto';
import { UserDashboardResponseDto } from '../models/user-dashboard-response-dto';
import { userDashboardsControllerCreate } from '../fn/user-dashboards/user-dashboards-controller-create';
import { UserDashboardsControllerCreate$Params } from '../fn/user-dashboards/user-dashboards-controller-create';
import { userDashboardsControllerFindAll } from '../fn/user-dashboards/user-dashboards-controller-find-all';
import { UserDashboardsControllerFindAll$Params } from '../fn/user-dashboards/user-dashboards-controller-find-all';
import { userDashboardsControllerFindOne } from '../fn/user-dashboards/user-dashboards-controller-find-one';
import { UserDashboardsControllerFindOne$Params } from '../fn/user-dashboards/user-dashboards-controller-find-one';
import { userDashboardsControllerFindOneDetailed } from '../fn/user-dashboards/user-dashboards-controller-find-one-detailed';
import { UserDashboardsControllerFindOneDetailed$Params } from '../fn/user-dashboards/user-dashboards-controller-find-one-detailed';
import { userDashboardsControllerRemove } from '../fn/user-dashboards/user-dashboards-controller-remove';
import { UserDashboardsControllerRemove$Params } from '../fn/user-dashboards/user-dashboards-controller-remove';
import { userDashboardsControllerUpdate } from '../fn/user-dashboards/user-dashboards-controller-update';
import { UserDashboardsControllerUpdate$Params } from '../fn/user-dashboards/user-dashboards-controller-update';

@Injectable({ providedIn: 'root' })
export class UserDashboardsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `userDashboardsControllerFindAll()` */
  static readonly UserDashboardsControllerFindAllPath = '/api/user-dashboards';

  /**
   * Get all dashboards.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userDashboardsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  userDashboardsControllerFindAll$Response(params?: UserDashboardsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return userDashboardsControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all dashboards.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userDashboardsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userDashboardsControllerFindAll(params?: UserDashboardsControllerFindAll$Params, context?: HttpContext): Observable<void> {
    return this.userDashboardsControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `userDashboardsControllerCreate()` */
  static readonly UserDashboardsControllerCreatePath = '/api/user-dashboards';

  /**
   * Create a new dashboard.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userDashboardsControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userDashboardsControllerCreate$Response(params: UserDashboardsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDashboardResponseDto>> {
    return userDashboardsControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new dashboard.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userDashboardsControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userDashboardsControllerCreate(params: UserDashboardsControllerCreate$Params, context?: HttpContext): Observable<UserDashboardResponseDto> {
    return this.userDashboardsControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDashboardResponseDto>): UserDashboardResponseDto => r.body)
    );
  }

  /** Path part for operation `userDashboardsControllerFindOne()` */
  static readonly UserDashboardsControllerFindOnePath = '/api/user-dashboards/{id}';

  /**
   * Get dashboard by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userDashboardsControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  userDashboardsControllerFindOne$Response(params: UserDashboardsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDashboardResponseDto>> {
    return userDashboardsControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get dashboard by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userDashboardsControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userDashboardsControllerFindOne(params: UserDashboardsControllerFindOne$Params, context?: HttpContext): Observable<UserDashboardResponseDto> {
    return this.userDashboardsControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDashboardResponseDto>): UserDashboardResponseDto => r.body)
    );
  }

  /** Path part for operation `userDashboardsControllerRemove()` */
  static readonly UserDashboardsControllerRemovePath = '/api/user-dashboards/{id}';

  /**
   * Delete dashboard.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userDashboardsControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  userDashboardsControllerRemove$Response(params: UserDashboardsControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return userDashboardsControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete dashboard.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userDashboardsControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userDashboardsControllerRemove(params: UserDashboardsControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.userDashboardsControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `userDashboardsControllerUpdate()` */
  static readonly UserDashboardsControllerUpdatePath = '/api/user-dashboards/{id}';

  /**
   * Update dashboard.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userDashboardsControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userDashboardsControllerUpdate$Response(params: UserDashboardsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDashboardResponseDto>> {
    return userDashboardsControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Update dashboard.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userDashboardsControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userDashboardsControllerUpdate(params: UserDashboardsControllerUpdate$Params, context?: HttpContext): Observable<UserDashboardResponseDto> {
    return this.userDashboardsControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDashboardResponseDto>): UserDashboardResponseDto => r.body)
    );
  }

  /** Path part for operation `userDashboardsControllerFindOneDetailed()` */
  static readonly UserDashboardsControllerFindOneDetailedPath = '/api/user-dashboards/{id}/detailed';

  /**
   * Get dashboard with widgets.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userDashboardsControllerFindOneDetailed()` instead.
   *
   * This method doesn't expect any request body.
   */
  userDashboardsControllerFindOneDetailed$Response(params: UserDashboardsControllerFindOneDetailed$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDashboardDetailedResponseDto>> {
    return userDashboardsControllerFindOneDetailed(this.http, this.rootUrl, params, context);
  }

  /**
   * Get dashboard with widgets.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userDashboardsControllerFindOneDetailed$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userDashboardsControllerFindOneDetailed(params: UserDashboardsControllerFindOneDetailed$Params, context?: HttpContext): Observable<UserDashboardDetailedResponseDto> {
    return this.userDashboardsControllerFindOneDetailed$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDashboardDetailedResponseDto>): UserDashboardDetailedResponseDto => r.body)
    );
  }

}
