/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ParsedResultResponseDto } from '../models/parsed-result-response-dto';
import { uploadControllerGetParsedResult } from '../fn/web-gis-upload/upload-controller-get-parsed-result';
import { UploadControllerGetParsedResult$Params } from '../fn/web-gis-upload/upload-controller-get-parsed-result';
import { uploadControllerGetStatus } from '../fn/web-gis-upload/upload-controller-get-status';
import { UploadControllerGetStatus$Params } from '../fn/web-gis-upload/upload-controller-get-status';
import { uploadControllerRemove } from '../fn/web-gis-upload/upload-controller-remove';
import { UploadControllerRemove$Params } from '../fn/web-gis-upload/upload-controller-remove';
import { uploadControllerSubmitMapping } from '../fn/web-gis-upload/upload-controller-submit-mapping';
import { UploadControllerSubmitMapping$Params } from '../fn/web-gis-upload/upload-controller-submit-mapping';
import { uploadControllerUpload } from '../fn/web-gis-upload/upload-controller-upload';
import { UploadControllerUpload$Params } from '../fn/web-gis-upload/upload-controller-upload';
import { UploadStatusResponseDto } from '../models/upload-status-response-dto';

@Injectable({ providedIn: 'root' })
export class WebGisUploadService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `uploadControllerUpload()` */
  static readonly UploadControllerUploadPath = '/api/webgis/upload';

  /**
   * Upload spatial data file.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadControllerUpload()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadControllerUpload$Response(params: UploadControllerUpload$Params, context?: HttpContext): Observable<StrictHttpResponse<UploadStatusResponseDto>> {
    return uploadControllerUpload(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload spatial data file.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadControllerUpload$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadControllerUpload(params: UploadControllerUpload$Params, context?: HttpContext): Observable<UploadStatusResponseDto> {
    return this.uploadControllerUpload$Response(params, context).pipe(
      map((r: StrictHttpResponse<UploadStatusResponseDto>): UploadStatusResponseDto => r.body)
    );
  }

  /** Path part for operation `uploadControllerGetStatus()` */
  static readonly UploadControllerGetStatusPath = '/api/webgis/upload/{id}/status';

  /**
   * Get upload status.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadControllerGetStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  uploadControllerGetStatus$Response(params: UploadControllerGetStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<UploadStatusResponseDto>> {
    return uploadControllerGetStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Get upload status.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadControllerGetStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  uploadControllerGetStatus(params: UploadControllerGetStatus$Params, context?: HttpContext): Observable<UploadStatusResponseDto> {
    return this.uploadControllerGetStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<UploadStatusResponseDto>): UploadStatusResponseDto => r.body)
    );
  }

  /** Path part for operation `uploadControllerGetParsedResult()` */
  static readonly UploadControllerGetParsedResultPath = '/api/webgis/upload/{id}/parsed';

  /**
   * Get parsed result with field suggestions.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadControllerGetParsedResult()` instead.
   *
   * This method doesn't expect any request body.
   */
  uploadControllerGetParsedResult$Response(params: UploadControllerGetParsedResult$Params, context?: HttpContext): Observable<StrictHttpResponse<ParsedResultResponseDto>> {
    return uploadControllerGetParsedResult(this.http, this.rootUrl, params, context);
  }

  /**
   * Get parsed result with field suggestions.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadControllerGetParsedResult$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  uploadControllerGetParsedResult(params: UploadControllerGetParsedResult$Params, context?: HttpContext): Observable<ParsedResultResponseDto> {
    return this.uploadControllerGetParsedResult$Response(params, context).pipe(
      map((r: StrictHttpResponse<ParsedResultResponseDto>): ParsedResultResponseDto => r.body)
    );
  }

  /** Path part for operation `uploadControllerSubmitMapping()` */
  static readonly UploadControllerSubmitMappingPath = '/api/webgis/upload/{id}/mapping';

  /**
   * Submit field mapping and create layer.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadControllerSubmitMapping()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadControllerSubmitMapping$Response(params: UploadControllerSubmitMapping$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return uploadControllerSubmitMapping(this.http, this.rootUrl, params, context);
  }

  /**
   * Submit field mapping and create layer.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadControllerSubmitMapping$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadControllerSubmitMapping(params: UploadControllerSubmitMapping$Params, context?: HttpContext): Observable<void> {
    return this.uploadControllerSubmitMapping$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `uploadControllerRemove()` */
  static readonly UploadControllerRemovePath = '/api/webgis/upload/{id}';

  /**
   * Cancel upload and delete file.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  uploadControllerRemove$Response(params: UploadControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return uploadControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Cancel upload and delete file.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  uploadControllerRemove(params: UploadControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.uploadControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
