/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { categoriesControllerCreate } from '../fn/web-gis-categories/categories-controller-create';
import { CategoriesControllerCreate$Params } from '../fn/web-gis-categories/categories-controller-create';
import { categoriesControllerFindAll } from '../fn/web-gis-categories/categories-controller-find-all';
import { CategoriesControllerFindAll$Params } from '../fn/web-gis-categories/categories-controller-find-all';
import { categoriesControllerFindByCode } from '../fn/web-gis-categories/categories-controller-find-by-code';
import { CategoriesControllerFindByCode$Params } from '../fn/web-gis-categories/categories-controller-find-by-code';
import { categoriesControllerFindOne } from '../fn/web-gis-categories/categories-controller-find-one';
import { CategoriesControllerFindOne$Params } from '../fn/web-gis-categories/categories-controller-find-one';
import { categoriesControllerGetIndustries } from '../fn/web-gis-categories/categories-controller-get-industries';
import { CategoriesControllerGetIndustries$Params } from '../fn/web-gis-categories/categories-controller-get-industries';
import { categoriesControllerGetTemplateFields } from '../fn/web-gis-categories/categories-controller-get-template-fields';
import { CategoriesControllerGetTemplateFields$Params } from '../fn/web-gis-categories/categories-controller-get-template-fields';
import { categoriesControllerRemove } from '../fn/web-gis-categories/categories-controller-remove';
import { CategoriesControllerRemove$Params } from '../fn/web-gis-categories/categories-controller-remove';
import { categoriesControllerSeedSystemCategories } from '../fn/web-gis-categories/categories-controller-seed-system-categories';
import { CategoriesControllerSeedSystemCategories$Params } from '../fn/web-gis-categories/categories-controller-seed-system-categories';
import { categoriesControllerUpdate } from '../fn/web-gis-categories/categories-controller-update';
import { CategoriesControllerUpdate$Params } from '../fn/web-gis-categories/categories-controller-update';

@Injectable({ providedIn: 'root' })
export class WebGisCategoriesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `categoriesControllerFindAll()` */
  static readonly CategoriesControllerFindAllPath = '/api/webgis/categories';

  /**
   * Get all categories.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesControllerFindAll$Response(params?: CategoriesControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return categoriesControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all categories.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesControllerFindAll(params?: CategoriesControllerFindAll$Params, context?: HttpContext): Observable<void> {
    return this.categoriesControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `categoriesControllerCreate()` */
  static readonly CategoriesControllerCreatePath = '/api/webgis/categories';

  /**
   * Create a new layer category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  categoriesControllerCreate$Response(params: CategoriesControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return categoriesControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new layer category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  categoriesControllerCreate(params: CategoriesControllerCreate$Params, context?: HttpContext): Observable<void> {
    return this.categoriesControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `categoriesControllerGetIndustries()` */
  static readonly CategoriesControllerGetIndustriesPath = '/api/webgis/categories/industries';

  /**
   * Get list of supported industries.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesControllerGetIndustries()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesControllerGetIndustries$Response(params?: CategoriesControllerGetIndustries$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return categoriesControllerGetIndustries(this.http, this.rootUrl, params, context);
  }

  /**
   * Get list of supported industries.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesControllerGetIndustries$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesControllerGetIndustries(params?: CategoriesControllerGetIndustries$Params, context?: HttpContext): Observable<void> {
    return this.categoriesControllerGetIndustries$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `categoriesControllerFindOne()` */
  static readonly CategoriesControllerFindOnePath = '/api/webgis/categories/{id}';

  /**
   * Get category by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesControllerFindOne$Response(params: CategoriesControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return categoriesControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get category by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesControllerFindOne(params: CategoriesControllerFindOne$Params, context?: HttpContext): Observable<void> {
    return this.categoriesControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `categoriesControllerRemove()` */
  static readonly CategoriesControllerRemovePath = '/api/webgis/categories/{id}';

  /**
   * Delete category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesControllerRemove$Response(params: CategoriesControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return categoriesControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesControllerRemove(params: CategoriesControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.categoriesControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `categoriesControllerUpdate()` */
  static readonly CategoriesControllerUpdatePath = '/api/webgis/categories/{id}';

  /**
   * Update category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  categoriesControllerUpdate$Response(params: CategoriesControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return categoriesControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Update category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  categoriesControllerUpdate(params: CategoriesControllerUpdate$Params, context?: HttpContext): Observable<void> {
    return this.categoriesControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `categoriesControllerFindByCode()` */
  static readonly CategoriesControllerFindByCodePath = '/api/webgis/categories/code/{code}';

  /**
   * Get category by code.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesControllerFindByCode()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesControllerFindByCode$Response(params: CategoriesControllerFindByCode$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return categoriesControllerFindByCode(this.http, this.rootUrl, params, context);
  }

  /**
   * Get category by code.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesControllerFindByCode$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesControllerFindByCode(params: CategoriesControllerFindByCode$Params, context?: HttpContext): Observable<void> {
    return this.categoriesControllerFindByCode$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `categoriesControllerGetTemplateFields()` */
  static readonly CategoriesControllerGetTemplateFieldsPath = '/api/webgis/categories/{code}/template-fields';

  /**
   * Get template fields for a category (for auto-mapping).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesControllerGetTemplateFields()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesControllerGetTemplateFields$Response(params: CategoriesControllerGetTemplateFields$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return categoriesControllerGetTemplateFields(this.http, this.rootUrl, params, context);
  }

  /**
   * Get template fields for a category (for auto-mapping).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesControllerGetTemplateFields$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesControllerGetTemplateFields(params: CategoriesControllerGetTemplateFields$Params, context?: HttpContext): Observable<void> {
    return this.categoriesControllerGetTemplateFields$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `categoriesControllerSeedSystemCategories()` */
  static readonly CategoriesControllerSeedSystemCategoriesPath = '/api/webgis/categories/seed-system';

  /**
   * Seed default system categories (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesControllerSeedSystemCategories()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesControllerSeedSystemCategories$Response(params?: CategoriesControllerSeedSystemCategories$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return categoriesControllerSeedSystemCategories(this.http, this.rootUrl, params, context);
  }

  /**
   * Seed default system categories (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesControllerSeedSystemCategories$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesControllerSeedSystemCategories(params?: CategoriesControllerSeedSystemCategories$Params, context?: HttpContext): Observable<void> {
    return this.categoriesControllerSeedSystemCategories$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
