/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeviceCommandsControllerGetMqttStatus$Params {
}

export function deviceCommandsControllerGetMqttStatus(http: HttpClient, rootUrl: string, params?: DeviceCommandsControllerGetMqttStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'connected'?: boolean;
}>> {
  const rb = new RequestBuilder(rootUrl, deviceCommandsControllerGetMqttStatus.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'connected'?: boolean;
      }>;
    })
  );
}

deviceCommandsControllerGetMqttStatus.PATH = '/api/device-commands/status';
