/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ForecastResponseDto } from '../../models/forecast-response-dto';

export interface ForecastsControllerFindLatest$Params {
  idSensorChannel: string;
}

export function forecastsControllerFindLatest(http: HttpClient, rootUrl: string, params: ForecastsControllerFindLatest$Params, context?: HttpContext): Observable<StrictHttpResponse<ForecastResponseDto>> {
  const rb = new RequestBuilder(rootUrl, forecastsControllerFindLatest.PATH, 'get');
  if (params) {
    rb.path('idSensorChannel', params.idSensorChannel, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ForecastResponseDto>;
    })
  );
}

forecastsControllerFindLatest.PATH = '/api/ml/forecasts/latest/{idSensorChannel}';
