/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateNodeLocationDto } from '../../models/create-node-location-dto';
import { NodeLocationResponseDto } from '../../models/node-location-response-dto';

export interface NodeLocationsControllerCreate$Params {
      body: CreateNodeLocationDto
}

export function nodeLocationsControllerCreate(http: HttpClient, rootUrl: string, params: NodeLocationsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeLocationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, nodeLocationsControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NodeLocationResponseDto>;
    })
  );
}

nodeLocationsControllerCreate.PATH = '/api/node-locations';
