/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NodeLocationResponseDto } from '../../models/node-location-response-dto';

export interface NodeLocationsControllerFindOne$Params {
  id: string;
}

export function nodeLocationsControllerFindOne(http: HttpClient, rootUrl: string, params: NodeLocationsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeLocationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, nodeLocationsControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NodeLocationResponseDto>;
    })
  );
}

nodeLocationsControllerFindOne.PATH = '/api/node-locations/{id}';
