/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NodeLocationResponseDto } from '../../models/node-location-response-dto';
import { UpdateNodeLocationDto } from '../../models/update-node-location-dto';

export interface NodeLocationsControllerUpdate$Params {
  id: string;
      body: UpdateNodeLocationDto
}

export function nodeLocationsControllerUpdate(http: HttpClient, rootUrl: string, params: NodeLocationsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<NodeLocationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, nodeLocationsControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NodeLocationResponseDto>;
    })
  );
}

nodeLocationsControllerUpdate.PATH = '/api/node-locations/{id}';
