/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReleaseScheduleResponseDto } from '../../models/release-schedule-response-dto';

export interface DashboardControllerGetReleaseSchedule$Params {
}

export function dashboardControllerGetReleaseSchedule(http: HttpClient, rootUrl: string, params?: DashboardControllerGetReleaseSchedule$Params, context?: HttpContext): Observable<StrictHttpResponse<ReleaseScheduleResponseDto>> {
  const rb = new RequestBuilder(rootUrl, dashboardControllerGetReleaseSchedule.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReleaseScheduleResponseDto>;
    })
  );
}

dashboardControllerGetReleaseSchedule.PATH = '/api/dashboard/release-schedule';
