/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserDashboardDetailedResponseDto } from '../../models/user-dashboard-detailed-response-dto';

export interface UserDashboardsControllerFindOneDetailed$Params {
  id: string;
}

export function userDashboardsControllerFindOneDetailed(http: HttpClient, rootUrl: string, params: UserDashboardsControllerFindOneDetailed$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDashboardDetailedResponseDto>> {
  const rb = new RequestBuilder(rootUrl, userDashboardsControllerFindOneDetailed.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserDashboardDetailedResponseDto>;
    })
  );
}

userDashboardsControllerFindOneDetailed.PATH = '/api/user-dashboards/{id}/detailed';
