/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AlertEventResponseDto } from '../../models/alert-event-response-dto';
import { CreateAlertEventDto } from '../../models/create-alert-event-dto';

export interface AlertEventsControllerCreate$Params {
      body: CreateAlertEventDto
}

export function alertEventsControllerCreate(http: HttpClient, rootUrl: string, params: AlertEventsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<AlertEventResponseDto>> {
  const rb = new RequestBuilder(rootUrl, alertEventsControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AlertEventResponseDto>;
    })
  );
}

alertEventsControllerCreate.PATH = '/api/alert-events';
