/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AlertEventResponseDto } from '../../models/alert-event-response-dto';
import { UpdateAlertEventDto } from '../../models/update-alert-event-dto';

export interface AlertEventsControllerUpdate$Params {
  id: string;
      body: UpdateAlertEventDto
}

export function alertEventsControllerUpdate(http: HttpClient, rootUrl: string, params: AlertEventsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<AlertEventResponseDto>> {
  const rb = new RequestBuilder(rootUrl, alertEventsControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AlertEventResponseDto>;
    })
  );
}

alertEventsControllerUpdate.PATH = '/api/alert-events/{id}';
