import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, of, forkJoin } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import { Tutorial, TutorialCategory, TutorialMetadata, TutorialProgress, TutorialDifficulty, UserRole } from '../../models/tutorial.model';

@Injectable({
  providedIn: 'root'
})
export class TutorialService {
  private tutorials: Tutorial[] = [];
  private tutorialsLoaded = false;

  // Tutorial metadata registry - map tutorial IDs to their metadata
  // Tutorial metadata registry - map tutorial IDs to their metadata
  private tutorialMetadataRegistry: TutorialMetadata[] = [
    // Getting Started (existing)
    {
      id: 'getting-started-login',
      title: 'Getting Started: Login to System',
      description: 'Learn how to access the IoT Monitoring System',
      category: TutorialCategory.GETTING_STARTED,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 3,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['login', 'authentication', 'access'],
      icon: 'bi-box-arrow-in-right',
      path: 'getting-started/login',
      order: 1,
    },
    {
      id: 'getting-started-first-login',
      title: 'Getting Started: First Time Login Setup',
      description: 'Complete guide for new users to set up their account on first login',
      category: TutorialCategory.GETTING_STARTED,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 5,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['first-login', 'setup', 'profile', 'password', 'onboarding'],
      icon: 'bi-person-check',
      path: 'getting-started/first-login',
      order: 2,
    },
    {
      id: 'user-dashboard-overview',
      title: 'Dashboard Overview',
      description: 'Understanding widgets, KPIs, and navigation',
      category: TutorialCategory.USER_GUIDE,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['dashboard', 'overview', 'navigation'],
      order: 1,
      icon: 'bi-speedometer2',
      path: 'user-guide/dashboard-overview',
    },
    {
      id: 'user-view-projects',
      title: 'View Projects',
      description: 'Browse and search projects',
      category: TutorialCategory.USER_GUIDE,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['projects', 'view', 'browse'],
      order: 2,
      icon: 'bi-folder',
      path: 'user-guide/view-projects',
    },
    {
      id: 'user-view-owners',
      title: 'View Owners',
      description: 'Browse owner list and details',
      category: TutorialCategory.USER_GUIDE,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 6,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['owners', 'view'],
      order: 3,
      icon: 'bi-building',
      path: 'user-guide/view-owners',
    },
    {
      id: 'user-view-nodes',
      title: 'View Nodes',
      description: 'Browse node list with filters',
      category: TutorialCategory.USER_GUIDE,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['nodes', 'view', 'filters'],
      order: 4,
      icon: 'bi-diagram-3',
      path: 'user-guide/view-nodes',
    },
    {
      id: 'user-view-unpaired-devices',
      title: 'View Unpaired Devices',
      description: 'Find and manage unpaired devices',
      category: TutorialCategory.USER_GUIDE,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 6,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['devices', 'unpaired', 'pairing'],
      order: 5,
      icon: 'bi-link-45deg',
      path: 'user-guide/view-unpaired-devices',
    },
    {
      id: 'user-view-sensors',
      title: 'View Sensors',
      description: 'Browse sensor list and details',
      category: TutorialCategory.USER_GUIDE,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 7,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['sensors', 'view'],
      order: 6,
      icon: 'bi-thermometer',
      path: 'user-guide/view-sensors',
    },
    {
      id: 'user-view-telemetry',
      title: 'View Telemetry',
      description: 'Real-time telemetry monitoring',
      category: TutorialCategory.USER_GUIDE,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['telemetry', 'real-time', 'monitoring'],
      order: 7,
      icon: 'bi-activity',
      path: 'user-guide/view-telemetry',
    },
    {
      id: 'user-view-alerts',
      title: 'View Alerts',
      description: 'Check and manage active alerts',
      category: TutorialCategory.USER_GUIDE,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['alerts', 'notifications'],
      order: 8,
      icon: 'bi-bell',
      path: 'user-guide/view-alerts',
    },
    {
      id: 'user-profile-settings',
      title: 'User Profile Settings',
      description: 'Update profile, password, preferences',
      category: TutorialCategory.USER_GUIDE,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 5,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['profile', 'settings', 'password'],
      order: 9,
      icon: 'bi-person-gear',
      path: 'user-guide/user-profile-settings',
    },
    {
      id: 'admin-user-management',
      title: 'User Management',
      description: 'Add, edit, deactivate users',
      category: TutorialCategory.ADMIN_GUIDE,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 12,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['users', 'management'],
      order: 1,
      icon: 'bi-people',
      path: 'admin-guide/user-management',
    },
    {
      id: 'admin-assign-roles',
      title: 'Assign User Roles',
      description: 'Role assignments and permissions',
      category: TutorialCategory.ADMIN_GUIDE,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['roles', 'permissions'],
      order: 2,
      icon: 'bi-shield-check',
      path: 'admin-guide/assign-user-roles',
    },
    {
      id: 'admin-manage-projects',
      title: 'Manage Projects',
      description: 'Create, edit, delete projects',
      category: TutorialCategory.ADMIN_GUIDE,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['projects', 'management'],
      order: 3,
      icon: 'bi-folder-plus',
      path: 'admin-guide/manage-projects',
    },
    {
      id: 'admin-node-registration',
      title: 'Node Registration',
      description: 'Register and configure new nodes',
      category: TutorialCategory.ADMIN_GUIDE,
      difficulty: TutorialDifficulty.ADVANCED,
      estimatedTime: 15,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['nodes', 'registration'],
      order: 4,
      icon: 'bi-cpu',
      path: 'admin-guide/node-registration',
    },
    {
      id: 'admin-sensor-config',
      title: 'Sensor Configuration',
      description: 'Configure sensor types and formulas',
      category: TutorialCategory.ADMIN_GUIDE,
      difficulty: TutorialDifficulty.ADVANCED,
      estimatedTime: 12,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['sensors', 'configuration'],
      order: 5,
      icon: 'bi-sliders',
      path: 'admin-guide/sensor-configuration',
    },
    {
      id: 'admin-alert-rules',
      title: 'Alert Rules Setup',
      description: 'Create and manage alert rules',
      category: TutorialCategory.ADMIN_GUIDE,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['alerts', 'rules'],
      order: 6,
      icon: 'bi-exclamation-triangle',
      path: 'admin-guide/alert-rules-setup',
    },
    {
      id: 'admin-dashboard-custom',
      title: 'Dashboard Customization',
      description: 'Customize widgets and layouts',
      category: TutorialCategory.ADMIN_GUIDE,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['dashboard', 'customization'],
      order: 7,
      icon: 'bi-layout-wtf',
      path: 'admin-guide/dashboard-customization',
    },
    {
      id: 'admin-audit-logs',
      title: 'Audit Logs',
      description: 'View and analyze audit logs',
      category: TutorialCategory.ADMIN_GUIDE,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 7,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['audit', 'logs', 'security'],
      order: 8,
      icon: 'bi-file-text',
      path: 'admin-guide/audit-logs',
    },
    {
      id: 'owner-account-setup',
      title: 'Owner Account Setup',
      description: 'Initial owner account configuration',
      category: TutorialCategory.OWNER_GUIDE,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['owner', 'setup'],
      order: 1,
      icon: 'bi-person-badge',
      path: 'owner-guide/owner-account-setup',
    },
    {
      id: 'owner-multi-project',
      title: 'Multi-Project Management',
      description: 'Manage multiple projects efficiently',
      category: TutorialCategory.OWNER_GUIDE,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 12,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['projects', 'management'],
      order: 2,
      icon: 'bi-collection',
      path: 'owner-guide/multi-project-management',
    },
    {
      id: 'owner-data-forwarding',
      title: 'Data Forwarding Setup',
      description: 'Configure data forwarding to external systems',
      category: TutorialCategory.OWNER_GUIDE,
      difficulty: TutorialDifficulty.ADVANCED,
      estimatedTime: 15,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['data', 'integration'],
      order: 3,
      icon: 'bi-arrow-repeat',
      path: 'owner-guide/data-forwarding-setup',
    },
    {
      id: 'owner-sla-contact',
      title: 'SLA & Contact Settings',
      description: 'Configure SLA and contact preferences',
      category: TutorialCategory.OWNER_GUIDE,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['sla', 'contacts'],
      order: 4,
      icon: 'bi-envelope',
      path: 'owner-guide/sla-contact-settings',
    },
    {
      id: 'owner-reports',
      title: 'Owner Reports',
      description: 'Generate and schedule owner reports',
      category: TutorialCategory.OWNER_GUIDE,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['reports', 'analytics'],
      order: 5,
      icon: 'bi-graph-up',
      path: 'owner-guide/owner-reports',
    },
    {
      id: 'owner-manage-projects',
      title: 'Manage Projects',
      description: 'Create, edit, delete projects',
      category: TutorialCategory.OWNER_GUIDE,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['projects', 'management'],
      order: 6,
      icon: 'bi-folder-plus',
      path: 'owner-guide/manage-projects',
    },
    {
      id: 'module-dashboard-kpi',
      title: 'KPI Cards',
      description: 'Monitor key performance indicators',
      category: TutorialCategory.MODULE_DASHBOARD,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['kpi', 'dashboard'],
      order: 1,
      icon: 'bi-bar-chart',
      path: 'module-dashboard/kpi-cards',
    },
    {
      id: 'module-dashboard-health',
      title: 'Node Health Widget',
      description: 'Monitor node health status',
      category: TutorialCategory.MODULE_DASHBOARD,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 6,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['health', 'monitoring'],
      order: 2,
      icon: 'bi-heart-pulse',
      path: 'module-dashboard/node-health-widget',
    },
    {
      id: 'module-dashboard-connectivity',
      title: 'Connectivity Status',
      description: 'Real-time connectivity monitoring',
      category: TutorialCategory.MODULE_DASHBOARD,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 7,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['connectivity', 'status'],
      order: 3,
      icon: 'bi-wifi',
      path: 'module-dashboard/connectivity-status',
    },
    {
      id: 'module-dashboard-telemetry',
      title: 'Telemetry Streams',
      description: 'Live telemetry data streams',
      category: TutorialCategory.MODULE_DASHBOARD,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['telemetry', 'real-time'],
      order: 4,
      icon: 'bi-broadcast',
      path: 'module-dashboard/telemetry-streams',
    },
    {
      id: 'module-dashboard-telemetry-aggregates',
      title: 'Telemetry Aggregates',
      description: 'Monitor aggregated sensor data with time windows, cascading filters & auto-refresh',
      category: TutorialCategory.MODULE_DASHBOARD,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 15,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['telemetry', 'aggregates', 'monitoring', 'real-time', 'filters'],
      order: 5,
      icon: 'bi-graph-up-arrow',
      path: 'module-dashboard/telemetry-aggregates',
    },
    {
      id: 'module-dashboard-logs',
      title: 'IoT Logs Widget',
      description: 'View recent IoT device logs',
      category: TutorialCategory.MODULE_DASHBOARD,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['logs', 'monitoring'],
      order: 6,
      icon: 'bi-journal-text',
      path: 'module-dashboard/iot-logs-widget',
    },
    {
      id: 'module-dashboard-alerts',
      title: 'Alert Summary',
      description: 'Alert statistics and trends',
      category: TutorialCategory.MODULE_DASHBOARD,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 6,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['alerts', 'summary'],
      order: 7,
      icon: 'bi-exclamation-circle',
      path: 'module-dashboard/alert-summary',
    },
    {
      id: 'module-dashboard-custom',
      title: 'Custom Dashboards',
      description: 'Create and manage custom dashboards',
      category: TutorialCategory.MODULE_DASHBOARD,
      difficulty: TutorialDifficulty.ADVANCED,
      estimatedTime: 12,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['dashboard', 'customization'],
      order: 8,
      icon: 'bi-grid-3x3',
      path: 'module-dashboard/custom-dashboards',
    },
    {
      id: 'module-owners-list',
      title: 'Owner List',
      description: 'Browse and filter owners',
      category: TutorialCategory.MODULE_OWNERS,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 6,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['owners', 'list'],
      order: 1,
      icon: 'bi-list-ul',
      path: 'module-owners/owner-list',
    },
    {
      id: 'module-owners-details',
      title: 'Owner Details',
      description: 'View detailed owner information',
      category: TutorialCategory.MODULE_OWNERS,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['owners', 'details'],
      order: 2,
      icon: 'bi-info-circle',
      path: 'module-owners/owner-details',
    },
    {
      id: 'module-owners-create',
      title: 'Create Owner',
      description: 'Add new owner to system',
      category: TutorialCategory.MODULE_OWNERS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['owners', 'create'],
      order: 3,
      icon: 'bi-plus-circle',
      path: 'module-owners/create-owner',
    },
    {
      id: 'module-owners-edit',
      title: 'Edit Owner',
      description: 'Modify owner information',
      category: TutorialCategory.MODULE_OWNERS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['owners', 'edit'],
      order: 4,
      icon: 'bi-pencil',
      path: 'module-owners/edit-owner',
    },
    {
      id: 'module-owners-projects',
      title: 'Owner Projects',
      description: "Manage owner's project portfolio",
      category: TutorialCategory.MODULE_OWNERS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['owners', 'projects'],
      order: 5,
      icon: 'bi-folder2-open',
      path: 'module-owners/owner-projects',
    },
    {
      id: 'module-projects-list',
      title: 'Project List',
      description: 'Browse and filter projects',
      category: TutorialCategory.MODULE_PROJECTS,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 6,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['projects', 'list'],
      order: 1,
      icon: 'bi-list-ul',
      path: 'module-projects/project-list',
    },
    {
      id: 'module-projects-details',
      title: 'Project Details',
      description: 'View detailed project information',
      category: TutorialCategory.MODULE_PROJECTS,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['projects', 'details'],
      order: 2,
      icon: 'bi-info-circle',
      path: 'module-projects/project-details',
    },
    {
      id: 'module-projects-create',
      title: 'Create Project',
      description: 'Create new project',
      category: TutorialCategory.MODULE_PROJECTS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['projects', 'create'],
      order: 3,
      icon: 'bi-plus-circle',
      path: 'module-projects/create-project',
    },
    {
      id: 'module-projects-edit',
      title: 'Edit Project',
      description: 'Modify project settings',
      category: TutorialCategory.MODULE_PROJECTS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['projects', 'edit'],
      order: 4,
      icon: 'bi-pencil',
      path: 'module-projects/edit-project',
    },
    {
      id: 'module-projects-nodes',
      title: 'Project Nodes',
      description: "View and manage project's nodes",
      category: TutorialCategory.MODULE_PROJECTS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['projects', 'nodes'],
      order: 5,
      icon: 'bi-diagram-3',
      path: 'module-projects/project-nodes',
    },
    {
      id: 'module-nodes-filters',
      title: 'Node List Filters',
      description: 'Advanced filtering and search',
      category: TutorialCategory.MODULE_NODES,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['nodes', 'filters'],
      order: 1,
      icon: 'bi-funnel',
      path: 'module-nodes/node-list-filters',
    },
    {
      id: 'module-nodes-detail',
      title: 'Node Detail View',
      description: 'Comprehensive node information',
      category: TutorialCategory.MODULE_NODES,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['nodes', 'details'],
      order: 2,
      icon: 'bi-info-circle-fill',
      path: 'module-nodes/node-detail-view',
    },
    {
      id: 'module-nodes-pairing',
      title: 'Node Pairing',
      description: 'Pair devices to projects',
      category: TutorialCategory.MODULE_NODES,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 12,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['nodes', 'pairing'],
      order: 3,
      icon: 'bi-link',
      path: 'module-nodes/node-pairing',
    },
    {
      id: 'module-nodes-unpaired',
      title: 'Unpaired Devices',
      description: 'Manage unpaired devices',
      category: TutorialCategory.MODULE_NODES,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['nodes', 'unpaired'],
      order: 4,
      icon: 'bi-unlink',
      path: 'module-nodes/unpaired-devices',
    },
    {
      id: 'module-nodes-location',
      title: 'Node Location Tracking',
      description: 'Track and update node locations',
      category: TutorialCategory.MODULE_NODES,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['nodes', 'location', 'gps'],
      order: 5,
      icon: 'bi-geo-alt',
      path: 'module-nodes/node-location-tracking',
    },
    {
      id: 'module-nodes-profiles',
      title: 'Node Profiles',
      description: 'Configure node communication profiles',
      category: TutorialCategory.MODULE_NODES,
      difficulty: TutorialDifficulty.ADVANCED,
      estimatedTime: 12,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['nodes', 'profiles'],
      order: 6,
      icon: 'bi-file-earmark-code',
      path: 'module-nodes/node-profiles',
    },
    {
      id: 'module-nodes-config',
      title: 'Node Configuration',
      description: 'Advanced node settings',
      category: TutorialCategory.MODULE_NODES,
      difficulty: TutorialDifficulty.ADVANCED,
      estimatedTime: 15,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['nodes', 'configuration'],
      order: 7,
      icon: 'bi-gear-fill',
      path: 'module-nodes/node-configuration',
    },
    {
      id: 'module-sensors-list',
      title: 'Sensor List',
      description: 'Browse all sensors',
      category: TutorialCategory.MODULE_SENSORS,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 6,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['sensors', 'list'],
      order: 1,
      icon: 'bi-list-stars',
      path: 'module-sensors/sensor-list',
    },
    {
      id: 'module-sensors-types',
      title: 'Sensor Types',
      description: 'Understanding sensor types',
      category: TutorialCategory.MODULE_SENSORS,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['sensors', 'types'],
      order: 2,
      icon: 'bi-tags',
      path: 'module-sensors/sensor-types',
    },
    {
      id: 'module-sensors-catalogs',
      title: 'Sensor Catalogs',
      description: 'Browse sensor catalog library',
      category: TutorialCategory.MODULE_SENSORS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['sensors', 'catalogs'],
      order: 3,
      icon: 'bi-book',
      path: 'module-sensors/sensor-catalogs',
    },
    {
      id: 'module-sensors-detail',
      title: 'Sensor Detail View',
      description: 'Monitor channel telemetry stream with filtering and pagination',
      category: TutorialCategory.MODULE_SENSORS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 12,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['sensors', 'telemetry', 'monitoring', 'channel'],
      order: 4,
      icon: 'bi-graph-up',
      path: 'module-sensors/sensor-detail',
    },
    {
      id: 'module-sensors-channels',
      title: 'Sensor Channels',
      description: 'Configure sensor channels',
      category: TutorialCategory.MODULE_SENSORS,
      difficulty: TutorialDifficulty.ADVANCED,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['sensors', 'channels'],
      order: 5,
      icon: 'bi-collection-play',
      path: 'module-sensors/sensor-channels',
    },
    {
      id: 'module-sensors-formulas',
      title: 'Sensor Formulas',
      description: 'Create and apply sensor formulas',
      category: TutorialCategory.MODULE_SENSORS,
      difficulty: TutorialDifficulty.ADVANCED,
      estimatedTime: 12,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['sensors', 'formulas'],
      order: 6,
      icon: 'bi-calculator',
      path: 'module-sensors/sensor-formulas',
    },
    {
      id: 'module-sensors-calibration',
      title: 'Sensor Calibration',
      description: 'Calibrate sensor readings',
      category: TutorialCategory.MODULE_SENSORS,
      difficulty: TutorialDifficulty.ADVANCED,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['sensors', 'calibration'],
      order: 7,
      icon: 'bi-sliders2',
      path: 'module-sensors/sensor-calibration',
    },
    {
      id: 'module-alerts-rules',
      title: 'Alert Rules',
      description: 'Create and manage alert rules',
      category: TutorialCategory.MODULE_ALERTS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['alerts', 'rules'],
      order: 1,
      icon: 'bi-shield-exclamation',
      path: 'module-alerts/alert-rules',
    },
    {
      id: 'module-alerts-events',
      title: 'Alert Events',
      description: 'View alert event history',
      category: TutorialCategory.MODULE_ALERTS,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['alerts', 'events'],
      order: 2,
      icon: 'bi-calendar-event',
      path: 'module-alerts/alert-events',
    },
    {
      id: 'module-alerts-notifications',
      title: 'Alert Notifications',
      description: 'Configure alert notifications',
      category: TutorialCategory.MODULE_ALERTS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['alerts', 'notifications'],
      order: 3,
      icon: 'bi-envelope-exclamation',
      path: 'module-alerts/alert-notifications',
    },
    {
      id: 'module-alerts-ack',
      title: 'Alert Acknowledgment',
      description: 'Acknowledge and manage alerts',
      category: TutorialCategory.MODULE_ALERTS,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 6,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['alerts', 'acknowledgment'],
      order: 4,
      icon: 'bi-check-circle',
      path: 'module-alerts/alert-acknowledgment',
    },
    {
      id: 'module-alerts-history',
      title: 'Alert History',
      description: 'Browse alert history and trends',
      category: TutorialCategory.MODULE_ALERTS,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['alerts', 'history'],
      order: 5,
      icon: 'bi-clock-history',
      path: 'module-alerts/alert-history',
    },
    {
      id: 'module-reports-generate',
      title: 'Generate Reports',
      description: 'Create custom reports',
      category: TutorialCategory.MODULE_REPORTS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 12,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['reports', 'generate'],
      order: 1,
      icon: 'bi-file-earmark-bar-graph',
      path: 'module-reports/generate-reports',
    },
    {
      id: 'module-reports-export',
      title: 'Export Data',
      description: 'Export data to various formats',
      category: TutorialCategory.MODULE_REPORTS,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['export', 'data'],
      order: 2,
      icon: 'bi-download',
      path: 'module-reports/export-data',
    },
    {
      id: 'module-reports-scheduled',
      title: 'Scheduled Reports',
      description: 'Automate report generation',
      category: TutorialCategory.MODULE_REPORTS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['reports', 'scheduled'],
      order: 3,
      icon: 'bi-calendar-check',
      path: 'module-reports/scheduled-reports',
    },
    {
      id: 'module-reports-templates',
      title: 'Report Templates',
      description: 'Create and use report templates',
      category: TutorialCategory.MODULE_REPORTS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['reports', 'templates'],
      order: 4,
      icon: 'bi-file-earmark-richtext',
      path: 'module-reports/report-templates',
    },
    {
      id: 'module-users-add',
      title: 'Add New User',
      description: 'Create new user accounts',
      category: TutorialCategory.MODULE_USERS,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['users', 'create'],
      order: 1,
      icon: 'bi-person-plus',
      path: 'module-users/add-new-user',
    },
    {
      id: 'module-users-roles',
      title: 'User Roles',
      description: 'Manage user roles and permissions',
      category: TutorialCategory.MODULE_USERS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['users', 'roles'],
      order: 2,
      icon: 'bi-person-badge',
      path: 'module-users/user-roles',
    },
    {
      id: 'module-users-permissions',
      title: 'User Permissions',
      description: 'Configure granular permissions',
      category: TutorialCategory.MODULE_USERS,
      difficulty: TutorialDifficulty.ADVANCED,
      estimatedTime: 12,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['users', 'permissions'],
      order: 3,
      icon: 'bi-key',
      path: 'module-users/user-permissions',
    },
    {
      id: 'module-users-deactivate',
      title: 'Deactivate Users',
      description: 'Deactivate or suspend users',
      category: TutorialCategory.MODULE_USERS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 6,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['users', 'deactivate'],
      order: 4,
      icon: 'bi-person-x',
      path: 'module-users/deactivate-users',
    },
    {
      id: 'module-users-activity',
      title: 'User Activity',
      description: 'Monitor user activity logs',
      category: TutorialCategory.MODULE_USERS,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['users', 'activity'],
      order: 5,
      icon: 'bi-activity',
      path: 'module-users/user-activity',
    },
    {
      id: 'module-profiles-node',
      title: 'Node Profiles',
      description: 'Configure node profiles',
      category: TutorialCategory.MODULE_PROFILES,
      difficulty: TutorialDifficulty.ADVANCED,
      estimatedTime: 12,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['profiles', 'nodes'],
      order: 1,
      icon: 'bi-file-code',
      path: 'module-profiles/node-profiles',
    },
    {
      id: 'module-profiles-rs485',
      title: 'RS485 Configuration',
      description: 'Configure RS485 communication',
      category: TutorialCategory.MODULE_PROFILES,
      difficulty: TutorialDifficulty.ADVANCED,
      estimatedTime: 15,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['rs485', 'modbus'],
      order: 2,
      icon: 'bi-diagram-2',
      path: 'module-profiles/rs485-configuration',
    },
    {
      id: 'module-profiles-builder',
      title: 'Profile Builder',
      description: 'Build custom profiles',
      category: TutorialCategory.MODULE_PROFILES,
      difficulty: TutorialDifficulty.ADVANCED,
      estimatedTime: 15,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['profiles', 'builder'],
      order: 3,
      icon: 'bi-tools',
      path: 'module-profiles/profile-builder',
    },
    {
      id: 'module-node-models-list',
      title: 'Node Models List',
      description: 'Browse available node models',
      category: TutorialCategory.MODULE_NODE_MODELS,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 6,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['models', 'list'],
      order: 1,
      icon: 'bi-grid-1x2',
      path: 'module-node-models/node-models-list',
    },
    {
      id: 'module-node-models-create',
      title: 'Create Node Model',
      description: 'Define new node models',
      category: TutorialCategory.MODULE_NODE_MODELS,
      difficulty: TutorialDifficulty.ADVANCED,
      estimatedTime: 15,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['models', 'create'],
      order: 2,
      icon: 'bi-plus-square',
      path: 'module-node-models/create-node-model',
    },
    {
      id: 'module-node-models-edit',
      title: 'Edit Node Model',
      description: 'Modify node model definitions',
      category: TutorialCategory.MODULE_NODE_MODELS,
      difficulty: TutorialDifficulty.ADVANCED,
      estimatedTime: 12,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['models', 'edit'],
      order: 3,
      icon: 'bi-pencil-square',
      path: 'module-node-models/edit-node-model',
    },
    {
      id: 'troubleshoot-login',
      title: 'Login Issues',
      description: "Can't login, forgot password",
      category: TutorialCategory.TROUBLESHOOTING,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 5,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['login', 'password'],
      order: 1,
      icon: 'bi-question-circle',
      path: 'troubleshooting/login-issues',
    },
    {
      id: 'troubleshoot-node-offline',
      title: 'Node Offline',
      description: 'Troubleshoot offline nodes',
      category: TutorialCategory.TROUBLESHOOTING,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['nodes', 'offline'],
      order: 2,
      icon: 'bi-wifi-off',
      path: 'troubleshooting/node-offline',
    },
    {
      id: 'troubleshoot-sensor',
      title: 'Sensor Not Reading',
      description: 'Fix sensor reading issues',
      category: TutorialCategory.TROUBLESHOOTING,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['sensors', 'readings'],
      order: 3,
      icon: 'bi-exclamation-triangle',
      path: 'troubleshooting/sensor-not-reading',
    },
    {
      id: 'troubleshoot-alert',
      title: 'Alert Not Triggering',
      description: 'Debug alert rules',
      category: TutorialCategory.TROUBLESHOOTING,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['alerts', 'debug'],
      order: 4,
      icon: 'bi-bell-slash',
      path: 'troubleshooting/alert-not-triggering',
    },
    {
      id: 'troubleshoot-performance',
      title: 'Performance Issues',
      description: 'Slow loading, timeouts',
      category: TutorialCategory.TROUBLESHOOTING,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 10,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['performance', 'slow'],
      order: 5,
      icon: 'bi-speedometer',
      path: 'troubleshooting/performance-issues',
    },
    {
      id: 'troubleshoot-export',
      title: 'Data Export Errors',
      description: 'Fix export failures',
      category: TutorialCategory.TROUBLESHOOTING,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 6,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['export', 'errors'],
      order: 6,
      icon: 'bi-file-x',
      path: 'troubleshooting/data-export-errors',
    },
    {
      id: 'faq-general',
      title: 'General Questions',
      description: 'Common questions and answers',
      category: TutorialCategory.FAQ,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 5,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['faq', 'general'],
      order: 1,
      icon: 'bi-question-square',
      path: 'faq/general-questions',
    },
    {
      id: 'faq-security',
      title: 'Account Security',
      description: 'Security best practices',
      category: TutorialCategory.FAQ,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 6,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['security', 'account'],
      order: 2,
      icon: 'bi-shield-lock',
      path: 'faq/account-security',
    },
    {
      id: 'faq-privacy',
      title: 'Data Privacy',
      description: 'Privacy and data protection',
      category: TutorialCategory.FAQ,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 5,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['privacy', 'data'],
      order: 3,
      icon: 'bi-eye-slash',
      path: 'faq/data-privacy',
    },
    {
      id: 'faq-billing',
      title: 'Billing & Subscription',
      description: 'Billing and payment questions',
      category: TutorialCategory.FAQ,
      difficulty: TutorialDifficulty.BEGINNER,
      estimatedTime: 6,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['billing', 'subscription'],
      order: 4,
      icon: 'bi-credit-card',
      path: 'faq/billing-subscription',
    },
    {
      id: 'faq-technical',
      title: 'Technical Specs',
      description: 'System requirements and specs',
      category: TutorialCategory.FAQ,
      difficulty: TutorialDifficulty.INTERMEDIATE,
      estimatedTime: 8,
      roles: [UserRole.USER, UserRole.ADMIN, UserRole.OWNER, UserRole.SUPER_ADMIN],
      tags: ['technical', 'specs'],
      order: 5,
      icon: 'bi-cpu',
      path: 'faq/technical-specs',
    },

  ];

  constructor(private http: HttpClient) {
    this.initializeTutorials();
  }

  /**
   * Initialize tutorials from metadata registry
   */
  private initializeTutorials(): void {
    // Create Tutorial objects from metadata (without sections, as those are in components)
    this.tutorials = this.tutorialMetadataRegistry.map(metadata => ({
      metadata,
      sections: [] // Sections are handled by individual components
    }));
    this.tutorialsLoaded = true;
  }

  /**
   * Get all tutorials
   */
  getAllTutorials(): Observable<Tutorial[]> {
    return of(this.tutorials);
  }

  /**
   * Get tutorials by category
   */
  getTutorialsByCategory(category: TutorialCategory): Observable<Tutorial[]> {
    const filtered = this.tutorials.filter(t => t.metadata.category === category);
    return of(filtered);
  }

  /**
   * Get tutorial by ID
   */
  getTutorialById(id: string): Observable<Tutorial | undefined> {
    const tutorial = this.tutorials.find(t => t.metadata.id === id);
    return of(tutorial);
  }

  /**
   * Search tutorials
   */
  searchTutorials(query: string): Observable<Tutorial[]> {
    const lowerQuery = query.toLowerCase();
    const results = this.tutorials.filter(t =>
      t.metadata.title.toLowerCase().includes(lowerQuery) ||
      t.metadata.description.toLowerCase().includes(lowerQuery) ||
      t.metadata.tags.some((tag: string) => tag.toLowerCase().includes(lowerQuery))
    );
    return of(results);
  }

  /**
   * Get user's tutorial progress
   */
  getTutorialProgress(tutorialId: string): Observable<TutorialProgress | null> {
    // TODO: Get from localStorage or API
    const stored = localStorage.getItem(`tutorial-progress-${tutorialId}`);
    if (stored) {
      return of(JSON.parse(stored));
    }
    return of(null);
  }

  /**
   * Get tutorial progress
   */
  getProgress(userId: string, tutorialId: string): TutorialProgress {
    const key = `tutorial-progress-${tutorialId}`;
    const stored = localStorage.getItem(key);

    if (stored) {
      const progress = JSON.parse(stored);
      return {
        ...progress,
        lastAccessedAt: new Date(progress.lastAccessedAt),
      };
    }

    // Return default progress
    return {
      userId,
      tutorialId,
      completedSections: [],
      currentSection: 0,
      lastAccessedAt: new Date(),
      completed: false,
    };
  }

  /**
   * Update tutorial progress
   */
  updateProgress(progress: TutorialProgress): void {
    localStorage.setItem(`tutorial-progress-${progress.tutorialId}`, JSON.stringify(progress));
  }

  /**
   * Mark section as completed
   */
  markSectionCompleted(userId: string, tutorialId: string): void {
    const key = `tutorial-progress-${tutorialId}`;
    const stored = localStorage.getItem(key);
    let progress: TutorialProgress;

    if (stored) {
      progress = JSON.parse(stored);
    } else {
      progress = {
        userId,
        tutorialId,
        completedSections: [],
        currentSection: 0,
        lastAccessedAt: new Date(),
        completed: false,
      };
    }

    // Note: We track completed sections at the tutorial component level
    // This method just updates the progress timestamp
    progress.lastAccessedAt = new Date();

    this.updateProgress(progress);
  }

  /**
   * Get categories with tutorial count
   */
  getCategoriesWithCount(): Observable<{ category: TutorialCategory; count: number }[]> {
    const categoryMap = new Map<TutorialCategory, number>();
    
    this.tutorials.forEach(tutorial => {
      const count = categoryMap.get(tutorial.metadata.category) || 0;
      categoryMap.set(tutorial.metadata.category, count + 1);
    });

    const result = Array.from(categoryMap.entries()).map(([category, count]) => ({
      category,
      count,
    }));

    return of(result);
  }
}
