/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface MlNotificationControllerResetSuppression$Params {
  deviceId: string;
  sensorKey: string;
  severity: string;
}

export function mlNotificationControllerResetSuppression(http: HttpClient, rootUrl: string, params: MlNotificationControllerResetSuppression$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, mlNotificationControllerResetSuppression.PATH, 'post');
  if (params) {
    rb.path('deviceId', params.deviceId, {});
    rb.path('sensorKey', params.sensorKey, {});
    rb.path('severity', params.severity, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

mlNotificationControllerResetSuppression.PATH = '/api/notifications/ml/dedup/reset/{deviceId}/{sensorKey}/{severity}';
