/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface NodeModelCommandsControllerFindAll$Params {
  page?: number;
  limit?: number;
  search?: string;
  idNodeModel?: string;
  channel?: string;
  isActive?: boolean;
}

export function nodeModelCommandsControllerFindAll(http: HttpClient, rootUrl: string, params?: NodeModelCommandsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, nodeModelCommandsControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('search', params.search, {});
    rb.query('idNodeModel', params.idNodeModel, {});
    rb.query('channel', params.channel, {});
    rb.query('isActive', params.isActive, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

nodeModelCommandsControllerFindAll.PATH = '/api/node-model-commands';
