/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomWidgetResponseDto } from '../../models/custom-widget-response-dto';

export interface WidgetBuilderControllerGetWidget$Params {

/**
 * Dashboard ID
 */
  dashboardId: string;

/**
 * Widget ID
 */
  widgetId: string;
}

export function widgetBuilderControllerGetWidget(http: HttpClient, rootUrl: string, params: WidgetBuilderControllerGetWidget$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomWidgetResponseDto>> {
  const rb = new RequestBuilder(rootUrl, widgetBuilderControllerGetWidget.PATH, 'get');
  if (params) {
    rb.path('dashboardId', params.dashboardId, {});
    rb.path('widgetId', params.widgetId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomWidgetResponseDto>;
    })
  );
}

widgetBuilderControllerGetWidget.PATH = '/api/widget-builder/dashboards/{dashboardId}/widgets/{widgetId}';
