/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomWidgetResponseDto } from '../../models/custom-widget-response-dto';

export interface WidgetBuilderControllerGetWidgets$Params {

/**
 * Dashboard ID
 */
  dashboardId: string;
}

export function widgetBuilderControllerGetWidgets(http: HttpClient, rootUrl: string, params: WidgetBuilderControllerGetWidgets$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CustomWidgetResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, widgetBuilderControllerGetWidgets.PATH, 'get');
  if (params) {
    rb.path('dashboardId', params.dashboardId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CustomWidgetResponseDto>>;
    })
  );
}

widgetBuilderControllerGetWidgets.PATH = '/api/widget-builder/dashboards/{dashboardId}/widgets';
