/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateWidgetDto } from '../../models/create-widget-dto';
import { CustomWidgetResponseDto } from '../../models/custom-widget-response-dto';

export interface WidgetBuilderControllerCreateWidget$Params {

/**
 * Dashboard ID
 */
  dashboardId: string;
      body: CreateWidgetDto
}

export function widgetBuilderControllerCreateWidget(http: HttpClient, rootUrl: string, params: WidgetBuilderControllerCreateWidget$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomWidgetResponseDto>> {
  const rb = new RequestBuilder(rootUrl, widgetBuilderControllerCreateWidget.PATH, 'post');
  if (params) {
    rb.path('dashboardId', params.dashboardId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomWidgetResponseDto>;
    })
  );
}

widgetBuilderControllerCreateWidget.PATH = '/api/widget-builder/dashboards/{dashboardId}/widgets';
