/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomDashboardResponseDto } from '../../models/custom-dashboard-response-dto';
import { UpdateCustomDashboardDto } from '../../models/update-custom-dashboard-dto';

export interface WidgetBuilderControllerUpdateDashboard$Params {

/**
 * Dashboard ID
 */
  id: string;
      body: UpdateCustomDashboardDto
}

export function widgetBuilderControllerUpdateDashboard(http: HttpClient, rootUrl: string, params: WidgetBuilderControllerUpdateDashboard$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomDashboardResponseDto>> {
  const rb = new RequestBuilder(rootUrl, widgetBuilderControllerUpdateDashboard.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomDashboardResponseDto>;
    })
  );
}

widgetBuilderControllerUpdateDashboard.PATH = '/api/widget-builder/dashboards/{id}';
