/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ValidateQueryDto } from '../../models/validate-query-dto';
import { ValidateQueryResponseDto } from '../../models/validate-query-response-dto';

export interface WidgetBuilderControllerValidateQuery$Params {
      body: ValidateQueryDto
}

export function widgetBuilderControllerValidateQuery(http: HttpClient, rootUrl: string, params: WidgetBuilderControllerValidateQuery$Params, context?: HttpContext): Observable<StrictHttpResponse<ValidateQueryResponseDto>> {
  const rb = new RequestBuilder(rootUrl, widgetBuilderControllerValidateQuery.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ValidateQueryResponseDto>;
    })
  );
}

widgetBuilderControllerValidateQuery.PATH = '/api/widget-builder/query/validate';
