/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface WidgetBuilderControllerDeleteWidget$Params {

/**
 * Dashboard ID
 */
  dashboardId: string;

/**
 * Widget ID
 */
  widgetId: string;
}

export function widgetBuilderControllerDeleteWidget(http: HttpClient, rootUrl: string, params: WidgetBuilderControllerDeleteWidget$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, widgetBuilderControllerDeleteWidget.PATH, 'delete');
  if (params) {
    rb.path('dashboardId', params.dashboardId, {});
    rb.path('widgetId', params.widgetId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

widgetBuilderControllerDeleteWidget.PATH = '/api/widget-builder/dashboards/{dashboardId}/widgets/{widgetId}';
