/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface WidgetBuilderControllerGetDataSources$Params {
}

export function widgetBuilderControllerGetDataSources(http: HttpClient, rootUrl: string, params?: WidgetBuilderControllerGetDataSources$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'postgresql'?: {
'available'?: boolean;
'name'?: string;
};
'clickhouse'?: {
'available'?: boolean;
'name'?: string;
'status'?: string;
};
}>> {
  const rb = new RequestBuilder(rootUrl, widgetBuilderControllerGetDataSources.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'postgresql'?: {
      'available'?: boolean;
      'name'?: string;
      };
      'clickhouse'?: {
      'available'?: boolean;
      'name'?: string;
      'status'?: string;
      };
      }>;
    })
  );
}

widgetBuilderControllerGetDataSources.PATH = '/api/widget-builder/datasources';
