/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ScadaDiagramListItemResponseDto } from '../../models/scada-diagram-list-item-response-dto';

export interface ScadaDiagramsControllerFindAll$Params {
  projectId?: string;
  ownerId?: string;
  status?: string;
}

export function scadaDiagramsControllerFindAll(http: HttpClient, rootUrl: string, params?: ScadaDiagramsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ScadaDiagramListItemResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, scadaDiagramsControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('projectId', params.projectId, {});
    rb.query('ownerId', params.ownerId, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ScadaDiagramListItemResponseDto>>;
    })
  );
}

scadaDiagramsControllerFindAll.PATH = '/api/scada/diagrams';
