/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DashboardWidgetResponseDto } from '../../models/dashboard-widget-response-dto';

export interface DashboardWidgetsControllerFindOne$Params {
  id: string;
}

export function dashboardWidgetsControllerFindOne(http: HttpClient, rootUrl: string, params: DashboardWidgetsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<DashboardWidgetResponseDto>> {
  const rb = new RequestBuilder(rootUrl, dashboardWidgetsControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DashboardWidgetResponseDto>;
    })
  );
}

dashboardWidgetsControllerFindOne.PATH = '/api/dashboard-widgets/{id}';
