/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SensorCatalogResponseDto } from '../../models/sensor-catalog-response-dto';
import { UpdateSensorCatalogDto } from '../../models/update-sensor-catalog-dto';

export interface SensorCatalogsControllerUpdate$Params {
  id: string;
      body: UpdateSensorCatalogDto
}

export function sensorCatalogsControllerUpdate(http: HttpClient, rootUrl: string, params: SensorCatalogsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<SensorCatalogResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sensorCatalogsControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SensorCatalogResponseDto>;
    })
  );
}

sensorCatalogsControllerUpdate.PATH = '/api/sensor-catalogs/{id}';
