/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { AppService } from './services/app.service';
import { AuthenticationService } from './services/authentication.service';
import { OwnersService } from './services/owners.service';
import { ProjectsService } from './services/projects.service';
import { NodeModelsService } from './services/node-models.service';
import { SensorTypesService } from './services/sensor-types.service';
import { SensorCatalogsService } from './services/sensor-catalogs.service';
import { NodeLocationsService } from './services/node-locations.service';
import { NodesService } from './services/nodes.service';
import { SensorsService } from './services/sensors.service';
import { SensorChannelsService } from './services/sensor-channels.service';
import { AlertRulesService } from './services/alert-rules.service';
import { AlertEventsService } from './services/alert-events.service';
import { NodeAssignmentsService } from './services/node-assignments.service';
import { UserDashboardsService } from './services/user-dashboards.service';
import { DashboardWidgetsService } from './services/dashboard-widgets.service';
import { SensorLogsService } from './services/sensor-logs.service';
import { DashboardService } from './services/dashboard.service';
import { UnpairedDevicesService } from './services/unpaired-devices.service';
import { NodeProfilesService } from './services/node-profiles.service';
import { DeviceCommandsService } from './services/device-commands.service';
import { IoTLogsService } from './services/io-t-logs.service';
import { WidgetBuilderService } from './services/widget-builder.service';
import { WebGisLayersService } from './services/web-gis-layers.service';
import { WebGisCategoriesService } from './services/web-gis-categories.service';
import { WebGisFeaturesService } from './services/web-gis-features.service';
import { WebGisUploadService } from './services/web-gis-upload.service';
import { WebGisCoreGeoJsonService } from './services/web-gis-core-geo-json.service';
import { DocumentsService } from './services/documents.service';
import { UsersService } from './services/users.service';
import { AuditService } from './services/audit.service';
import { NotificationsService } from './services/notifications.service';
import { MlNotificationsService } from './services/ml-notifications.service';
import { MlAnomaliesService } from './services/ml-anomalies.service';
import { MlForecastsService } from './services/ml-forecasts.service';
import { MlDashboardService } from './services/ml-dashboard.service';
import { ReportsService } from './services/reports.service';
import { SearchService } from './services/search.service';
import { ScadaDiagramsService } from './services/scada-diagrams.service';
import { ScadaRuntimeService } from './services/scada-runtime.service';
import { ScadaBindingOptionsService } from './services/scada-binding-options.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    AppService,
    AuthenticationService,
    OwnersService,
    ProjectsService,
    NodeModelsService,
    SensorTypesService,
    SensorCatalogsService,
    NodeLocationsService,
    NodesService,
    SensorsService,
    SensorChannelsService,
    AlertRulesService,
    AlertEventsService,
    NodeAssignmentsService,
    UserDashboardsService,
    DashboardWidgetsService,
    SensorLogsService,
    DashboardService,
    UnpairedDevicesService,
    NodeProfilesService,
    DeviceCommandsService,
    IoTLogsService,
    WidgetBuilderService,
    WebGisLayersService,
    WebGisCategoriesService,
    WebGisFeaturesService,
    WebGisUploadService,
    WebGisCoreGeoJsonService,
    DocumentsService,
    UsersService,
    AuditService,
    NotificationsService,
    MlNotificationsService,
    MlAnomaliesService,
    MlForecastsService,
    MlDashboardService,
    ReportsService,
    SearchService,
    ScadaDiagramsService,
    ScadaRuntimeService,
    ScadaBindingOptionsService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
