/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AppService } from './services/app.service';
export { OwnersService } from './services/owners.service';
