/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectResponseDto } from '../../models/project-response-dto';
import { UpdateProjectDto } from '../../models/update-project-dto';

export interface ProjectsControllerUpdate$Params {
  id: string;
      body: UpdateProjectDto
}

export function projectsControllerUpdate(http: HttpClient, rootUrl: string, params: ProjectsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectResponseDto>> {
  const rb = new RequestBuilder(rootUrl, projectsControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectResponseDto>;
    })
  );
}

projectsControllerUpdate.PATH = '/api/projects/{id}';
