/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AlertRuleResponseDto } from '../../models/alert-rule-response-dto';
import { UpdateAlertRuleDto } from '../../models/update-alert-rule-dto';

export interface AlertRulesControllerUpdate$Params {
  id: string;
      body: UpdateAlertRuleDto
}

export function alertRulesControllerUpdate(http: HttpClient, rootUrl: string, params: AlertRulesControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<AlertRuleResponseDto>> {
  const rb = new RequestBuilder(rootUrl, alertRulesControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AlertRuleResponseDto>;
    })
  );
}

alertRulesControllerUpdate.PATH = '/api/alert-rules/{id}';
