/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface SensorChannelsControllerOverview$Params {

/**
 * Max rows (default 500, max 2000)
 */
  limit?: string;

/**
 * Search by metric code
 */
  search?: string;

/**
 * Filter by sensor id
 */
  idSensor?: string;

/**
 * Filter by sensor type id
 */
  idSensorType?: string;

/**
 * Filter by node id
 */
  idNode?: string;

/**
 * Filter by project id
 */
  idProject?: string;

/**
 * Filter by node model id
 */
  idNodeModel?: string;

/**
 * Filter by owner id (admin only)
 */
  ownerId?: string;
}

export function sensorChannelsControllerOverview(http: HttpClient, rootUrl: string, params?: SensorChannelsControllerOverview$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, sensorChannelsControllerOverview.PATH, 'get');
  if (params) {
    rb.query('limit', params.limit, {});
    rb.query('search', params.search, {});
    rb.query('idSensor', params.idSensor, {});
    rb.query('idSensorType', params.idSensorType, {});
    rb.query('idNode', params.idNode, {});
    rb.query('idProject', params.idProject, {});
    rb.query('idNodeModel', params.idNodeModel, {});
    rb.query('ownerId', params.ownerId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

sensorChannelsControllerOverview.PATH = '/api/sensor-channels/overview';
