/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface SensorChannelsControllerGetReadings$Params {
  id: string;

/**
 * ISO 8601 timestamp
 */
  startTime?: string;

/**
 * ISO 8601 timestamp
 */
  endTime?: string;

/**
 * raw|5m|15m|1h
 */
  aggregation?: string;
}

export function sensorChannelsControllerGetReadings(http: HttpClient, rootUrl: string, params: SensorChannelsControllerGetReadings$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, sensorChannelsControllerGetReadings.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('startTime', params.startTime, {});
    rb.query('endTime', params.endTime, {});
    rb.query('aggregation', params.aggregation, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

sensorChannelsControllerGetReadings.PATH = '/api/sensor-channels/{id}/readings';
