/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SensorChannelDetailedResponseDto } from '../../models/sensor-channel-detailed-response-dto';

export interface SensorChannelsControllerFindOneDetailed$Params {
  id: string;
}

export function sensorChannelsControllerFindOneDetailed(http: HttpClient, rootUrl: string, params: SensorChannelsControllerFindOneDetailed$Params, context?: HttpContext): Observable<StrictHttpResponse<SensorChannelDetailedResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sensorChannelsControllerFindOneDetailed.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SensorChannelDetailedResponseDto>;
    })
  );
}

sensorChannelsControllerFindOneDetailed.PATH = '/api/sensor-channels/{id}/detailed';
