/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateSensorLogDto } from '../../models/create-sensor-log-dto';
import { SensorLogResponseDto } from '../../models/sensor-log-response-dto';

export interface SensorLogsControllerCreate$Params {
      body: CreateSensorLogDto
}

export function sensorLogsControllerCreate(http: HttpClient, rootUrl: string, params: SensorLogsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<SensorLogResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sensorLogsControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SensorLogResponseDto>;
    })
  );
}

sensorLogsControllerCreate.PATH = '/api/sensor-logs';
