/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SensorLogTelemetryTrendsResponseDto } from '../../models/sensor-log-telemetry-trends-response-dto';

export interface SensorLogsControllerGetTelemetryTrends$Params {

/**
 * The UUID of the node
 */
  nodeId: string;

/**
 * Hours of historical data
 */
  hours?: number;

/**
 * Comma-separated channel IDs to filter
 */
  channelIds?: string;

/**
 * Data point interval in minutes
 */
  intervalMinutes?: number;
}

export function sensorLogsControllerGetTelemetryTrends(http: HttpClient, rootUrl: string, params: SensorLogsControllerGetTelemetryTrends$Params, context?: HttpContext): Observable<StrictHttpResponse<SensorLogTelemetryTrendsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sensorLogsControllerGetTelemetryTrends.PATH, 'get');
  if (params) {
    rb.path('nodeId', params.nodeId, {});
    rb.query('hours', params.hours, {});
    rb.query('channelIds', params.channelIds, {});
    rb.query('intervalMinutes', params.intervalMinutes, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SensorLogTelemetryTrendsResponseDto>;
    })
  );
}

sensorLogsControllerGetTelemetryTrends.PATH = '/api/sensor-logs/telemetry/trends/{nodeId}';
