/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SensorLogListResponseDto } from '../../models/sensor-log-list-response-dto';

export interface SensorLogsControllerFindAll$Params {

/**
 * Page number (1-indexed)
 */
  page?: number;

/**
 * Items per page
 */
  limit?: number;

/**
 * Filter by sensor channel ID
 */
  idSensorChannel?: string;

/**
 * Filter by sensor ID
 */
  idSensor?: string;

/**
 * Filter by node ID
 */
  idNode?: string;

/**
 * Filter by project ID
 */
  idProject?: string;

/**
 * Filter by owner ID
 */
  idOwner?: string;

/**
 * Filter by quality flag
 */
  qualityFlag?: 'good' | 'bad' | 'uncertain';

/**
 * Filter by ingestion source
 */
  ingestionSource?: 'api' | 'mqtt' | 'modbus' | 'tcp' | 'http';

/**
 * Start timestamp (ISO string)
 */
  startDate?: string;

/**
 * End timestamp (ISO string)
 */
  endDate?: string;
}

export function sensorLogsControllerFindAll(http: HttpClient, rootUrl: string, params?: SensorLogsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<SensorLogListResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sensorLogsControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('idSensorChannel', params.idSensorChannel, {});
    rb.query('idSensor', params.idSensor, {});
    rb.query('idNode', params.idNode, {});
    rb.query('idProject', params.idProject, {});
    rb.query('idOwner', params.idOwner, {});
    rb.query('qualityFlag', params.qualityFlag, {});
    rb.query('ingestionSource', params.ingestionSource, {});
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SensorLogListResponseDto>;
    })
  );
}

sensorLogsControllerFindAll.PATH = '/api/sensor-logs';
