/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BulkCreateSensorLogsDto } from '../../models/bulk-create-sensor-logs-dto';
import { SensorLogResponseDto } from '../../models/sensor-log-response-dto';

export interface SensorLogsControllerBulkCreate$Params {
      body: BulkCreateSensorLogsDto
}

export function sensorLogsControllerBulkCreate(http: HttpClient, rootUrl: string, params: SensorLogsControllerBulkCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'created'?: number;
'logs'?: Array<SensorLogResponseDto>;
}>> {
  const rb = new RequestBuilder(rootUrl, sensorLogsControllerBulkCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'created'?: number;
      'logs'?: Array<SensorLogResponseDto>;
      }>;
    })
  );
}

sensorLogsControllerBulkCreate.PATH = '/api/sensor-logs/bulk';
