/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OwnerResponseDto } from '../../models/owner-response-dto';

export interface OwnersControllerFindOne$Params {

/**
 * Owner UUID
 */
  id: string;
}

export function ownersControllerFindOne(http: HttpClient, rootUrl: string, params: OwnersControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<OwnerResponseDto>> {
  const rb = new RequestBuilder(rootUrl, ownersControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OwnerResponseDto>;
    })
  );
}

ownersControllerFindOne.PATH = '/api/owners/{id}';
