/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OwnerWidgetsResponseDto } from '../../models/owner-widgets-response-dto';

export interface OwnersControllerGetWidgetsData$Params {
}

export function ownersControllerGetWidgetsData(http: HttpClient, rootUrl: string, params?: OwnersControllerGetWidgetsData$Params, context?: HttpContext): Observable<StrictHttpResponse<OwnerWidgetsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, ownersControllerGetWidgetsData.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OwnerWidgetsResponseDto>;
    })
  );
}

ownersControllerGetWidgetsData.PATH = '/api/owners/reports/widgets';
