/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateWebhookDto } from '../../models/create-webhook-dto';
import { ForwardingWebhookResponseDto } from '../../models/forwarding-webhook-response-dto';

export interface OwnersControllerCreateWebhook$Params {

/**
 * Owner ID
 */
  id: string;
      body: CreateWebhookDto
}

export function ownersControllerCreateWebhook(http: HttpClient, rootUrl: string, params: OwnersControllerCreateWebhook$Params, context?: HttpContext): Observable<StrictHttpResponse<ForwardingWebhookResponseDto>> {
  const rb = new RequestBuilder(rootUrl, ownersControllerCreateWebhook.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ForwardingWebhookResponseDto>;
    })
  );
}

ownersControllerCreateWebhook.PATH = '/api/owners/{id}/webhooks';
