/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OwnerStatisticsResponseDto } from '../../models/owner-statistics-response-dto';

export interface OwnersControllerGetStatistics$Params {
}

export function ownersControllerGetStatistics(http: HttpClient, rootUrl: string, params?: OwnersControllerGetStatistics$Params, context?: HttpContext): Observable<StrictHttpResponse<OwnerStatisticsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, ownersControllerGetStatistics.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OwnerStatisticsResponseDto>;
    })
  );
}

ownersControllerGetStatistics.PATH = '/api/owners/statistics/overview';
