/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface OwnersControllerDeleteWebhook$Params {

/**
 * Owner ID
 */
  id: string;

/**
 * Webhook ID
 */
  webhookId: string;
}

export function ownersControllerDeleteWebhook(http: HttpClient, rootUrl: string, params: OwnersControllerDeleteWebhook$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, ownersControllerDeleteWebhook.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('webhookId', params.webhookId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

ownersControllerDeleteWebhook.PATH = '/api/owners/{id}/webhooks/{webhookId}';
